espruino/BangleApps

apps.json, apps/setting/ChangeLog, apps/setting/settings.js
/cc @gfwilliams.
I tested it locally, it works. It'll be nice to work upstream on an alternate representation for this menu though (one that can go 5:30 instead of 5.5) but this should be as functional as anything.
Fixes: #68
=> feature: all thirty-minute timezones

comms.js, index.html, index.js
- a new tab to list files on your watch
- it displays a table of files, indicating files type when possible
- when clicking on row, trigger download as a file on your host
- refresh button that works similarly to "My Apps" refresh button
As application may create files on the watch, it would be nice to have a simple way to download them on your computer. In my case, I would like to retrieve the GPX files of my activities.
This implementation supports textual and binary files, and in particular, files in append mode, which the final octal sequence in name makes communication a bit hairy.
Without encoding accessed file names (with `encodeURIComponent`), Puck experiences either JSON parsing error (when listing the files) or general failure (when accessing file content)
One thing really …
=> feat: "my files" tab to list and download files

apps/locale/locales.js
Fixes:
Distance: based on the snippet `distance: n => (n < 1000) ? Math.round(n) + locale.distance[0] : Math.round(n/1000) + locale.distance[1]`, distance[0] should be 'meter', locale.distance[1] should be 'kilometer' (or the equivalent). It was swapped the other way in some cases
Temperatur(e): The `e` was missing in some cases
=> locales -> added Hungarian and fixed some typos

apps.json, apps/barclock/ChangeLog, apps/barclock/clock-bar.js
Whoops, sorry about that.
Seems the app still works though
(Snuck in during code cleanup, I'm blaming autoformat)
=> Bar clock: fix SyntaxError

apps.json, apps/widbat/ChangeLog, apps/widbat/widget.js
This has two commits:
0.05: Change color depending on battery level
0.06: Show battery percentage as text
Because I think the coloring is probably nice, but not sure if everybody would like the percentage? If not I could remove that (or maybe add settings?).
=> Battery widget: color by level and percentage as text

apps.json, apps/marioclock/ChangeLog, apps/marioclock/marioclock-app.js
Using now weekday abbrev, space, short dateformat with full-year removed.
This should work for most locales (I hardcoded also replacing a trailing slash esp for en_IL and fr_FR)
=> Take into account discussion from #167

apps.json, apps/gbridge/ChangeLog, apps/gbridge/widget.js
The 10ms timeout delay for the animation was kinda laggy on my watch.
i've changed the timeout delay to 15ms and it looks more fluently now.
Some notifications like Whatsapp group chat have very long titles because they consists of chat name + name of the person. These caused the title to go out of bound. Therefore i've limited the title length to 18 characters.
=> Gadgetbridge notification optimization

apps.json, apps/marioclock/ChangeLog, apps/marioclock/marioclock-app.js
After seeing @gfwilliams suggestions on how to do graphics in a more performant manner I thought I would apply this to the Mario Clock to speed it up.
* Store images inside functions for better performance and reduce ram usage.
* Re-draw all the graphics, make multi-tone for better visuals. Make it more true to the original Gameboy visuals
* Multi-layered background for 'depth' or 'parallax' effects
* Mario jumping and hitting blocks (by way of time change or BTN1 press) will eject a coin like in the game!
=> Mario Clock [Enhancement] - Better performance / graphics

js/comms.js, js/index.js
Fix #216
Cleaner PR than #235: just improves the update process without worrying about special settings/data files.
- Always fill `appsInstalled` before uploading
- Install: if `appid.info` already on device, update instead
- Update: get files to remove from `appid.info`, only remove files which
won't be overwritten anyway
- Remove: get files to remove from `appid.info`
=> Improve update process

apps.json, apps/marioclock/ChangeLog, apps/marioclock/README.md, apps/marioclock/marioclock-app.js
Press BTN3 to toggle what was displayed on the date panel (now referred to as the info panel) between the `Date`, `Battery level %`, and `Temperature`.
Add new character (this will be the last on I add) which is Princess Daisy.
This feature has been added as requests have come in to display widgets which is not possible in 80x80 display mode, nor was this watch face designed to show anything but what it currently does.
So as a compromise, I have updated the app to let you display the date, battery, and temperature in the one panel, by cycling through them on BTN3 press.
I think this works really well, and is not distracting nor taking up valuable space that wasn't already being used.
=> Mario Clock [Enhancement] - Extend info displayed + add Daisy

apps.json, apps/gbridge/ChangeLog, apps/gbridge/widget.js
Do draw the notification, so you can still look up what is playing.
=> gbridge: don't turn on screen at start of every song

apps.json, apps/marioclock/ChangeLog, apps/marioclock/README.md, apps/marioclock/marioclock-app.js
Integrate GadgeBridge (partially any way) in to Mario Clock.
If your BangleJS is connected to you mobile phone via GadgetBridge you will be notified of incoming calls and any generic notification.
Mario (or any of the characters) will show the notification type in a speech bubble, while the relevant details of the notification are scrolled along the info panel.
Pressing BTN1 or BTN3 will cancel the notification
It works fine, but having connected to the IDE, my Apps store, and Gadget bridge sometimes it wont find the device / connect without restarting the watch (turn off and on again). Maybe someone can see if I'm not handling the BLE properly?
The emulator complains the graphics buffer is out of memory. Can anyone see where I can save a few bytes?
=> Mario Clock [Enhancement] - Integrate GadgetBridge

apps.json, apps/marioclock/ChangeLog, apps/marioclock/README.md, apps/marioclock/marioclock-app.js
* In night mode, further left swipes reduce the screen brightness (3 levels) until returning to day-mode
* Persist and load user settings
* Display info banner message when phone connects/disconnects
* Display info banner message when phone battery <= 10% (checks every 10 mins) along with character speech low-battery bubble.
=> MarioClock [Enhancement] - Nightmode + 3 levels of darkness + Settings persisted + New info banner messages

README.md, bin/sanitycheck.js, js/appinfo.js, js/comms.js, js/index.js, js/utils.js
Fix for #243
Adds a "data" section to apps.json, with data files to clean on uninstall   
These are added to `appid.info` as "dataFiles" or "storageFiles", and can contain wildcards.
If an app contains `<appid>.settings.js` and no "data" section, it is assumed to store its settings in `<appid>.settings.json`. So if all you want to do is save settings, you don't need to worry about adding a "data" section.
Also added commit to use this for the `gpsrec` app, as it seemed a good example app with pretty much every feature:
```json
"data": [
{"name": "gpsrec.json"},
{"wildcard": ".gpsrc?", "storageFile": true}
]
```
Which becomes this in `gpsrec.info`:
```json
,"dataFiles":"gpsrec.json","storageFiles":".gpsrc?"}
```
I made sanitycheck `WARN` if a wildcard pattern does not contain the appid, …
=> Data files

apps.json, apps/setting/ChangeLog, apps/setting/settings.js, js/appinfo.js
Didn't see you already improved it a bit, but this also removes the need for appid.info.settings.
(So now `appid.settings.js` is hardcoded in the settings app instead of during upload)
So we could get rid of https://github.com/espruino/BangleApps/blob/242c35dfac89f2e962b807292f8e17dc6d0bdc80/js/appinfo.js#L63-L64 once enough(?) people have updated the settings app.
=> Remove "settings" from appid.info

apps.json, apps/astrocalc/ChangeLog, apps/astrocalc/astrocalc-app.js
The GPS lock can take a long time, and if indoors the app probably cannot be used.
Store the last successful GPS lock data to file, then when the app is next started, the user is presented with the option to use their last GPS position, with the date value updated.
=> AstroCalc [Enhancement] - Store last GPS fix for optional use next time

js/index.js, js/utils.js
I've replaced `href="#"` with `class="c-hand"` (available in Spectre framework) to avoid pages scrolling on top on every click on app changelogs or "Read mode..." links.
=> Removed href="#" that scrolls pages on top

apps/widbatpc/widbatpc.settings.js, apps/widbatpc/widbatpc.settings.json, apps/widbatpc/widbatpc.wid.js
In case the user only wants to know battery status when it is low enough to need charging soon, this setting will stop the widget from being drawn when the battery has >  20% capacity.  
It ain't too pretty here but it works. Suggestions / changes are of course welcome - I recognize my coding skills are pretty rusty. :)
=> Add option in settings to hide battery indicator widget when battery is over 20%.

apps.json, apps/speedo/speedo.js
Enable Widgets in Speedo app
This allows e.g. GPS Recorder to work in the background while running Speedo.
=> Speedo app: Allow widgets

js/index.js
Github links of apps are statically linked to `github.com/espruino`.
These links are wrong if you run a forked App Launcher, probably with unpublished apps.
I added onClick eventListeners for every github link, which generate the right url, if the launcher is not accessed via the main domain.
=> Fix github links of apps for foked launchers

apps.json, apps/gbridge/ChangeLog, apps/gbridge/widget.js
Make gbridge widget report battery status at regular intervals and shortly after connecting, instead of just when the widget is loaded.
=> Report battery status to Gadgetbridge more often

apps.json, apps/imgclock/ChangeLog, apps/imgclock/app.js, apps/imgclock/custom.html
This prevents imgclock from cutting off the date in locales with long date
formats such as "Wednesday, September 10, 2020". Also adjusts the position
and alignment of the date when necessary to prevent it from flowing off the edge of the
screen.
=> imgclock: Make text area wider

apps.json, apps/gpstime/ChangeLog, apps/gpstime/gpstime.js
Like for example at [comms.js](https://github.com/espruino/BangleApps/blob/master/js/comms.js#L156), the `getTimezoneOffset()` return value must be inverted to get correct time zone.
=> gpstime 0.04: Fix shown UTC time zone sign

bin/apploader.js, js/appinfo.js
Thank you for the apploader.js. That is really helpful!
For being able to use the apploader.js I had to change some code.
After installing noble with `npm install -g '@abandonware/noble'` I had to require '@abandonware/noble' instead of just 'noble'.
I can't test the code in a apple browseri, but I think the `ABuffer` is a typo and should be `Buffer`.
=> Require correct module in apploader.js  and fix typo in appinfo.js

apps.json, apps/alarm/ChangeLog, apps/alarm/boot.js
Fixes https://github.com/espruino/BangleApps/issues/433: instead of only selecting the alarms that didn't already run during the current day for scheduling, get all active alarms, sort accordingly and add 24h to the timer if the alarm already ran.
=> Make the alarm scheduling more reliable

apps.json, apps/simpletimer/ChangeLog, apps/simpletimer/README.md, apps/simpletimer/app.js
- Fix BTN2 to really open the launcher
- Remember last set time
I figured the fix for BTN2 doesn't need a separate version/changelog.
=> Simpletimer: remember last set time, make BTN2 work

apps.json, apps/gbridge/ChangeLog, apps/gbridge/settings.js, apps/gbridge/widget.js
I noticed #131 also has this, but it looks like the notification overhaul stuff might take a while to do properly, and the icon was starting to bug me.
It's doing
```js
Bangle.loadWidgets();
Bangle.drawWidgets();
```
To make the show/hide take effect inside the settings, but that really eats RAM somehow.
I'll see if I can figure out why, and/or come up with a better way to show/hide the widget.
(maybe make hidden = width:0)
=> gbridge: Add setting to show/hide icon

apps/cliock/ChangeLog, apps/cliock/app.js
Removes the clear screen and widget loading from each wake so it only runs the first time. Prevents the watch from running out of memory due to redraws after approx. 3 wakes.
=> Stop the cliock face redrawing and running out of memory

apps.json, apps/alarm/ChangeLog, apps/alarm/alarm.js, apps/alarm/app.js
What the title says: this adds an "auto-snooze" option to the alarm editor which, if enabled, schedules a new round of buzzing 10 minutes later as if the snooze button was clicked.
I also added a behaviour fix for snoozing: the way it's implemented currently, snoozing adds 10 minutes to the alarm time and saves it; this means that, for repeating alarms, the next run will be 10 minutes * number of snoozes later, which is not something the user would expect.
=> Add auto-snooze option to alarms

apps/boot/bootloader.js
In timezones in the Western hemisphere (UTC-1 etc.), the local year at UNIX epoch is 1969, not 1970. Therefore, instead of checking getFullYear()==1970, we should be checking getFullYear()<=1970 (I did < 2000 consistent with the existing code below on line 24).
=> Fix for TZ in Western hemisphere

apps.json, apps/marioclock/ChangeLog, apps/marioclock/marioclock-app.js
**Problem:**
Pyramids float above ground. Possibly due to changes to fillPoly function
**Solution:**
Adjust Pyramid Y values
=> BugFix: Marioclock use of fillPoly adjustments

apps.json, apps/gbridge/ChangeLog, apps/gbridge/widget.js
Looks like this fell through during the 'notify' upgrade.
Some apps can keep the LCD pretty much awake all the time with "position" updates. And even if they don't, turning on the LCD for every next song also isn't great for battery life.
=> gbridge: Don't keep LCD on while playing music

apps.json, apps/gpsrec/ChangeLog, apps/gpsrec/app.js, apps/gpsrec/widget.js
I added an option to plot gpsrec tracks on top of OpenStreetMap tiles. 
The option only occurs when OpenStreetMap tiles are installed via the eponymous app. The tiles are centered on the 'center of gravity' of the track, and the track is scaled to the same scale as the OpenStreetMap tiles. The change is mostly a cut-and-paste job of the function drawopenstmap from the OpenStreetMap app.
Also includes a small change to change the color of the "gps signal acquired" icon in the widget from red to green - I found green to be much more visible in bright daylight than red.
=> Gpsrec OpenStreetMap track plotting

apps.json, apps/notifyfs/ChangeLog, apps/notifyfs/notify.js
Now draws properly in the middle of the screen, instead of outside it.
=> notifyfs: fix custom render callback

apps.json, apps/gpsnav/ChangeLog, apps/gpsnav/app.js
The distance to the next way point computation was not quite right, more markedly so over large distances (as noticed on a long road trip). The submitted fix can exhibit machine precision issues on short distances with 32 floats, but the 64 bit floats used by Espruino seem to do just fine when tested.
=> Fix great circle formula in distance calculation

apps.json, apps/largeclock/ChangeLog, apps/largeclock/largeclock.js
The `clearInterval()` stops any boot code or widgets that use intervals from working.
See conversation here: http://forum.espruino.com/conversations/356341/
> Large Clock that line is totally pointless and could just be removed
=> Don't clear all intervals during initialisation of Large Clock

apps/locale/locales.js
App Loader -> Languages -> Select `en_JP`, Upload -> `Morphing Clock` date display is broken(below image).
Web IDE console
```javascript
>var locale = require('locale');
={
name: "en_JP",
currencySym: "\xA5",
dow: function (d,short) { ... },
month: function (d,short) { ... },
number: function (n,dec) { ... },
currency: function (n) { ... },
distance: function (n) { ... },
speed: function (n) { ... },
temp: function (t) { ... },
translate: function (s) { ... },
date: function (d,short) { ... },
time: function (d,short) { ... },
meridian: function (d) { ... }
}
>locale.date(new Date(), 0);
="20/%M/14"
>locale.date(new Date(), 1);
="20/11;/14"
```
I fixed it (fe1c596)
```javascript
>var locale = require('locale');
={
name: "en_JP",
currencySym: "\xA5",
dow: function (d,short) { ... },
month: …
```
=> Fix datePattern and temperature of locale.en_JP

apps/gpsinfo/gps-info.js
I wrote a new function specifically to calculate extended maidenhead squares on Bangle.js, and added it here because I like the functionality of this app better than hamloc. 
Most maidenhead calculators use only 6 characters of precision, which is only enough accuracy to determine a rough neighbourhood. That's fine for HF comms, but VHF can make use of extended accuracy. Eight characters brings that down to about a block, which is enough to meet someone when driving or on foot and sharing locators over radio. Ten would point at one building, and I may expand to that in the future.
=> Added maidenhead readout

apps.json, apps/worldclock/app.js
This PR updates worldclock to 
1) Show bigger time / timezone when only one additional offset is specified
2) Adds some code to facilitate efficient testing of various offset scenarios
3) Refactors the loop for offsets to for readability
4) Creates array constants for readability
5) Renames some variables for readability
6) Removes some unused code.  (Code for 12hr view left commented as apparent work in progress)
=> Update world clock for larger secondary timezone display

apps.json, apps/devstopwatch/ChangeLog, apps/devstopwatch/app.js
This PR updates devstopwatch to keep all state related variables in a `state` object which is persisted to storage on `kill` and read from storage on app launch. This gives the stopwatch the illusion of continuing to run in the background while other apps are active.
Using flash storage for this seems a bit overkill but I couldn't find a way of writing to global RAM that persists between app launches. Does such a mechanism exist?
=> devstopwatch - Persist stopwatch state

apps/activepedom/widget.js
my hide modification broke the widget, I was experiencing the widget resetting steps back to zero in the middle of the day.  This is because the draw() function updates the lastupdate variable. So move my return code to after that has been done.
=> fixed activepedom widget, only exit after lastupdate has been recorded

apps/blobclk/clock-blob.js, apps/counter/counter.js
The bug in "counter" was that it wasn't setting the colour when updating the screen. That means if the widgets are not drawn and the colour is set to 0, then the screen is drawn in black and you can't see anything. It also means that if the last widget to be drawn left the colour as something other than white, then the counter is not drawn in white. The fix is to set the colour to white explicitly.
I found that "blobclk" took a noticeably long time to display the time on the screen when the LCD is powered on. Moving the `redraw()` call to happen a bit earlier makes an improvement, but not a massive one. It would be better to make "blobclk" more efficient if possible, but this is still an improvement for now, in my opinion.
=> Make counter work even when widgets are hidden, and make blobclk draw the time a bit sooner when LCD is powered on

apps.json, apps/aclock/ChangeLog, apps/aclock/clock-analog.js, apps/beebclock/ChangeLog, apps/beebclock/beebclock.js, apps/dotclock/ChangeLog, apps/dotclock/clock-dot.js
Because we have a separate widget (`widchime`) for that now
=> Remove hardcoded hour buzz from aclock, beebclock, dotclock

apps.json, apps/widchime/ChangeLog, apps/widchime/widget.js
Well, this is a bit embarrassing...   
Somehow the code I tested worked fine, and then I got fancy and removed semicolons before pushing, apparently without testing.   
Which means that
```js
if (!type) return
function chime() {
```
becomes a single statement, `chime()` isn't actually defined, and it now chimes the hour by crashing instead of buzzing.
Actually only needed two semicolons to fix, but I just added them everywhere (and will try to remember this the next time I think code w/o semicolons looks cleaner)
=> fix widchime: make it actually chime the hour instead of crashing

apps.json, apps/gbmusic/ChangeLog, apps/gbmusic/README.md, apps/gbmusic/app.js
Change the color selection to always mix in a bit of every color, so you never end up trying to read e.g. 100% blue. 
It also turns out that having your volume lowered to 0 every time you long-pressed BTN3 to restart the watch is kind of annoying.   
Added double/triple pressing BTN2 to navigate between songs.
And a bunch of changes to attempt to lower memory usage, which in most cases actually meant simplification of the code :-)
=> gbmusic: Increase text brightness, improve controls, (try to) reduce memory usage

apps.json, apps/gbmusic/ChangeLog, apps/gbmusic/app.js, apps/gbmusic/widget.js
* only auto-start from clock apps, [(thanks for the hint)](https://github.com/espruino/BangleApps/pull/686#issuecomment-799260231)
* reformat widget code (as I was touching it anyway)
* auto close after `2*<song duration>` or 1 hour of inactivity: some (i.e. my) phones don't bother ending music updates when music simply finishes playing. (Duration seems reliable enough, but using the 1 hour fallback just in case some players don't report it.)
=> Gadgetbridge Music Controls: only auto-start from clock apps, auto close after 1 hour of inactivity 

apps.json, apps/gbmusic/ChangeLog, apps/gbmusic/README.md, apps/gbmusic/app.js, apps/gbmusic/settings.js
My sleeve touching the screen causing random song skips was bugging me, and I pretty much coded "completely disable touch controls" before realizing these were happening while the screen was off. So now it has three options :-p
Maybe we should just stick with a unconditional `isLDCOn` check?
But when the weather improves (i.e. no more long sleeves) blindly swiping to the next song might be nice. (At least that's the excuse I tell myself for not throwing away my shiny new code.)
Also a minor bugfix for dynamic colors, to make them actually behave as the comments claim they do.
=> gbmusic: setting to disable touch controls (and a small bugfix)

apps.json, apps/gbmusic/ChangeLog, apps/gbmusic/README.md, apps/gbmusic/app.js, apps/gbmusic/settings.js
* Setting to disable double/triple press control for http://forum.espruino.com/comments/15984222/
* Remove touch controls setting, because [firmware `2v10` will ignore touch/swipe events while the LCD is off anyway](https://github.com/espruino/Espruino/commit/917ceab9710a8ed1a8f1d50aa01dcae25059e2a5), so just having a setting to disable them seems silly.
(we still check the LCD is off before handling touch events, as probably not everybody is using `2v10` yet ;-)
* Don't clear the area while redrawing for fade out, to prevent flicker
* Some JSDoc improvements
=> gbmusic: Setting to disable double/triple press control, remove touch controls setting, reduce fadeout flicker

apps.json
Emulator has stopped working because the clock is split into dynamic languages classes. Turning off the emulator otherwise people will think it doesn't work
=> sliding text clock BUGFIX: turning emulator option off. 

apps.json, apps/multiclock/ChangeLog, apps/multiclock/digi.js, apps/multiclock/timdat.js
Hi there,
this is my first contribution, so I hope that I did not miss any requirements. If so, please tell me and I will fix my commit respectively.
I really like the multiclock timdat.js clock. However, it is not using the internationalisation mechanism. See also https://github.com/espruino/BangleApps/issues/136
Thus, I adapted the code - trying to change as few things as possible. I also adapted digi.js, which was quite simple. I did not touch txt.js since IMO it is alright to have this as an English skin and it would require a major effort to be adapted for other languages.
One technical remark: In timdat.js, a special date format consisting of day of week, month and day of month is used that is not available as a date pattern. Hence, I decided to build it there. I used this code …
=> multiclock - Added localisation to digi.js and timedat.js

apps/gbridge/widget.js, apps/notify/notify.js
Most of the support was already there, so this is just a few small steps:
- `notify.js` gets a `dismiss_and_hide()` exported function that can send the "notify-" event to Gadgetbridge, if installed
- `dismiss_and_hide()` is called when the Bangle.js screen is touched, instead of just `hide()`
- Gadgetbridge's `widget.js` saves "notify"-type events to a variable
- Gadgetbridge's `widget.js` sends a `DISMISS` action back to the Android app on "notify-" events, using the saved event data
Note that this is a limited implementation. For example, only the most recent notfication is saved (when a new one comes in, the old one is overridden in the variable), so it will be dismissed on the phone. A more advanced implementation might make it possible to choose which notification to dismiss.
From my …
=> Add support for dismissing Gadgetbridge notifications through notify

apps.json, apps/launch/ChangeLog, apps/launch/app.js
I was playing with a custom theme, and apps showed up in the wrong colour until I scrolled over them, this fixed it.
=> Small theme colour fix for Launcher

apps/slidingtext/slidingtext.locale.es.js
Fixed the words for 7, SEITO is now SIETE.
20, VEINTA is now VEINTE
=> Fix translation slidingtext.locale.es.js

apps.json, apps/weather/ChangeLog, apps/weather/app.js, modules/Layout.js
I took a stab at updating the weather app to use the new Layout library.
Some notes:
- Experimenting with different layout variations is very convenient!
- I found a small hack to sort-of-emulate different screen sizes: `g.getWidth=()=>176;g.getHeight=()=>176;`
- The initial layout / render adds a rather noticeable delay to the app's loading time
- This is made worse by the fact that I construct the layout with placeholder labels (which implicitly calls `layout.update()`), and then I immediately fill out the labels with actual data (if available) and call `update()` again. It would be nice if there was a way to tell the Layout constructor to skip that initial `update()` call.
- I could see memory usage becoming an issue on the Bangle 1. On my watch this change increases memory usage from …
=> weather: Use Layout library

apps.json, apps/menusmall/ChangeLog, apps/menusmall/boot.js
Same as EspruinoDocs graphical_menu.js: https://github.com/espruino/EspruinoDocs/pull/614
I think I also got the appRect tweaks, seemd to look allright in the emulator...   
I did notice it got rid of `Bangle.drawWidgets();` though, not sure if that is ok?
=> menusmall `wrap` option

apps/menusmall/boot.js
Apply https://github.com/espruino/EspruinoDocs/pull/616 / https://github.com/espruino/Espruino/pull/2085
Only small optimizations, so I figured skipping the version bump would be ok.
- remove unused variable
- remove unused parameter from `select()`
- shave a few bytes off `move()`
If a numerical item has `item.wrap` we no longer check if `item.min/max` is set, because your menu will be broken either way.
=> menusmall: follow latest E_showMenu improvements

apps.json
This app used to be tagged `b2` only, but got both devices during the great `tags`->`supports` update: https://github.com/espruino/BangleApps/commit/a94790391a9f13ab83c9658ba48080b9d5967190#diff-70e375511009c0cb767fdc64667e148359c6d6b7b8cf4f100b7eb0e853f83529L8-R10
=> apps.json fix: fwupdate is for Bangle.js 2 only

apps.json
I've got the data going into Home Assistant already.
=> BLE GATT Battery Service works on Bangle JS 2

apps.json, apps/swiperclocklaunch/ChangeLog, apps/swiperclocklaunch/boot.js
Fixed issue with Swiper Clock Launch causing launcher not to show due to "mode" being undefined
=> Bugfix: Swiper Clock Launch

apps.json, apps/gbridge/sample_messages.js, apps/weather/ChangeLog, apps/weather/app.js, apps/weather/lib.js
- use `g.fillPoly` when device doesn't support `g.fillPolyAA`
- use (mostly) 3-bit colors instead of dithering
- crash a bit less on incomplete weather data
=> weather: Bangle.js 2 support

apps.json, apps/compass/ChangeLog, apps/compass/compass.js
The box being cleared was off so on single or double digit bearings artefacts remained either side
=> Bugfix: Compass bearing not clearing correctly

apps.json, apps/barclock/ChangeLog, apps/barclock/clock-bar.js
At least, it works just as well as on the Bangle.js 1, where it also breaks from fullscreen notifications.   
So fixed that, and now it really works fine on both devices.
=> Barclock works fine on the Bangle.js 2 :-)

apps.json, apps/locale/ChangeLog, apps/locale/locale.html
Fixes #892
I figured it would be a good idea to not read+parse the settings file every time something wants to draw the time, so we remember it after the first call.
=> locale: Apply 12hour setting to time

apps.json, apps/widbatpc/ChangeLog, apps/widbatpc/README.md, apps/widbatpc/widget.js
When displaying the charging indicator, the whole widget moves to the right, now including the charge bar.
Also some minor typos in the readme.
=> widbatpc: Fix drawing the bar when charging

apps.json, apps/93dub/ChangeLog, apps/93dub/README.md, apps/93dub/app.js
Currently the `93dub` watch face displays midnight for the 12 hour time setting as 00:00. This PR changes it to more correctly display 12:00.
I've tested this change in the emulator to verify that the 24 hour time setting remains unchanged for various dates with hour values of midnight (00:00). Testing these same inputs for the 12 hour setting now displays values of 12:00 for 00:00.
=> Adjust 93dub midnight for 12hr time

apps.json, apps/93dub/ChangeLog, apps/93dub/README.md, apps/93dub/app.js
This should fix a crash for 93dub that only shows up on Thursdays. When this happens it even seems to disable navigation back to the Settings app from the button on a Banglejs 2 when set as the default clock.
I've tested this on the emulator, and it appears to do the correct thing now.
=> Fix 93dub on Thursdays

apps.json
- Tagged poweroff app with "tool"
- Allowed it for emulator
=> Poweroff app -> tool and emulator

apps.json, apps/calendar/ChangeLog, apps/calendar/README.md, apps/calendar/calendar.js, apps/calendar/settings.js
Adds a setting in a Calendar app which allows it to start the week on Sunday rather than Monday.
=> Allow Calendar app to begin on Sunday

apps.json, apps/gbmusic/ChangeLog, apps/gbmusic/app.js
We forgot to reset the background color when drawing the scrolling title.
Not very noticeable, until you get a notification and suddenly the title starts flashing in sync with the `messages` widget ;-)
=> gbmusic: Fix scrolling title background color

apps.json, apps/messages/ChangeLog, apps/messages/widget.js
I figured that re-adding the `touch` listener every time we redraw the widget should prevent most breakage from apps doing `removeAllListeners`
=> messages: Open app when touching the widget (Bangle.js 2 only)

apps.json, apps/qmsched/ChangeLog, apps/qmsched/widget.js
Fixes an issue where qmsched would cause widgets to be drawn twice on every app load.
This was especially noticeable on the Bangle 1 when it's snowing outside, since the snowflake icon renders particularly slowly :)
=> qmsched: Correctly size widget on load

apps.json, apps/rtorch/ChangeLog, apps/rtorch/app.js
- Use setUI instead of Bangle.watch
- Quickstart sequence does just work on Bangle 1, since Bangle 2 is missing the additional two buttons and the only remaining button is often used for functions in apps (see: https://github.com/espruino/BangleApps/pull/1083#issuecomment-993444082)
=> Red Torch - Update for Bangle 2

apps.json, apps/pooqround/ChangeLog, apps/pooqround/README.md, apps/pooqround/app.js
Add tap-to-enhance, turning on complications transiently.
Remove some dead code.
Fix a fairly serious bug arising from version skew in the orientation-dependent update rate mechanism, which was probably making a lot of unnecessary events.
Reduce the number of screen clears to eliminate unmotivated blanking.
Alter readme to elucidate that (as I now understand) lack of backlight-on-twist was a bug in the system, and this is not a permanent feature of the watchface.
=> pooq Round: tap for transient complications; bugfixes

apps.json
Looks like the app.js definition was lost during merging.
Fixes https://github.com/espruino/BangleApps/issues/1095
=> Fix missing app.js defintion of clicompleteclock (fix #1095)

bin/sanitycheck.js
Adds an error to sanitycheck.js for incorrectly sized app icons, to help catch issues like #1121. As something of a side-effect, it also ensures that app icon files follow the format described in the README.
Since there are currently 24 apps that would trigger the error, and I imagine they won't all be fixed right away, I added a `GRANDFATHERED_ICONS` list that makes them only trigger a warning instead of an error. Once the existing icons are fixed the `GRANDFATHERED_ICONS` list can be removed.
Circleclock should be fixed by #1113, so I didn't include it in the `GRANDFATHERED_ICONS` list.
These icons currently trigger the warning:
```
Warning: JS icon hebrew_calendar.img should be 48x48px but is instead 0x0px
Warning: JS icon fontclock.img should be 48x48px but is instead 40x40px
Warning: …
```
=> sanitycheck: Error on incorrectly sized js icons

apps.json, apps/qmsched/ChangeLog, apps/qmsched/lib.js
Whoops, properly check WIDGETS is set before redrawing the widget.
=> qmsched: fix #1117: properly check WIDGETS is set before redrawing the widget.

apps/widbt/ChangeLog, apps/widbt/widget.js
The bluetooth widget turns the screen on on bluetooth status change. For me at least, this is undesirable since I don't sleep in the same room as my phone, but close enough that it will, from time to time, connect or disconnect, disturbing my wife's sleep.
=> Disable screen turn on on bluetooth status change

apps/gpsinfo/gps-info.js
1. (bugfix) Workaround for a crash in toUTCString() if fix.time has the value "undefined", see https://github.com/espruino/BangleApps/issues/1155
2. (improvement) The 4-dot progress indicator is replaced by the number of satellites in view.
Tested on Bangle.js 2 with firmware 2v11
=> GPS Info App: Added number of satellites in view and fixed crash with GPS time

apps/calculator/ChangeLog, apps/calculator/app.js
added grid positioning and for Bangle.js 2 swipe controls to switch between numbers, operators and specials. 
On Bangle.js 2 only one page of numbers, operators and specials is displayed. Swiping left displays the operators, swiping right displays the specials and swiping up or down displays the numbers. After an operator is entered, it also switches to the numbers.
=> Added grid positioning and swipe controls to calculator app

apps/locale/locales.js
I am providing small fixes for the Italian localization.
1. using : to separate hours from minutes, instead of .
2. datePattern: changed to the more usual way of representing dates in Italian.
3. datePattern: fixed so that clocks such as Anton Clock work fine
4. day: removed an extra space.
=> Fixed Italian localization

apps/calendar/calendar.js
If week is set to start on Sunday, make Saturday (last row) and Sunday (first row) have weekend colors.
=> Update calendar weekend colors for start on Sunday

apps.json, apps/bthrm/ChangeLog, apps/bthrm/boot.js, apps/bthrm/bthrm.js, apps/bthrm/recorder.js, apps/bthrm/settings.js, apps/recorder/ChangeLog, apps/recorder/README.md, apps/recorder/app.js, apps/recorder/widget.js
* Make overriding the HRM event optional
* Emit BTHRM event for external sensor
* Add recorder app plugin
=> BLE Heart Rate Monitor improvements

apps.json, apps/antonclk/ChangeLog, apps/antonclk/README.md, apps/antonclk/app.js, apps/antonclk/settings.js
The ISO-8601 calendar weeknumber added as or behind weekday.
The "display with seconds " mode was untouched.
No "core" update this time ;)
PS: copied GIST for ISO-Week # is als "MIT-license"
=> Anton-Clock can optionally show ISO-8601 calendar weeknumber

apps.json, apps/menuwheel/ChangeLog, apps/menuwheel/boot.js
Because apps/libraries expect setUI to clean up touch handlers.
(I spend hours wondering why my `E.showScroller` was broken, turns out it was because I opened a menu :-()
=> menuwheel: override Bangle.setUI to clear up touch handler

apps/boot/bootupdate.js, apps/setting/settings.js
As discussed in [https://github.com/espruino/BangleApps/pull/1199](https://github.com/espruino/BangleApps/pull/1199).
This adds the combination possibility HID as an option in the settings to be advertised on boot as well.
=> Add mouse keyboard combination HID to Banglejs settings and boot.

apps.json, apps/messages/ChangeLog, apps/messages/app.js
- Use theme colors and app-specific icon colors
- Spread message action buttons out
- Back button now goes back to list of messages
Still draft, because:
Haven't had a proper look at B1 yet, maybe it's better to stick with custom colors instead of theme there?
I'm not entirely sure if `fg/fg2`+`bg/bg2` are supposed to be used in this way (as alternating rows)    
Also: is it me, or is the Instagram icon broken?
=> messages improvements

apps/openstmap/custom.html
Added leaflet geosearch control to OpenStreetMap custom HTML page.
https://github.com/smeijer/leaflet-geosearch MIT License
=> OpenStreepMap custom: Add leaflet geosearch control

apps/qmsched/app.js, apps/qmsched/lib.js
Thanks for pointing out `Bangle.CLOCK`, I know I've seen it before, but totally forgot about it.   
Also just checks for `global.setAppQuietMode` instead of `__FILE__`, so that should work with borked `__FILE__` as well.
I figured this wouldn't need a version bump, because it hasn't made it into the official store yet.
=> qmsched: use Bangle.CLOCK instead of __FILE__

apps/circlesclock/app.js
Just a minor bugfix:
* Do not overwrite circle on event (e.g. charging) if there is a circle configured for that place
I did not increase the version number as this is just a very minor fix and the current version of the clock was released yesterday.
=> Circlesclock: Minor fix

apps.json, apps/touchmenu/ChangeLog, apps/touchmenu/touchmenu.boot.js
- Menu event listeners are now properly cleared when going directly from the menu to the launcher
- Menu now fills all available screen space, respecting widgets if there are any (using `Bangle.appRect`)
=> Fix a couple of issues with TouchMenu

apps/sleepphasealarm/ChangeLog, apps/sleepphasealarm/app.js, apps/sleepphasealarm/metadata.json
Make app compatible with Bangle.js 2:
- check hardware
- _drawString(s, x, y)_: removed _x_, always centered
- _drawString(s, y)_: _g.reset()_ before _g.clearRect(...)_
- adjust heights for Bangle.js 2 for each _drawString(s, y)_ call
- _drawApp()_: on Bangle.js 2's always on display save energy by drawing time only at every next minute
- _drawTime()_: hide seconds on Bangle.js 2 (only refreshed every minute)
- _drawApp()_: add _"Alarm at "_ to distinct from actual time (no difference in seconds)
- execute _load()_ on Bangle.js 2's BTN
Make app compatible with _E.showMessage(...)_ on new firmware:
- adjust actual time height to be drawn above the alarm time from _E.showMessage(...)_
=> sleepphasealarm: Compatibility to Bangle.js 2 and new firmware

apps/diract/ChangeLog, apps/diract/README.md, apps/diract/diract.js, apps/diract/metadata.json
Twice as responsive and far more sensitive at slight expense to battery life.
=> Improved proximity identification settings specific to Bangle.js

apps/acmaze/ChangeLog, apps/acmaze/app.js, apps/acmaze/metadata.json
Turns out bottom widgets (specifically, digital clock widget) were disappearing during maze generation. Still not clear _why_, but calling `Bangle.drawWidgets()` from inside the `Maze` object constructor solves this.
Also: say "Btn1" in order to be less confusing on `bangle.js 1` (before I ask people to test this app on that platform).
=> Avoid erasing bottom widgets

bin/language_scan.js
I'm working on the Italian translation and I noticed that `language_scan.js` prints *Missing translation* for existing translations.
This commit fix the issue.
=> use the correct key to check for translations

apps/matrixclock/matrixclock.js
I fixed 2 Problems in MatrixClock: 
1. When trying to clear the old Text, so it could get updated, previously it got cleared by using "g.theme.fg" as color which is white. But it should be "g.theme.bg" which is black. 
2. Previously the Date got "deleted" by the falling Shards, this problem should be fixed.
=> MatrixClock: Fixed Color-Issues and Screen-Update-Order

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json, apps/gbridge/ChangeLog, apps/gbridge/PROTOCOL.md, apps/gbridge/metadata.json, apps/gbridge/widget.js
This seems like a useful thing to include for GadgetBridge: not only do you get the nice lightning bolt icon, but it also means the app knows to dismiss the "low battery" warning when the watch is connected to a charger.
Before you merge:
- `charging`:`true/false` seemed like the cleanest option, but I have no idea how frugal we need to be with bluetooth-bytes, does it really matter? Because then I guess `pow`:`1/0` (or `chrg` or even `c`...) would be better.   
Asking because this will also need some changes in GadgetBridge and EspruinoDocs, so I'd like to get it right instead of amending 3 PRs later on ;-)
- I noticed we could also include `volt` (from `NRF.getBattery()`?), not sure if that has any added value over `bat`, but I'd be happy to work it in while I'm messing with this code …
=> android/gbridge: Include charging state in battery updates to phone

apps/bthrm/ChangeLog, apps/bthrm/boot.js, apps/bthrm/bthrm.js, apps/bthrm/default.json, apps/bthrm/metadata.json, apps/bthrm/recorder.js, apps/bthrm/settings.js, apps/recorder/widget.js
BTHRM
* Allow reading additional data if available: HRM battery, position and RR
* Better caching of scanned BT device properties
* New setting for not starting the BTHRM together with HRM
* Save some RAM by not defining functions if disabled in settings
* Always emit BTHRM event
* Cleanup promises code and allow to configure custom additional waiting times to work around bugs
* Disconnect cleanly on exit
Recorder
* Log src property of HRM-event
* Allow creating new files instead of overwriting
=> BTHRM - Allow reading more characteristics if the sensor supports them

apps/hrm/ChangeLog, apps/hrm/heartrate.js, apps/hrm/metadata.json
The heart rate monitor app forces the backlight to be on and the screen not to lock.
There is no need on the Bangle 2, as the screen is readable with the backlight disabled.
=> HRM: Don't force screen to be on for Bangle 2.

apps/messages/app.js
In: https://github.com/espruino/BangleApps/issues/1294#issuecomment-1012921003, @gfwilliams said: 
"Right now the message title font does change dynamically depending on how much text there is, so doing the same for the body text is probably no big deal."
This mirrors the implementation used for the message title in the message body. 
I can see there are other issues open related to controlling font size globally. But I think the main need for most users will be in the messages app, where the ability to choose a larger font for body text would be useful even in the short term, IMHO. Perhaps getting rid of the buttons in favor of labels to view next / previous via swipe direction would leave more screen real estate for larger text as well. The buttons do not work for me most of the time. …
=> Messages: Use large font for message body when message < 2 lines 

apps/locale/locales.js
I think the day of week should not be part of the date in fr_FR as it is not in most of the other locales.
Fteacher suggested this in the forum: http://forum.espruino.com/comments/16389770/ as well.
**Note**: i am **not** a french speaker so i am not 100% sure about this change but in my opinion this should be changed.
=> Update fr_FR locales.js: dow not part of date?

apps/locale/locale.html
As most apps aren't translated, I found odd the mixed language on apps, so I thought it would be useful to have a locale with formatting but no translation. this way the apps language are all in english, but the format for numbers, dates, etc are in my locale.
As forum post: http://forum.espruino.com/conversations/371915/#comment16353541
=> Option to keep or not the textual translations

apps/recorder/interface.html
I had a broken recorder track which causes errors downloading the GPX file.
I was not able to see the errors except in the web console.
So here are changes which make the errors visible if they happen.
=> Recorder webinterface: Catch some errors

apps/boot/ChangeLog, apps/boot/bootupdate.js, apps/boot/metadata.json
Sorts the *.boot.js files during bootupdate.js and allows an optional priority with the following scheme: 
`name.<optional_priority>.boot.js`
The resulting order would be like this:
```
xyz.0.boot.js
xyz.3.boot.js
abc.boot.js
xyz.boot.js
```
=> boot - Sort *.boot.js files

apps/neonx/ChangeLog, apps/neonx/README.md, apps/neonx/metadata.json, apps/neonx/neonx.app.js, apps/neonx/neonx.settings.js
I added optional settings to switch colors whenever the bangle is unlocked. Per default, those settings are off to keep the standard behavior and design. This especially helps in full-screen mode to easily detect the lock state while not changing the cool design of this watch face.
Also, I found that the watch face is updated every 10 seconds - wouldn't it be enough to do it every 60 seconds in order to save some battery? What do you think about this PR @bundyo?
=> [NeonX & IO X] Added optional settings to show the lock status.

apps/boldclk/ChangeLog, apps/boldclk/bold_clock.js, apps/boldclk/metadata.json
Removed "wake LCD on face-up"-feature of Bold Clock: A watch-face should not set things like "wake LCD on face-up". 
If you want, that the LCD get activated when facing up, go to Settings > System > LCD > Wake on FaceUp.
=> Bold Clock: Removed "wake LCD on face-up"

apps/crowclk/ChangeLog, apps/crowclk/crow_clock.js, apps/crowclk/metadata.json, apps/matrixclock/ChangeLog, apps/matrixclock/matrixclock.js, apps/matrixclock/metadata.json, apps/slidingtext/ChangeLog, apps/slidingtext/metadata.json, apps/slidingtext/slidingtext.js
Removed "wake LCD on face-up"-feature of MatrixClock, Crow-Clock and SlidingText-Clock: A watch-face should not set things like "wake LCD on face-up".
If you want, that the LCD get activated when facing up, go to Settings > System > LCD > Wake on FaceUp. 
This pull-request is a successor of my previous pull-request number 1490 ( [https://github.com/espruino/BangleApps/pull/1490](https://github.com/espruino/BangleApps/pull/1490) ), where Gordon Williams mentioned, that other watch-faces might also contain this code.
=> 3 Clock-Apps: Removed "wake LCD on face-up"

apps/timeandlife/metadata.json
The shortName for the Time and Life app was misspelled in the metadata, so it showed in the menu as "Time and Lfie". This PR fixes that.
=> Fix typo in Time and Life shortName

apps/daisy/ChangeLog, apps/daisy/metadata.json
The new `daisy` clock was missing a line in `metadata.json` to make is actually usable as a clock, as it stands you can only open it as an app from the launcher but not set it as a clock in the settings.
=> Fix Daisy Clock

apps/qmsched/ChangeLog, apps/qmsched/app.js, apps/qmsched/metadata.json
Whoops, this app was quite broken with the new menu, because of how it abused `format`.
=> qmsched: support new bangle.js 2 menu, add /*LANG*/ hints

apps/bthrm/ChangeLog, apps/bthrm/boot.js, apps/bthrm/metadata.json, apps/bthrm/settings.js
Set a specific sensor to use to prevent chaos when more than one is in range. Without a set sensor the old "connect to first found" behaviour is kept.
=> bthrm - Allow scanning for sensors in settings

apps/boot/bootupdate.js
No version bump: assuming that where it really matters we already set a priority, which worked fine.
=> boot: fix alphabetic sorting of *.boot.js files

apps/cscsensor/ChangeLog, apps/cscsensor/README.md, apps/cscsensor/cscsensor.app.js, apps/cscsensor/metadata.json
The Cycling speed sensor app is now compatible with the BangleJS2.
I have decided against using the Layout library because I could not reproduce the complete layout with it, e.g. white border, text alignment left/right. For these I would need to create custom elements with render functions. Also I did not want to change the layout because that might not have been in the interest of the original author. So between forking the app for a new layout and keeping the current draw methods I decided to the latter.
So I recalculated all magic position and size numbers given the BangleJS1 screen size of 240x240. The look on BangleJS1 should be unchanged (I have not seen a difference) while all items just scale down for the BangleJS2. Unfortunately the changes do not make the code look any prettier, …
=> cscsensor: Make BangleJS2 compatible

modules/Layout.js
I'm not overly happy with this, it feels wrong to add options to `Layout` just for passing through to `setUI`...
I guess the underlying unhappiness comes from `Layout` calling `setUI` at all. Maybe `Layout` should only modify `Bangle.btnWatch` directly? That way you could at least always call them in the same order:
```js
setUI({mode: "custom", back: ()=>{...} });
layout = new Layout({...}); // layout containing buttons
setUI({mode: "updown", back: ()=>{...} }, dir=>{...} ); 
layout = new Layout({...}); // layout without buttons
```
=> Layout: add support for `back` option

apps/seiko-5actus/ChangeLog, apps/seiko-5actus/app.js, apps/seiko-5actus/metadata.json
Your response in my last pull request made me realize how simple it would be to keep the hands centered and shrink the image size down so there wasn't a bunch of extra transparency around each image.
I've shrunk the minute and hour down so that the point I need centered stays centered but removes all the whitespace around the images. The second hand isn't able to be changed due to already being at the max size it can be.
Hopefully this improves memory utilization a little
=> Seiko-5actus: shrunk hand images to save memory

apps/bledetect/ChangeLog, apps/bledetect/bledetect.js, apps/bledetect/metadata.json, apps/sleepphasealarm/app.js
Set bledetect BangleJs2 compatible and show Widgets. Bledetect works on BangleJs2 without any changes.
Also fix a typo in a comment of sleepphasealarm
=> bledetect: BangleJs2 compatible

apps/recorder/ChangeLog, apps/recorder/metadata.json, apps/recorder/widget.js, apps/run/ChangeLog, apps/run/app.js, apps/run/metadata.json, apps/run/settings.js, modules/exstats.js
This fixes a few issues with the `run` app, mostly ones I introduced with the notifications, but not exclusively. It also removes an unnecessary variable assignment in the `recorder` app.
* Don't try and enable/disable recording if the `recorder` widget is unavailable
* Don't configure notifications for stats which do not have a box enabled
* Look up the `vibTimes` rather than the `vibPatterns` to determine the current notification configuration
* Use the previous notification state to determine the next state, rather than the current stat (decreases notification drift)
* Reset GPS state in `reset` to prevent distance miscalculation when stopping one run and starting another
=> Fix run notifications bugs and improve accuracy

modules/exstats.js
If you start the run before the first GPS fix, Speed may be NaN when the first fix occurs.
=> [RUN] Fix.speed could be NaN

apps/run/README.md, modules/exstats.js
This has `exstats` keep track of the maximum BPM reached while active and emit a `changed` event every time it goes up. `run` makes this one of the options available to put in a box.
=> [exstats/run] Include maxbpm as a stat that can be tracked

apps/antonclk/ChangeLog, apps/antonclk/app.js, apps/antonclk/metadata.json
bugfixed calendar week shown 3 digits (`substring` -> `slice`) furthermore replaced deprecated `substr` by `slice`
=> Antonclk fix calweek substring

apps/locale/locales.js
Added norwegian locale to the list, and also listed our three special characters æ, ø and å in the fallback list. They are all in the codebook, but I'm unsure if they will be rendered correctly with the current code (the two last days of the weeks contains the ø).
=> Added norwegian locale

apps/fuzzyw/fuzzy_strings.json, apps/locale/locales.js
Norway has two written languages, Bokmål and Nynorsk. This adds the Nynorsk variant.
I was uncertain which language code to use.
nn_NO is the POSIX identifier, used in Linux et.al. so this pull request uses that, however as mentioned in https://github.com/espruino/BangleApps/pull/1665 the language code that has been used for Norwegian Bokmål is "no_NB" (ie. the other way around, country_LANGUAGE rather than language_COUNTRY). Browsers similarly use "nn-NO" for nynorsk, and "nb-NO" for bokmål.
=> Added Norwegian Nynorsk translation

apps/sched/ChangeLog, apps/sched/README.md, apps/sched/lib.js, apps/sched/metadata.json, apps/sched/sched.js
Only set `last` for alarms to prevent a wrong output of `getTimeToAlarm` for a timer already used at same day.
=> sched: Fix `getTimeToAlarm` for timers

apps/sched/ChangeLog, apps/sched/lib.js, apps/sched/metadata.json
Fix undefined output of `getTimeToAlarm` on an alarm that is already in the past to check for the next dow instead of the actual dow.
- if alarm.t < currentTime, (time.getDay() + 1) % 7
=> sched: `getTimeToAlarm` check next dow if t<now

apps/kbswipe/ChangeLog, apps/kbswipe/lib.js, apps/kbswipe/metadata.json
@gfwilliams
Change the way the display is updated as to keep user input trace intact until they lift their finger from the screen. 
Now only the marker is updated every second as opposed to the whole screen. To achieve this the marker is reimplemented outside the wrapString-method with g.fillRect() and g.clearRect() as well as a newly introduced function findMarker().
=> Update apps/kbswipe/lib.js (Swipe keyboard)

apps/pebble/ChangeLog, apps/pebble/README.md, apps/pebble/metadata.json, apps/pebble/pebble.app.js, apps/pebble/pebble.settings.js
=> [Pebble Clock] Support for internationalization / Get steps from built-in step counter

apps/dtlaunch/ChangeLog, apps/dtlaunch/app-b2.js, apps/dtlaunch/metadata.json
@jeffmer
On bangle 2 change swipe directions to move between pages from **_LeftRight_** to **_UpDown_**, as to match the page indicators. Implemented like 'natural scrolling'.
Also added function **_showClock()_** which is called on **_'left-to-right' swipe_**.  Here I imagine the clock to be to the left of the launcher, if you do that then this also follows the natural scrolling principle.
=> [dtlaunch, b2] Change swipe direction to UpDown

apps/messages/ChangeLog, apps/messages/lib.js, apps/messages/metadata.json, apps/messages/settings.js
The messages app will auto-open messages (but not buzz) even when the watch is in quiet mode. This adds a setting that disables this behaviour.
=> Allow quiet mode to optionally override message auto-open

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json, apps/sched/ChangeLog, apps/sched/README.md, apps/sched/lib.js, apps/sched/metadata.json, apps/sched/sched.js, apps/sched/settings.js
_edit: This first message is obsolete_
Unlock the watch at buzz so the user can interact with the prompt immediately (it also reduces the use of the button :-D)
PS: This could be an option but I don't know where to put it:
1. in a new system setting (like the quiet mode)
2. in the Scheduler-owned settings (sched/settings.js)
3. Other?
=> [Scheduler] New functions & Settings page

apps/messages/ChangeLog, apps/messages/app.js, apps/messages/metadata.json
Currently, when a new message is delivered, the messages app starts a timeout timer that returns to the clock after a while. If the message being displayed is removed without user interaction (for instance by the user dismissing a notification on their phone), the app returns to the message list and stops the timer. The result is that if a message is received and then before the timeout is dismissed on the phone, the device will permanently display the message list until the user manually returns to the clock.
This change lets the timer keep on running as long as the user doesn't interact with the screen, restoring the clock as usual.
One possible improvement to this change (that I haven't attempted to write) could be to clear the timeout if the screen gets unlocked by the user while on …
=> Allow timeouts to run on the message list screen

apps/sched/ChangeLog, apps/sched/lib.js, apps/sched/metadata.json
Correct `decodeTime(t)` to return a more likely expected time:
- before:  
```
>require("sched").decodeTime(60*60*1000-1)
={ hrs: 0, mins: 60 }
```
- after:   
```
>require("sched").decodeTime(60*60*1000-1)
={ hrs: 1, mins: 0 }
```
=> [Sched] Correct decodeTime(t) rounding

index.html
This PR adds 3 new categories to the app loader:
Not sure about the label for "Apps Without Installations" (aka: apps with `type: RAM`) - does anyone have a better name?
---
Companion PR: https://github.com/espruino/EspruinoAppLoaderCore/pull/20
=> [AppLoader] New categories

apps/locale/ChangeLog, apps/locale/README.md, apps/locale/locale.html, apps/locale/metadata.json
This PR adds a new function `dowAll` to the `locale` module. It returns *all* the days of the week in 3 versions: long, short, first char only.
The PR also updates the `dow` function to add the _first char only_ version.
=> [locale] dow/dowAll

apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js
Orange, purple and grey seemed distinct enough to be nice additions
(Just in time for [King's Day](https://en.wikipedia.org/wiki/Koningsdag) ;-)
=> settings: Add some Bangle 1 colours to theme customizer

.gitignore, apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
1. Fix redrawing selected Alarm/Timer entry inside its edit submenu through opening the menu after a short timeout.
2. Apply redrawing fix to dow submenu, too.
3. Removing the obsolete check-mark images.
4. Removing format on boolean values to use new check-marks.
---
5. Missed to ignore the _.gitignore_ file, should I remove the entry or can it stay?
=> [alarm] Fix redrawing entry inside its submenu

apps/stopwatch/ChangeLog, apps/stopwatch/metadata.json, apps/stopwatch/stopwatch.app.js
manually start clock on button, avoids conflict with quicklaunch which
otherwise believes that a clock is running and reacts on touch events
@hughbarney Are you ok with that?
=> stopwatch: Do not register as watch

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json, apps/setting/ChangeLog, apps/setting/README.md, apps/setting/metadata.json, apps/setting/settings.js, modules/date_utils.js
_PR updated, see comments below_
~~This PR improves the UI of the default alarms app.~~
~~- Show localized abbreviations for days of week (current version always uses english abbreviations)~~
~~- An alarm on repeat Monday to Friday is labeled "repeat on workdays"~~
~~- An alarm on repeat Saturday and Sunday is labeled "repeat on weekends"~~
~~Some screenshots:~~
Any feedback/suggestions?
---
Closes #1780
=> [Alarms & Timers] Support for Monday as first day of week

apps/notanalog/ChangeLog, apps/notanalog/metadata.json, apps/notanalog/notanalog.app.js
As Bangle.getHealthStatus("day").steps is available, it is now used as fallback if no widget is installed.
=> [NotAnalog Clock] Use Bangle.getHealthStatus("day").steps as fallback if no widget is installed.

apps/bordle/ChangeLog, apps/bordle/bordle.app.js, apps/bordle/metadata.json
Update to @berkenbu's bordle app
The valid word detection did not account for the fact that a valid word
could exist twice in the list: once at a non-multiple-of-five index
because it is the end of one word and the start of another, and again at
a multiple-of-five index for the word itself. An example is aglow agony
contains wagon. This prevented wagon from being considered a valid word
(even though it could be selected as the target word).
This fix loops through all detections of the word in the dictionary to
see if any are at a multiple-of-five index.
=> [Bordle] Fix bug in valid word detection

apps/barclock/ChangeLog, apps/barclock/clock-bar.js, apps/barclock/metadata.json, modules/ClockFace.js, modules/ClockFace.md
I figured this might be a good idea.
A module which handles watchface boilerplate:
* gets rid of watchface boilerplate
* adds `Bangle.pause`/`Bangle.resume`, so widgets/boot code can do this
```js
if (Bangle.pause) { // check for support
Bangle.pause(); // now Bangle.paused = true
E.showAlert("Alert!").then(() => Bangle.resume());
}
```
* we could extend it later with global options, like powersave mode or custom widget Stuff.
```js
// Just showing off: clock one-liner 
(new (require("Clock"))(t=>g.setFont('Vector:50').drawString(require("locale").time(t,1),50,100))).start();
```
=> ClockFace module

apps/sleeplog/ChangeLog, apps/sleeplog/README.md, apps/sleeplog/lib.js, apps/sleeplog/metadata.json
Check and if neccessary reduce logsize to 1500 entries in writeLog() to prevent low mem error.
=> sleeplog: Fix LOW_MEMORY,MEMORY error #1835

apps/android/ChangeLog, apps/android/README.md, apps/android/boot.js, apps/android/metadata.json, apps/android/settings.js, apps/sched/ChangeLog, apps/sched/boot.js, apps/sched/lib.js, apps/sched/metadata.json
For the Android app, it seems better to let Sched's default alarm settings handle things like vibration, auto-snooze, and repeat for GB alarms. 
As for Sched, if a nonexistent js file is specified in an alarm's js field, the watch will be stuck on a screen which says "Loading..." until auto-snooze kicks in, and then repeats 10 mins later (or however long your AS is set to). Sched will now check to see if the js file exists - if not, it will default to sched.js. It seems to handle alarms with no js field just fine as well.
=> [Android & Sched] - small fixes and updates

modules/time_utils.js
This PR adds support for days and seconds to `time_utils`. It also improves the output of `formatDuration`.
Closes #304
=> [time_utils] Improve formatDuration with days and seconds

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json, apps/sched/ChangeLog, apps/sched/boot.js, apps/sched/lib.js, apps/sched/metadata.json
In #1822 I merged the "repeat (Y/N)" and "days" menus. Before my PR a "repeat _once_ alarm" inherited a dow = 127 (_every day_) but in my updated app I allow a free customization of the days of the week so if the user select none of them then dow = 0 and the app assumes that the alarm will fire _once_.
I didn't noticed that an alarm with dow = 0 will never fire because the filter will discard it!
This PR fixes that (I also changed the filter conditions to be in the same order so they are easier to read)
---
Anyway, could the `rp `attribute be removed? The dow alone should be enough to understand if an alarm will run multiple times (dow > 0) or once (dow = 0). What do you think?
=> [Alarms & Timers / Scheduler] Fix bug with alarms not firing when repeat is set to "once"

apps/bowserWF/metadata.json
without those entries in the metadata the app won't show as watch face
=> added tags to the metadata

apps/ffcniftya/ChangeLog, apps/ffcniftya/README.md, apps/ffcniftya/app.js, apps/ffcniftya/metadata.json, apps/ffcniftya/settings.js, apps/ffcniftyb/ChangeLog, apps/ffcniftyb/README.md, apps/ffcniftyb/app.js, apps/ffcniftyb/metadata.json, apps/ffcniftyb/settings.js, lang/it_IT.json
This PR fixes a couple of bugs in Nifty Clock A & B:
- Call setUI _before_ loading widgets (otherwise the "close widget" icon remains in the clock face)
- In Nifty Clock B there was a bug with black colour (the settings were read wrongly)
The PR also updates the clocks' Settings page.
=> [Nifty Clock A&B] Bug fix and improvements

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
I just noticed that a timer is saved with a wrong value for `dow` (254 instead of 127) if first day of week is Monday. This PR fixes the bug.
=> [Alarms & Timers] Fix dow handling for new timers

apps/r2d2clk/metadata.json
The screenshot was missing from the metadata in the app store initially, so this just adds the screenshot in so it will show up.
=> [r2d2clk] Add screenshot to metadata.json

apps/sched/ChangeLog, apps/sched/lib.js, apps/sched/metadata.json, apps/sched/sched.js, apps/sched/settings.js, modules/buzz.js, modules/buzz_menu.js
As discussed in #1873 this PR adds two new vibration patterns: `:` and `=`.
`.` now is a "short and weak" vibration and `:` is a "short and strong" vibration. Similarly `-` is "long and weak" and `=` is "long and strong" where 
- "strong" means that the Bangle.buzz() is called with strength = 1 and 
- "weak" means the function is called with strength = 0.25.
Feel free to propose some common patterns for `buzz_menu`!
Current values are  `var patterns = ["", ".", ":", "..", "::", "-", "=", "--", "==", "=.=", "---"];`
=> [buzz] Add support for new patterns

apps/calibration/ChangeLog, apps/calibration/README.md, apps/calibration/app.js, apps/calibration/boot.js, apps/calibration/metadata.json
I have tested this with two bangles and was slightly surprised by the different results:
```
{
"xoffset": 0,
"yoffset": -19.5,
"xscale": 0.90285714285,
"yscale": 1.04290429042,
"active": true,
"reload": false
}
```
```
{
"xoffset": -8,
"yoffset": -7.5,
"xscale": 0.94894894894,
"yscale": 0.95468277945,
"active": true,
"reload": false
}
```
Despite this it seems work well so far. Will test a bit longer before removing the draft marker.
=> Calibration - Scale the inputs to account for linear variation

modules/ClockFace.js, modules/ClockFace.md, modules/ClockFace_menu.js
The idea is you can specify a `settingsFile` in options, and it will be loaded directly into the clock object. (i.e. not inside a separate `settings` property, as I figured that only makes accessing settings more verbose.)
`loadWidgets` is special: it defaults to true, when `false` it prevents the call to `Bangle.loadWidgets()` (and we check if `WIDGETS` is loaded before calling `drawWidgets()`
`showDate` doesn't do anything special, but it does default to `true`
Also adds `ClockFace_menu`, although at the moment it only has two boolean menu options... Still cuts down on the boilerplate though.
=> ClockFace: add settings support

modules/time_utils.js
This PR adds a "compact mode" to `formatDuration`:
- `compact = false` &rarr; `3d 1h 10m 45s`
- `compact = true` &rarr; `3d1h10m45s`
=> [time_utils] Update formatDuration

apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js
The _Turn Off_ feels strange: it shutdowns the watch immediatly without asking the user (sometimes I turned off the watch by mistake while exploring the menus) and the last displayed screen (before the shutdown) is shown when the watch is turned on again. This feels really strange and "broken" imho.
This PR improves the "turn off" user experience:
- The user must confirm 
- A goodbye message will be shown ("_See you later!_" &rarr; other ideas?)
- The screen will be cleared
Maybe this is a trivial change but I think this is a step towards better overall usability :-)
=> [Settings] Improve "Turn Off" user experience

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
I found a bug with a disabled timer + _enable all_ action: the _enable all_ does not update the `timer` field. This PR fixes the bug :-)
=> [Alarms & Timers] Fix "Enable All"

apps/miclock2/ChangeLog, apps/miclock2/clock-mixed.js, apps/miclock2/metadata.json
For some reason a test with reversed equal comparison got committed and pushed.
=> miclock2: Fix typo in redraw check

apps/iconlaunch/app.js
Widgets can change the colors in between two drags and cause artifacts.
=> Iconlaunch - Fix colors changed during scrolling by widgets

apps/barclock/ChangeLog, apps/barclock/metadata.json, apps/barclock/settings.js, apps/cogclock/ChangeLog, apps/cogclock/metadata.json, apps/cogclock/settings.js, modules/ClockFace.md, modules/ClockFace_menu.js
As discussed [here](https://github.com/espruino/BangleApps/pull/1893#issuecomment-1147301019), instead of having separate "menu item" functions, do `require("ClockFace_menu").addItems(menu, callback, items)` instead.
And then I figured that if clocks don't have any other settings, it would be nice to get rid of the `Storage` boilerplate as well, so you can just do `require("ClockFace_menu").addSettingsFile(menu, settingsFile, ["showDate", "loadWidgets"])`
=> Clockface menu improvements

apps/sched/settings.js
This PR removes the custom boolean formatter since the new menu system handles the booleans better.
=> after 2v14 release: [Scheduler] UI improvements

modules/ClockFace.js
* Don't erase widgets when using `draw`, see discussion for [this PR](https://github.com/espruino/BangleApps/pull/1979)
* minor cleanup: remove unused argument from `tick` call
=> Clockface fixes

bin/create_apps_json.sh
Git is not good at cleaning up empty folders on changing branches. The script created corrupt json on empty app folders.
=> apploader - Ignore empty folder instead of creating invalid json

apps/stardateclock/ChangeLog, apps/stardateclock/app.js, apps/stardateclock/metadata.json
Resolves issue described in http://forum.espruino.com/conversations/377003
Fixes let/const usage for stardate clock to work properly with firmware version >=2v14
Before BJS1
Before BJS2
After BJS1
After BJS2
=> [stardateclock] Fix let/const usage

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
In my quest to hide as many widgets as I can; here is the ability to hide alarms or timers from the Alarms & Timers widget.
This feature was already available in the "sched" library & the widget, it just wasn't exposed in the menu.
So allow to change this from the menu now.
It mostly serves to hide the daily morning alarm that you might have set up.
=> [Alarms & Timers] Allow hiding timers/alarms

bin/thumbnailer.js
To avoid the error below:
```
ReferenceError: Espruino is not defined
at parseJS (eval at <anonymous> (/home/romek/Bangle/BangleApps/bin/thumbnailer.js:43:1), <anonymous>:95:5)
at eval (eval at <anonymous> (/home/romek/Bangle/BangleApps/bin/thumbnailer.js:43:1), <anonymous>:166:37)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
```
=> [thumbnailer.js] Require espruinotools as Espruino

bin/thumbnailer.js
flow app sets LCDMode to 120x120 wich will break image export (`TypeError: FUNCTION_TABLE[(HEAPU8[(($0 + 52) | 0)] | (HEAPU8[(($0 + 53) | 0)] << 8) | ((HEAPU8[(($0 + 54) | 0)] << 16) | (HEAPU8[(($0 + 55) | 0)] << 24)))] is not a function`)
Some applications use a very short timeout, which also break the export.
=> [thumbnailer.js] Output app name, reset lcd and intervals

modules/ClockFace.js, modules/ClockFace.md, modules/ClockFace_menu.js
* Makes `tick` a "ram" function, so if clocks implement their `update()` in "ram" as well, (in theory) updating the clock doesn't need to wake flash. (Based on [this forum thread](http://forum.espruino.com/conversations/375995/))
* Adds a `powerSave` menu option. (It's a boolean for now, in the future maybe also allow integer options (`["Always","During Quiet Mode", "Never"]`), but that would mean clocks need to watch for quiet mode changes.)
=> Clockface: powersaving 

apps/barclock/ChangeLog, apps/barclock/README.md, apps/barclock/clock-bar.js, apps/barclock/metadata.json, apps/barclock/settings.js, modules/ClockFace.js, modules/ClockFace.md, modules/ClockFace_menu.js
(Needs the [Clockface: powersaving](https://github.com/espruino/BangleApps/pull/2046) PR)
* Optimize drawing: second updates (the bar) happen in `"ram"`, and only redraw the changed part of the screen. (Instead of calling `layout.render()` every second)
* (Bangle.js 2 only): adds a "Power saving" option: only draws the bar while unlocked, otherwise only update once a minute.
=> Barclock powersaving

apps/noteify/README.md, apps/noteify/metadata.json
The Noteify app said it only supported Bangle.js 2, but it actually works fine on Bangle.js 1, as long as a different textinput library is used. (Although because kbmorse is the only such library for Bangle.js 1 and it's currently [broken](https://github.com/espruino/Espruino/issues/2240), it doesn't change much just yet).
=> Allow Noteify on Bangle.js 1

apps/messages/lib.js, apps/messages/widget.js
Don't keep entire messages in memory: we only need `src` for icon+color
I figured this doesn't warrant a version bump, as there aren't any functional changes
=> messages: reduce widget memory usage

tsconfig.json
In the editor I use the TypeScript language server doesn't detect the `tsconfig.json` file when it's in the `typescript` folder, meaning I have to manually open the `main.d.ts` file. Moving it to the root folder fixes that.
=> Move tsconfig.json

apps/widcw/ChangeLog, apps/widcw/metadata.json, apps/widcw/widget.js
Repeated redrawing would create multiple redraw-timeouts
(Same as https://github.com/espruino/BangleApps/pull/1713 for `widcal`)
=> widcw: fix memory leak

apps/messages/app.js
Clear `layout` when going back from message to list
Map and music already do this, just the single message view missed it.
I also considered converting `layout` from a global to local variables, but figured that leaving it global makes debugging easier.
=> messages: improve memory usage

apps/weather/ChangeLog, apps/weather/app.js, apps/weather/metadata.json
Use setWatch() instead of setUI to make middle button open the launcher, checking HWVERSION to watch the correct button.
Otherwise widgets get confused and you don't get e.g. a close button.
=> weather: don't mark app as CLOCK.

apps/agenda/ChangeLog, apps/agenda/agenda.js, apps/agenda/metadata.json, apps/agenda/settings.js
(Small feature hoping someone is actually able to use the agenda with GB)
Gadgetbridge doesn't synchronize events very frequently, unless there's a change in the calendar (new events), the update may take a day or more, depending on the connection status.
This means that before GB realizes there are old events and deletes them, we may see them in the calendar for a while.
With this update, by default the agenda won't show them. If enabled they can still be shown (grayed out). An event is considered old immediately after its finishing time, in a future update we could add a threshold for that (e.g. show events finished 1 hour ago).
=> agenda: disable past events display from settings

apps/waypoints/lib.js
The current library for waypoints includes nested backticks for format string evaluation. However, when attempting to import this library (e.g. with `require("waypoints").load()` such as in the Way Pointer app) I get the error  
`Uncaught SyntaxError: Got EOF expected ':'
at line 1 col 5
num?
^
at line 1 col 5
num?
^
in function "load" called from line 44 col 38 in waypointer.app.js
var waypoints=require("waypoints").load();`. 
This is fixed by removing the inner backticks and replacing them with string concatenation, which still appears to evaluate the format string correctly.
=> Waypoint bugfix

apps/widgps/ChangeLog, apps/widgps/README.md, apps/widgps/default.json, apps/widgps/metadata.json, apps/widgps/settings.js, apps/widgps/widget.js
Small refactor that allows the user to switch off the icons when GPS is off.
=> Add option to hide GPS widget when GPS is off

bin/apploader.js, bin/create_app_supports_field.js, bin/create_apps_json.sh, bin/firmwaremaker.js, bin/firmwaremaker_c.js, bin/pre-publish.sh, bin/sanitycheck.js, bin/thumbnailer.js, tests/Layout/bin/runalltests.sh, tests/Layout/bin/runtest.sh
It's not guaranteed that bash will be available at /bin/bash; it's even less likely that node will always be installed at /usr/bin/node{,js}. Always indirecting through /usr/bin/env means that there is only one such path that needs to be available on every system everywhere forever.
In particular, /bin/bash _is_ frequently available, but is not included in NixOS, which means I can't use the scripts unmodified for local development.
Note: `npm run update-local-apps` works for me after this, but I have not tested whether this breaks e.g. the github actions stuff.
=> Use /usr/bin/env as shebang everywhere

apps/lcars/ChangeLog, apps/lcars/lcars.app.js, apps/lcars/lcars.settings.js, apps/lcars/metadata.json
Really like this watch face, but I would find myself accidentally starting alarms when trying to touch right to go to the activity view, and occasionally also have "ghost" alarms where I didn't feel like I pressed something but must have accidentally started an alarm. This adds a simple setting for disabling the functionality without having to uninstall the Scheduler library.
=> [LCARS] Add ability to disable alarms 

bin/apploader.js
* Don't hide errors while loading `noble`:
Loading the module can also fail when e.g. compiled against a different Node.js version, don't hide those errors.
* Add `-b1` param to upload to Bangle.js 1
=> Apploader.js improvements

apps/slash/ChangeLog, apps/slash/app.js, apps/slash/metadata.json
Since slash is (wisely) very conservative about clearing / redrawing, artifacts from past dates that aren't overwritten tend to stack up. On my watch now where it says "Sun 9/18" there is some left over "T" from last Thursday sticking out to the left of the "S" in "Sun", and some leftover "6" sticking out to the right of the "8" in "18" from two days ago. This should clear everything once a day at midnight so these artifacts get cleared out.
=> [slash] If midnight clear the display to clean up artifacts

apps/messages/ChangeLog, apps/messages/README.md, apps/messages/app.js, apps/messages/lib.js, apps/messages/metadata.json, apps/messages/settings.js, apps/messages/widget.js
See http://forum.espruino.com/conversations/379866/
- Emit "message" events for incoming messages.
- Allow event handlers to prevent default app from loading.
- Add setting to hide default widget, meant for people who want to install custom widgets.
- Move `buzz()` from the widget to the library.
=> Message events

apps/kbmulti/ChangeLog, apps/kbmulti/README.md, apps/kbmulti/lib.js, apps/kbmulti/metadata.json
I switched the direction for Caps lock switching and Move cursor mode. I have two rationalizations for this. One, I feel the top-to-bottom swipe motion is more natural/pleasant to perform and should therefore be used for the more frequently used task - for me, and I suspect most users, this is to switch Caps lock. Two, since we start with upper case it makes sense to make a downward motion to get to lower case letters.
A counter argument is doing this switch might interfere with established habits. Should this be a setting in that case? If so I suggest the default to be as what I change it to with this PR.
What do you think? @sir-indy @halemmerich
=> [kbmulti] switch directions for Caps lock switch and Move cursor mode

apps/imageclock/ChangeLog, apps/imageclock/app.js, apps/imageclock/metadata.json
Clock did not refresh completely once after switching from launcher if the drawing in timeouts option in the customizer was deactivated.
=> imageclock - Fix the clock not refreshing completely after switch

apps/calendar/ChangeLog, apps/calendar/calendar.js, apps/calendar/metadata.json
The calendar jumps from 2022 to 2024 between December and January, and this seems to fix it
Signed-off-by: James Taylor <jt-git@nti.me.uk>
=> calendar - fix off-by-one-error on next year

apps/iconlaunch/ChangeLog, apps/iconlaunch/README.md, apps/iconlaunch/app.js, apps/iconlaunch/metadata.json
Since there are problems with all full screen apps it's probably better to only directly load the clock. When fastloading full screen apps widgets will draw over those without a way of recovering without restarting the app.
Discussion on ongoing development for correctly fast loading apps can be found here: [https://forum.espruino.com/conversations/379724/](https://forum.espruino.com/conversations/379724/)
=> Iconlaunch - Back to slow loading apps

apps/iconlaunch/ChangeLog, apps/iconlaunch/README.md, apps/iconlaunch/app.js, apps/iconlaunch/metadata.json, apps/iconlaunch/settings.js
Always try to fastload the clock as .bootcde now checks if it has widgets.
=> iconlaunch - Remove no longer needed fastload option

apps/iconlaunch/ChangeLog, apps/iconlaunch/app.js, apps/iconlaunch/metadata.json, apps/iconlaunch/settings.js, apps/rebble/ChangeLog, apps/rebble/metadata.json, apps/rebble/rebble.app.js
https://github.com/espruino/BangleApps/issues/2196
=> [Rebble] implemented widget_utils

apps/bthrm/ChangeLog, apps/bthrm/default.json, apps/bthrm/lib.js, apps/bthrm/metadata.json, apps/bthrm/settings.js
* Prevent mixing of internal and external HRM events
* Do not scan every 100ms if no device is found
* Run some steps of the connection process in timeouts
=> Bthrm - Stability and power use improvements

apps/boot/ChangeLog, apps/boot/bootupdate.js, apps/boot/metadata.json
These are minimal polyfills, just delegating the new calls to load(). Is this enough or should they mimic more of the new calls?
=> boot - Add polyfills for Bangle.load and Bangle.showClock

apps/torch/ChangeLog, apps/torch/app.js, apps/torch/metadata.json
Weirdly exiting with HW button behaves a little differently from using the red back button.
- Red back button: the clock and widgets are displayed at the same time when everything is ready.
- HW button: the widgets are displayed immediately, followed shortly thereafter by the clock.
Open question: should we just leave widgets shown i.e. we could do without `widget_utils` here?
=> [Torch] use Bangle.showClock

apps/quicklaunch/ChangeLog, apps/quicklaunch/boot.js, apps/quicklaunch/metadata.json, apps/quicklaunch/settings.js
This reverts commit e115cac82a7cbc055b2473997c026554c1b1e9a7.
Back to how version 0.05 worked.
This solves #2295, but does not implement any of the suggestions regarding still using Bangle.load where applicable.
=> [Quick Launch] Revert "Use Bangle.load(), remove the special 'Show launcher' entry"

README.md
It's frustrating for newcomers to try to tweak an existing app in the Web IDE and get "Module ... not found" and not know why, when this section just seem to state that any "require" should work.  The extra note clarifies this.
=> Update README.md to hint about how to require Bangle modules.

modules/widget_utils.js
This fixes `Bangle.drawWidgets` clearing the top widget bar on the global graphics object instead of the newly allocated buffer for the widgets.
=> widget_utils - Prevent initial draw clearing on global g

.gitmodules, index.html
Is this a valid way to make the locally hosted apploader usable if puck-js.com is not reachable? It did work for me, but I do not know if there are other implications of this.
=> apploader - Load puck.js locally

apps/circlesclock/ChangeLog, apps/circlesclock/app.js, apps/circlesclock/default.json, apps/circlesclock/metadata.json, apps/circlesclock/settings.js
Simple view of the closest running timer in the clock.
I cannot figure out how to properly generate the icon though, I created a 16x16 image and converted in b/w but it only works if I don't set a colour, otherwise the picture is weirdly mirrored (I bet it has something to do with the size, any hint is appreciated).
TODO:
* differentiate among alarms and timers
* _something else_?
=> [WIP] circlesclock: load circles from clkinfo

apps/android/boot.js, apps/android/settings.js
In the [Gadgedbridge PR](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2976), i add the possibility to use the gps data of the phone.
With this PR, the android app gets extended, so that it can handle the communication with the gadegtbridge part.
To enable to do that i changed the following.
* I added a handler for a "gps" and a "is_gps_active" GB message.
- The "gps" message retrieves the gps position of the phone and publishes it as a "gps" event onto the "Bangle" object.
- The "is_gps_active" messages is a request of the phone to retrieve the current power status of the gps. This is used on the phone to stop sending GPS data if the gps is turned off on the bangle device to perserve the battery of the phone.
* I added a logic to overwrite the "setGPSPower" method and the …
=> [Android] Add handling of phone gps data

apps/messagesmusic/ChangeLog, apps/messagesmusic/app.js, apps/messagesmusic/metadata.json
Fix #2321
- Fix the dependency for `messagesmusic` (whoops)
- Wrap the app code in a timeout, as otherwise it didn't work for me (no idea why).
=> Fix messagesmusic

apps/messages/README.md
It wasn't up-to-date anymore with how the library/gui now work, and still mentioned `messagelib`.
I didn't think this warrants a version bump though.
=> messages: Fix/improve README

modules/ClockFace.js, modules/ClockFace.md
It also updates `setting.json` with the correct `clockHasWidgets`, because clocks relying on `ClockFace` don't call `loadWidgets` themselves.
=> ClockFace: support Fast Loading, by adding a remove() function to clocks

apps/messagegui/ChangeLog, apps/messagegui/app.js, apps/messagegui/lib.js, apps/messagegui/metadata.json, apps/messages/ChangeLog, apps/messages/lib.js, apps/messages/metadata.json
The library combines musicinfo+musicstate messages, and waited for a "complete" message before emitting the event.
But once you are playing music you don't get new music state events. The problem was that when the first "complete" message arrives, the UI is `load()`ed, so the library forgets its state, and doesn't emit anymore music events until the play state changes.
This
- changes the library to keep combining music messages, but always emit an event
- makes the UI only launch itself if it sees a "complete" music event
- makes the UI also combine musicinfo+musicstate messages
=> messages,messagegui: fix handling of music

apps/spotrem/ChangeLog, apps/spotrem/app.js, apps/spotrem/metadata.json
When fastloading Quick Launch listeners would be removed as well - this fixes that.
=> [Remote for Spotify] remove only specific listeners

apps/spotrem/app.js
Spotted this while updating Podcast Addict Remote where I already did this.
I don't think this warrants a version bump, the change is functionally insignificant and the last pr was just merged.
=> [Remote for Spotify] remove unnecessary removeListener

apps/podadrem/app.js
No functional change - I don't think it warrants a version bump.
=> [podcast Addict Remote] shorten prepended info re intents in comment

apps/hworldclock/ChangeLog, apps/hworldclock/README.md, apps/hworldclock/app.js, apps/hworldclock/metadata.json
As in https://forum.espruino.com/conversations/382176
=> BangleJS2: Swipe down to rotate screen. So you can show the time to a friend real quick.

apps/messagegui/ChangeLog, apps/messagegui/app.js, apps/messagegui/lib.js, apps/messagegui/metadata.json, apps/messages/ChangeLog, apps/messages/lib.js, apps/messages/metadata.json
* Fast load messages without writing them to flash  
it checks `if (Bangle.load === load) // write to flash anyway` to prevent breakage on old firmwares   
Still writes to flash if we decide not to load the app
* In-app: we already saved `MESSAGES` in `E.on("kill"`, so just remove all earlier calls to `saveMessages()`
=> messagegui: don't write messages to flash quite as often

apps/sched/ChangeLog, apps/sched/boot.js, apps/sched/lib.js, apps/sched/metadata.json
Test scenario that this patch fixes:
```
E.setTimeZone(-8);
date = new Date("2022-12-05T23:00");
date.toLocalISOString(); // -> "2022-12-05T23:00:00.000-0800"
getActiveAlarms([{on: true, t: 0, dow: 0b1111111, date: "2022-12-05"}], date); //should be marked as active, but isn't
getActiveAlarms([{on: true, t: 0, dow: 0b1111111, date: "2022-12-06"}], date); //should not be marked as active, but it is because it's already "tomorrow" in UTC
```
=> sched - improve support for date timezone, toLocalISOString

modules/ClockFace.js
I don't know why this is needed, but it was definitely broken for at least `barclock`: after fast loading a messages app, it would still draw over it once.
I tried adding a bunch of logging: it *does* call `clearTimeout` with the correct ID, but somehow the timeout fires anyway.   
No idea if it's a bug in `barclock`/`ClockFace` I missed, or some subtle problem with `clearTimeout` 🙁, but at least this fixes it.
=> ClockFace: fix fast loading

apps/messagegui/ChangeLog, apps/messagegui/lib.js, apps/messagegui/metadata.json
Whoops: we didn't handle these at all, but are actually responsible for
saving them, even if the UI won't be launched.
Fixes #2380
=> messagegui: write "remove" messages to flash

apps/circlesclock/ChangeLog, apps/circlesclock/app.js, apps/circlesclock/metadata.json
Quick and dirty as my watch was crashing every time I was getting to the calendar clkinfo. In this case I guess the `addInteractive` could also populate the img field with the one from the menu item (still i think we ought to check it).
The text slicing is also preventing to draw outside the circle so that the text doesn't stay there while rotating, again this could be handled better splitting words, but I'd rather have clkinfos using the short field in this case (I'm planning to do it myself for the agenda, when I have some time).
=> circlesclock: fixed crash if item has no image and cutting long text

apps/sched/ChangeLog, apps/sched/boot.js, apps/sched/metadata.json
To reproduce the bug that this PR fixes:
```
E.setTimeZone(-5); // works if we pass timezone 0 here
setTime(new Date("2022-12-10T23:59").getTime()/1000);
console.log("seconds to midnight (expect <=60)", (86400000 - (Date.now()%86400000)) / 1000);
```
=> fix midnight recompute time in local timezone

modules/clock_info.js
Not sure if this has been discussed somewhere.
I can happen that some clock infos don't have elements (e.g. those with `dynamic` like alarms and calendar events, if the user simply doesn't have any). Swiping around in the `addInteractive` opens also those pointing to the first element (`undefined`) and crashes.
With this PR we are simply going on in the same swipe direction until we find a menu with at least an item (which is surely there as the module itself provides some items).
It looks to me more tidy than handling the case displaying an empty menu element.
=> clkinfo: repeating selection if menu is empty

apps/hworldclock/ChangeLog, apps/hworldclock/README.md, apps/hworldclock/app.js, apps/hworldclock/metadata.json, apps/hworldclock/settings.js
First, offtopic: Awesome work Gordon with the bangle! My garmin fenix 6 is sitting on my desk unused since I got the banglejs2 ! Awesome! 
Have a nice vacation!
Great work with updating this @pebl-hank ! I think in the future this setting could go in the initial pre-upload setup page, but this is my first time getting my fingers wet with the bangle and it was clear how to add it to the watch settings.
I don't want to step any boundaries with modifying someone else's watch face unless that's fine for the original author, and I can create a rworldclock, but I'd rather not. @pebl-hank ? :D 
This adds an entry in the settings menu that allows the user to show an extra single timezone small. Just like there would be more than 1 timezone. I need an extra timezone, and only one, but I do not …
=> [Hank's World Clock] Setting for single extra timezone small

loader.js
This fixes Bangle.JS Gadgetbridge from failing to load the ChangeLog with net::ERR_CLEARTEXT_NOT_PERMITTED
=> Update changelog link to https

apps/aiclock/ChangeLog, apps/aiclock/aiclock.app.js, apps/aiclock/metadata.json, apps/bwclk/ChangeLog, apps/bwclk/app.js, apps/bwclk/metadata.json, apps/linuxclock/ChangeLog, apps/linuxclock/app.js, apps/linuxclock/metadata.json
It seems that .show is not always implemented. As quick-fix I use .get() instead which works fine currently. Later on I plan using `addInteractive` -- at least for BWClock as well as AI clock this should not be a problem :)
This should also fix your report @gfwilliams:
```I can also reproduce this exact error in BW Clock without the sunrise widget - just right after starting the clock, keep tapping really quickly, and then after a few taps it stops updating.```
=> [BWClock, AIClock and LinuxClock] Fix instability by using .get() instead of .show()

.github/ISSUE_TEMPLATE/bangle-bug-report-custom-form.yaml, index.html
Add a new Textarea to enter a list of installed apps 
Adding a new button, which depends on https://github.com/espruino/EspruinoAppLoaderCore/pull/45 
If https://github.com/espruino/EspruinoAppLoaderCore/pull/45 is merged, a click on the button opens a prefilled issue on github (Bangle Version and installed apps with version).
=> [Apploader] Extend Issue Template, add Button

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json
Hi everyone i found some bugs in the handling of the gadgetbridge gps data.
**The current state**
If we retrieve the gps data from the Gadegtbridge app, we receive a JSON object with the different values. The object has a key "long" which contains the longitude gps value. The received object will then be published under the "gps" event on the global Bangle object.
**Changes in this PR**
To prevent breaking of code if you start using the gps data provided by Gadgetbridge, i adjusted the event name from "gps" to "GPS" and added a mapper to map the longitude value from "long" to "lon" so that it is similar to a gps object, which you wouuld receive if you use the normal gps chip of the banglejs device.
=> Fix mapping of Gadegtbridge GPS data and adjust event name

apps/lcars/ChangeLog, apps/lcars/README.md, apps/lcars/lcars.app.js, apps/lcars/lcars.settings.js, apps/lcars/metadata.json
I updated the clock to include 4 new colors and have the ability to disable the charts section in the settings for the app. 
dark green-556B2F
purple-FF00FF
pink-let-6C00FF
light green-99FF00
This picture showcases some of the new colors:
=> LCARS Clock 0.25-New Colors and ability to disable data charts.

apps/infoclk/metadata.json
when opened in the emulator the app gives several errors so I deleted the ability to open the app in the emulator. I also added a dependency to the weather app because without it the app does not work.
=> Informational Clock delete emulator functionality because it does not work

apps/entonclk/ChangeLog, apps/entonclk/README.md, apps/entonclk/app.js, apps/entonclk/metadata.json
For my watchface I urgently needed a timer function. In the past, I have used the built-in timer or 'a_clock_timer' from @alainsaas for this. I looked at the code for it and just unceremoniously added it to my watchface. I left the increase over the right touch. The decrease over the left touch, however, I have reduced to 1 minute. So it is also possible to give more precise information like 3, 7 or 12 minutes. Thanks for the code from @alainsaas. So it was very easy for me.
=> [entonclk] Add timer function

apps/dtlaunch/ChangeLog, apps/dtlaunch/app-b2.js, apps/dtlaunch/metadata.json
When fast loading from BW Clock to Desktop Launcher the widget field would keep the inverted theme background then quickly resetting to follow non-inverted theme. 
With this PR this is no longer the case - I have inner peace.
=> [Desktop Launcher] widget field follow correct theme immediately

apps/android/boot.js
With the [Gadgetbridge PR](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3019), the mapping of "long -> lon" will be done on the app side and therfore this guard is not needed anymore.
If you want to keep it as backward compatibility, just close this PR.
=> remove null check, since mapping is now down on app side

apps/health/ChangeLog, apps/health/boot.js, apps/health/metadata.json, apps/health/settings.js
Settings would not be saved correctly since the settings variable wasn't always passed on to setSettings. This fixes that.
EDIT: moved a LANG-tag, I think this will fix a bug where the step goal notification would say 8000 regardless of what was actually set.
=> [health] fix settings.js + boot.js

apps/messagelist/ChangeLog, apps/messagelist/app.js, apps/messagelist/metadata.json
Finally figured out why music would sometimes(well, most of the time...) revert to `<unknown>`: calling `setUI` to refresh/switch screens within the app also called `Bangle.uiRemove` every time.
Also a minor cleanup: remove the `MESSAGES!==undefined` check, as we don't handle failure anyway. (and the code that loads MESSAGES does have an error handler)
(This causes the diff to look huge, while it's actually just 4 lines+indentation changes)
=> Messagelist fix

apps/sched/ChangeLog, apps/sched/clkinfo.js, apps/sched/metadata.json
After the last modification, the text and progress bars were not updated from the clkinfo. With this PR the items are updated with a frequency that depends on how far will the timer fire.
I hope I didn't leave any dangling timeout around :)
=> sched: update clock_info to refresh periodically on active alarms/timers

apps/agpsdata/ChangeLog, apps/agpsdata/lib.js, apps/agpsdata/metadata.json
Previously GPS was left on and needed a reload to be switched off. When updating through the app this is not a problem. Automatic updates in the background while on clock however left GPS on until the next reload and caused substantial battery draw.
=> agpsdata - Switch off GPS after use

apps/berlinc/ChangeLog, apps/berlinc/berlin-clock.js, apps/berlinc/metadata.json, apps/berlinc/settings.js
This uses sliding widgets on B2 and just plain hidden widgets on B1. Also respects the appRect for compatibility with bottom widgets and dynamically changes size on showing the date.
=> Berlin Clock - Adds fullscreen mode

loader.js
Hopefully fix #2405
`sendUsageStats` is also called in case of a disconnect.
But then no apps are available anymore
=> Don't send app_stats on disconnect

apps/sched/ChangeLog, apps/sched/clkinfo.js, apps/sched/metadata.json
I saw "Uncaught Error: clearInterval(undefined) not allowed" when scheduler / alarm was set as clock info item and starting the launcher.
This fixes the crash.
=> Sched: Fix crash in clock_info

modules/graphics_utils.js
* Modifies the default value for stepAngle to allow full circle arcs without hitting the 64 vertex limit of `fillPoly`
* Fixes the use of a wrong parameter name in `radiansToDegrees`
=> Graphics utils

apps/android/boot.js
Make use of [https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3026](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3026). Will mark this as ready when that PR is merged.
=> android - Use course from GB if available

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json, apps/android/test.js
This handles connection events and switches all GPS clients over from GPS to GBGPS and viceversa.
@gfwilliams I have written some manually executed code to test the transition, is there a way to run something like that automatically?
=> android - Handle reconnects with fallback to internal GPS

apps/quicklaunch/ChangeLog, apps/quicklaunch/boot.js, apps/quicklaunch/metadata.json, modules/clock_info.js
Allows the swipe actions from the quicklaunch not to run together with actions in clkinfo, making the two work fine together.
I'm not sure this is the right way to do this (setting an attribute in the `Bangle` object), but it's the simplest way I could think of
=> quicklaunch: do not react if clkinfo is focused

apps/iconlaunch/README.md, apps/iconlaunch/app.js
This removes the copied and modified implementation of the scroller in favor of the one provided by the firmware since 2v16.
Do we have 2v16 in the wild for enough time, or should we wait for 2v17 before implementing this without a fallback for older firmwares?
=> Iconlaunch - Use firmware E.showScroller

apps/chargent/ChangeLog, apps/chargent/boot.js, apps/chargent/boot.min.js, apps/chargent/metadata.json
This configures `chargent` to work with BangleJS2 and drops the minified JS, as mentioned in the [previous PR](https://github.com/espruino/BangleApps/pull/2506)
=> chargent: support BangleJS2

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
- Display date in locale
- When switching 'repeat' from 'Workdays', 'Weekends' to 'Custom' preset Custom menu with previous selection
- Display alarm label in delete prompt
=> alarm: menu changes

apps/chargent/ChangeLog, apps/chargent/README.md, apps/chargent/boot.js, apps/chargent/metadata.json
Hi,
this changes the method so it would notify early instead of waiting for the peak to materialize. All charge curves I recorded so far show fast convergence at the peak, justifying this approach. *powermanager* does the same but relies on user supplied threshold, so I think this is not a duplicate.
=> chargent: added threshold

apps/qcenter/ChangeLog, apps/qcenter/app.js, apps/qcenter/metadata.json
This prevents loading the clock after the timeout when an app was fastloaded from qcenter.
=> qcenter - Cleanup timeout

apps/mtnclock/ChangeLog, apps/mtnclock/app.js, apps/mtnclock/metadata.json
Tested with different versions of weather.json that include or exclude the weather and time properties.
=> [mtnclock] Addressed undefined weather timestamp

apps/backswipe/ChangeLog, apps/backswipe/README.md, apps/backswipe/boot.js, apps/backswipe/metadata.json, apps/backswipe/settings.js
@Kedlub
As per:
> You can do stuff like:
> 
> ```
> (Bangle["#onswipe"] instanceof Array)&&Bangle["#onswipe"].length>1
> ```
> 
> to detect if there's >1 handler. It's not documented but honestly at this point it's unlikely to change :)
_Originally posted by @gfwilliams in https://github.com/espruino/BangleApps/issues/2524#issuecomment-1406230564_
I'll test it in just a minute.
=> [backswipe] check for existing swipe/drag handlers

typescript/types/main.d.ts
This regenerates `main.d.ts` from [`build_types.js`] in the espruino repo, after [updates to optionals and other changes].
The main changes are new modules, and some older typings that might have not been regenerated since their jsdoc/comments changed.
New module typings:
- CC3000
- ESP8266
- Flash
- NetworkJS
- Storage
- TelnetServer
- WIZnet
- Wifi
- crypto
- dgram
- fs
- heatshrink
- http
- neopixel
- net
- tensorflow
- tls
- tv
[`build_types.js`]: https://github.com/espruino/Espruino/blob/149a7f6bace3a56c1892de47bd8baacfb3f496a5/scripts/build_types.js
[updates to optionals and other changes]: https://github.com/espruino/Espruino/pull/2322
=> Regenerate typescript / main.d.ts

.github/dependabot.yml
This PR adds a dependabot config file for checking the submodules :)
According to the documentation you have to enable dependabot in the settings.
=> add dependabot config for submodules

apps/btadv/app.js, apps/btadv/app.ts, tsconfig.json
Currently we have `tsc` [generate code for es5], because we don't yet have es6 destructuring support in JSV (used [here], for example).                                            
As a follow on from #2587, this disables the TS poiyfill and points it at our `Object.assign`, so we benefit from these new features, while still keeping the target at es5. 
[generate code for es5]: https://github.com/espruino/BangleApps/blob/380af9c600121f50b940b83cdb83a5f83914b8a6/tsconfig.json#L4-L4                                                  
[here]: https://github.com/espruino/BangleApps/blob/380af9c600121f50b940b83cdb83a5f83914b8a6/apps/btadv/app.ts#L235
=> btadv: manually setup TS helpers - use Object.assign()

typescript/types/clock_info.d.ts
Clock info can remember the app a clock info was associated with this - now tracked in typescript
=> `clock_info.d.ts` `.app` addition

typescript/types/main.d.ts
This brings in `fromEntries` and `getOwnPropertyDescriptors`, and the `call`/`apply`/`bind` `thisArg` changes from espruino/Espruino#2334
=> Regenerate `main.d.ts`

apps/notanalog/ChangeLog, apps/notanalog/metadata.json, apps/notanalog/notanalog.app.js
Quick update to the Not Analog clock to respect the system time format setting for 12h time. Utilizing the ClockFace module is probably a better solution, but a much bigger lift than this quick fix :shrug: 
@peerdavid
=> [Not Analog] Respect system time format setting

apps/weather/ChangeLog, apps/weather/clkinfo.js, apps/weather/lib.js, apps/weather/metadata.json
The `drawIcon` function used to draw the weather icon directly on the screen, long ago I changed it to optionally draw on a supplied Graphic object to be able to transform it in an image.
As the mechanism was used just by the `clkinfo` (which needs monochromatic images), the function was always using a single colour palette in case a Graphic object was supplied.
With this (small) update, calling this function without the monochrome parameter set to true will still draw a coloured icon even on the supplied Graphic object, as needed by apps like weatherClock (#2617).
=> weather: added monochrome parameter to `drawIcon`

apps/altimeter/ChangeLog, apps/altimeter/app.js, apps/altimeter/metadata.json
Add display of sea-level pressure and temperature, and allow calibration by setting the altitude. That way, you can get precise altitude if you already know sea-level pressure (from example from forecast), or you can calibrate using known altitude and have precise readings for a while.
=> altimeter: Display sea-level pressure, too, and allow calibration

apps/clockcal/ChangeLog, apps/clockcal/metadata.json, apps/clockcal/settings.js
fixed typo in settings.js for DRAGDOWN that did cause the setting to not be saved correctly and hence wasn't settable
=> [clockcal] fixed typo in settings.js for DRAGDOWN

apps/alarm/app.js, apps/btadv/app.ts, tsconfig.json, typescript/types/locale.d.ts, typescript/types/modules.d.ts, typescript/types/sched.d.ts
I'd like to eventually make this opt-in, so if a user wants to, they can check JS files by popping a little `"apps/myapp/*.js"` into `tsconfig.json`. Currently this doesn't pick up any of the typescript bindings - something I'd like to address.
=> Add typings for `sched`, `locale` and expose via `require`

apps/widdevst/ChangeLog, apps/widdevst/metadata.json, apps/widdevst/wid.js
Hi,
this version adds GC because memory usage would otherwise grow continuously, albeit slow. For instance, function definitions inside function calls create reference cycles that prevent objects from being freed immediately. Reporting memory usage without GC is therefore misleading.
https://notevil.github.io/BangleApps/?q=widdevst
It still reports current memory usage every 2s because quickly increasing memory usage is an indicator for app/system (design) issues. If you disagree, please let me know.
Additionally, storage usage is updated less frequently, and element positioning is slightly improved.
=> widdevst v0.03

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
The alarm app menu was "crashing" when trying to create a new alarm that didn't yet have a message. This seems to fix that issue.
=> Fix a menu crash in alarms app

apps/sleeplog/ChangeLog, apps/sleeplog/README.md, apps/sleeplog/boot.js, apps/sleeplog/interface.html, apps/sleeplog/lib.js, apps/sleeplog/metadata.json
to 0.13:
- Prevent to stay in consecutive sleep if not worn.
- Correct calling triggers where last time is earlier then first time.
- Add the trigger object itself as argument to the fn function to be able to store data or functions inside the trigger object.
to 0.14:
improvements initiated by #2677
- Add a option to delete all logfiles before a specific date from the watch
- Correct regex file search from `\d\d\d\d` / `\d{4}` to `\d+`
=> [sleeplog] Improving triggers and web interface

apps/btadv/app.js, apps/clkinfostopw/ChangeLog, apps/clkinfostopw/clkinfo.js, apps/clkinfostopw/clkinfo.ts, apps/clkinfostopw/metadata.json, apps/clkinfostopw/settings.js, apps/clkinfostopw/settings.ts, apps/widChargingStatus/widget.js, apps/widbtstates/widget.js, tsconfig.json
Several improvements to the stopwatch clockinfo, inspired by #2692 and #2686:
- Format option added, to reduce space used (see [forum thread on various clocks](https://forum.espruino.com/conversations/384497/))
- Reduced interval to 1s, no point redrawing the same thing 10x per second
- Don't queue the redraw when shown, if we're paused
- This was a large drain on the battery, shown in the [`powermanager`](https://github.com/espruino/BangleApps/tree/master/apps/powermanager) app (`this.emit(...)`)
=> Improvements to the stopwatch clockinfo

apps/clkinfostopw/clkinfo.ts, apps/clkinfostopw/settings.ts, apps/drained/app.js, apps/drained/boot.js, apps/drained/settings.js, apps/drained/settings.ts, typescript/types/funcs.d.ts, typescript/types/main.d.ts
Including using typescript's [`satisfies` feature](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator) to avoid having to manually type settings or clockinfo functions.
=> Update typescript & remove "use strict"s

index.html
This moves the minify option to an expandable advanced section, and changes the warning ("may" -> "will"). See #2562 for more details.
Deployed to my [gh pages](https://bobrippling.github.io/BangleApps/) if you want a preview.
=> Move minify setting into expandable area, and warn

apps/wid_edit/ChangeLog, apps/wid_edit/metadata.json, apps/wid_edit/settings.js, apps/widalarmeta/ChangeLog, apps/widalarmeta/metadata.json, apps/widalarmeta/widget.js, apps/widbatpc/ChangeLog, apps/widbatpc/metadata.json, apps/widbatpc/widget.js, apps/widmessages/ChangeLog, apps/widmessages/metadata.json, apps/widmessages/widget.js
When attempting to edit a widget whose `draw` function takes the widget as an argument, we get an exception from that `draw` function. This fixes that by catering for both APIs.
The back button widget expects this, as does [`widsleepstatus`], [`widlock`] and [`widlockunlock`].
However, there are other widgets ([`widmessages`], [`widbatpc`] and [`widalarmeta`]) which use something else for the first parameter. So I'm thinking we change the behaviour of the first three (to use `this` instead of an argument, and revert this `wid_edit` change), but we'd also need to change the back widget - but I'm not sure where this comes from.
Before I dig into that, does this sound like a good approach?
[`widsleepstatus`]: https://github.com/espruino/BangleApps/blob/2f6862024d6b92a11fd05a5183a1dd9a53dc5e48 …
=> Fix `wid_edit`'s `draw()` - pass `WIDGET` as first argument

apps/powermanager/interface.html
@halemmerich if you're happy with this, I'd like to add a small tweak to powermanager's `interface.html`, to show the durations in minutes / hours / days.
[Deployed here](https://bobrippling.github.io/BangleApps/?q=powermanager) if you want to check it out.
For example:
=> powermanager: format seconds into days/hours/minutes/seconds

apps/powermanager/ChangeLog, apps/ratchet_launch/ChangeLog, apps/ratchet_launch/metadata.json
I had a file open from another branch and accidentally changed its version for #2719, not ratchet launcher's.
=> Fix `d888b80ea` - correctly bump ratchet launcher's version

apps/stlap/ChangeLog, apps/stlap/app.js, apps/stlap/metadata.json
@bruceblore I've made a little tweak to `stlap`, so we drop the redraw interval to a second, unless the user's looking at, or interacting with the watch, what do you think?
=> stlap - reduce battery consumption

apps/widhid/ChangeLog, apps/widhid/README.md, apps/widhid/metadata.json, apps/widhid/wid.js, apps/widhid/wid.ts
Particularly in menus, the widget's swipe handler would activate, preventing the menu from working. Tested now with a launcher active, on a clock, on a menu and on a few apps.
=> widhid: avoid clashing with other swipe/drag handlers

apps/widhid/ChangeLog, apps/widhid/metadata.json, apps/widhid/wid.js, apps/widhid/wid.ts, typescript/types/bangle_extensions.d.ts, typescript/types/main.d.ts
- `sendHIDReport` sometimes errors if it can't send a HID - we now handle this to stop it bailing out the whole event handler chain.
- We also now handle the special case of `Bangle["#ondrag"]` being a function, catching this error with typings
- This also updates `main.d.ts` from the espruino repo (for `E.stopEventPropagation()`)
=> Fix `widhid`'s HID sending errors and handling of #ondrag

apps/hasensors/ChangeLog, apps/hasensors/boot.js, apps/hasensors/custom.html, apps/hasensors/lib.js, apps/hasensors/metadata.json
* Instead of uploading a separate config file, adjust the code directly during customization.   
* Add icons depending on level+state: Home Assistant already uses a level-dependent icon, but doesn't know the sensors belong together, so doesn't add a charging indicator.
* Cleanup: use double quotes everywhere, instead of randomly mixed `'` and `"`
=> [Home Assistant Sensors] inline config, add icons, quotes unification

apps/stlapview/ChangeLog, apps/stlapview/app.js, apps/stlapview/metadata.json
This fixes referencing a variable that's not in scope for `stlapview`, letting the user go back from a lap view.
It also removes the `eval` previously mentioned in a comment, and adds a back button to the main menu - @bruceblore hope these are ok, happy to revert them or change if you'd prefer
=> Small stlapview menu fixes

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json, apps/android/test.js
I had a go at using the GPS events from GadgetBridge as soon as they arrive. This removes the need to handle connection events and fixes GPS not working if for some reason (e.g. config) GadgetBridge never sends an GPS event or stops sending them.
=> android - Handle GPS events from Gadgetbridge instead of connection events

apps/lightswitch/ChangeLog, apps/lightswitch/metadata.json, apps/lightswitch/widget.js
I've tried to use the same kind of logic present for the drag event. 
Don't know if it would be better to do some refactor to use the new `E.stopEventPropagation()` function?
Edit:
And to add, I don't really understand why this works, but from testing it it seems to at least.
Can be tested on my app loader: https://thyttan.github.io/BangleApps/?q=lightswitch
=> [Light Switch Widget] handle and intercept swipe event

apps/locale/locale.html
After a factory reset the bangle.js 12 hour mode does not have a leading zero in front of the hour. After updating the locale using languages from the app loader it will always have a leading zero in front of the hour. This fixes that and ensures 24 hour mode still has a leading zero.
=> Update locale.html to remove leading zero in 12 hour mode

apps/notify/ChangeLog, apps/notify/metadata.json, apps/notify/notify_bjs1.js, apps/notify/notify_bjs2.js
This permits `0x0` as a `titleBgColor` for notifications, and sets the notification's default title bg-colour depending on the user's theme.
Previously, a dark theme would display the below notification on a bangle2:
Which is readable here, but on a real device, looks like this:
This tweaks the background colour for the dark theme to almost-black, making the notification easier to read.
=> notify: improve title bg colour for dark theme

apps/bootgatthrm/ChangeLog, apps/bootgatthrm/boot.js, apps/bootgatthrm/metadata.json
This pull request includes two key changes to enhance the functionality of the BangleJs HRM device and improve compatibility with the OpenTracks app.
- added BLE sensor location (0x2a38) with value "wrist":
In this update, I have added the BLE sensor location characteristic with the value "wrist" (0x2a38). This addition provides important information about the placement of the HRM device on the user's body, specifically on the wrist. This information can be utilized by apps and services to accurately identify and interpret the sensor data from the BangleJs HRM device.
- Tuned HRM service advertisement settings for OpenTracks compatibility:
To ensure that the BangleJs HRM device is discoverable and recognized by the OpenTracks app, I have made specific adjustments to the HRM service …
=> [bootgatthrm] Added BLE sensor location and tuned HRM service advertisement settings

apps/sensortools/ChangeLog, apps/sensortools/README.md, apps/sensortools/default.json, apps/sensortools/lib.js, apps/sensortools/metadata.json, apps/sensortools/settings.js, apps/sensortools/square.gpx, apps/sensortools/squareFuzzy.gpx
This changes the interpolation to get a speed of roundabout 20km/h instead of hundreds and calculates useful course changes during interpolation. README has improved formatting and gpx files of the simulated routes.
=> Sensortools - Fix GPS interpolation

apps/btadv/app.ts, apps/clkinfostopw/clkinfo.ts, apps/clkinfostopw/settings.ts, apps/drained/app.ts, apps/folderlaunch/ChangeLog, apps/folderlaunch/app.ts, apps/folderlaunch/configLoad.js, apps/folderlaunch/configLoad.ts, apps/folderlaunch/metadata.json, apps/folderlaunch/settings.ts, apps/folderlaunch/types.d.ts, apps/popconlaunch/ChangeLog, apps/popconlaunch/boot.js, apps/popconlaunch/boot.ts, apps/popconlaunch/metadata.json, apps/popconlaunch/settings.ts, apps/widhid/wid.ts, typescript/types/main.d.ts
This change alters a few things typescript-related, but the actual JS changes come down to two apps - popcon and folderlaunch (hence only those having version bumps).
In summary:
- `main.d.ts` has been regenerated from the espruino repo
- Typescript apps which use `storage.readJSON()` now must declare the type they expect for the JSON, and also must handle `undefined`, in the `noExceptions` case (to avoid a crash)
- It's now harder for typescript apps to mix up `setTimeout` and `setInterval` ids
- popcon's `readJSON` override now handles the case where we get back `undefined`
=> Catch additional errors from readJSON (via typescript)

apps/wrkmem/ChangeLog, apps/wrkmem/app.js, apps/wrkmem/metadata.json
This reverts commit f947105677ea2bcdece8317bfdbaee6fae0d9a0e. 
I didn't realize this wouldn't be fixed until 2v19 was available, which isn't quite yet! Adding the workaround back in until 2v19 is out.
=> Revert "remove workaround fixed by a0e2d92"

apps/folderlaunch/ChangeLog, apps/folderlaunch/README.md, apps/folderlaunch/app.js, apps/folderlaunch/app.ts, apps/folderlaunch/configLoad.js, apps/folderlaunch/configLoad.ts, apps/folderlaunch/metadata.json, apps/folderlaunch/settings.js, apps/folderlaunch/settings.ts, apps/folderlaunch/types.d.ts
This PR adds a new option in the settings menu of Folder Launcher to disable vibrations in the launcher. Some users (myself included) might find the vibrations annoying so it would be nice to have an option to disable it. 
I wasn't sure whether to open this PR against the official repo or the app's fork so @bruceblore if you would rather have me open this PR against your repo instead I can do that too. 
Thank you!
=> [folderlaunch] Add setting to disable vibration

apps/boxclk/ChangeLog, apps/boxclk/app.js, apps/boxclk/metadata.json
Improves responsiveness of background apps that also use the touchscreen (such as Pattern Launcher) by only using the drag handler if a box is actively selected.
=> [boxclk] - v0.04 Update

apps/mylocation/ChangeLog, apps/mylocation/README.md, apps/mylocation/metadata.json, apps/mylocation/settings.js
Notify @hughbarney 
Added dependency for waypoint. I could change that to "only show menu if waypoint is installed".
=> mylocation: Add option to set location from waypoint

apps/boxclk/ChangeLog, apps/boxclk/app.js, apps/boxclk/metadata.json
Use `Bangle.getHealthStatus("day").steps)` instead of `Bangle.getStepCount())`
=> [boxclk] - Update v0.05: Fix step count not resetting

apps/podadrem/ChangeLog, apps/podadrem/app.js, apps/podadrem/metadata.json
...instead of twice like we did before. It should not be needed now we issue a newline before GB commands.
=> podadrem: Send GB wake command only once

apps/spotrem/ChangeLog, apps/spotrem/app.js, apps/spotrem/metadata.json
...instead of twice like we did before. It should not be needed now we issue a newline before GB commands.
=> spotrem: Send GB wake command only once

apps/chimer/ChangeLog, apps/chimer/metadata.json, apps/chimer/widget.js
A small fix to #2799, we now sleep between buzzes instead of kicking off a buzz and instantly sleeping
=> chimer: sleep between buzzes, instead of during

apps/fastload/ChangeLog, apps/fastload/README.md, apps/fastload/boot.js, apps/fastload/metadata.json, apps/fastload/settings.js
WIP
@halemmerich 
The app history is used to navigate back to previous apps when going back from the current app.
To do before converting PR from draft:
Can be loaded here in the meantime: https://thyttan.github.io/BangleApps/?q=fastload
Should this be a separate new app, does the added code contribute too much to loading times? (Not in my experience so far. No timings done)
=> [Fastload Utils] Add app history functionality

apps/agenda/ChangeLog, apps/agenda/agenda.js, apps/agenda/metadata.json
The way we were comparing the date for Today and Yesterday was to compute the ISOstring, extract the date and compare that with today's. Such date is however in UTC and allDay events start at midnight, which makes them belong to the previous day on half of the time zones (the same problem could appear on other events earlier than the time zone's offset).
With this PR we compare day and month, which is safer as it should take into consideration also  time zones.
Fixes: https://github.com/espruino/BangleApps/issues/2856
=> agenda: Fixed "Today" and "Yesterday" wrongly displayed for allDay events on some time zones

apps/openstmap/ChangeLog, apps/openstmap/app.js, apps/openstmap/metadata.json, apps/openstmap/openstmap.js
As discussed in #2844
Also disables the internal widget if widgps is installed. Kind of troubled me seeing two GPS widgets.
=> openstmap: Remember latitude, longitude & scale

apps/swiperclocklaunch/ChangeLog, apps/swiperclocklaunch/boot.js, apps/swiperclocklaunch/metadata.json
=> swiperclocklaunch: check `mode` after pulling from `options`

apps/batchart/ChangeLog, apps/batchart/metadata.json, apps/batchart/widget.js
@msdeibel if this is ok with you, I've a small tweak to keep the IDE console free of logs
=> batchart: remove log

apps/messagesoverlay/ChangeLog, apps/messagesoverlay/boot.js, apps/messagesoverlay/lib.js, apps/messagesoverlay/metadata.json
This uses the `messages` events instead of overloading the require function to get the messages.
=> messagesoverlay - Use event based mechanism

apps/gpstrek/convert.xsl, apps/gpstrek/interface.html
No version bump since no code changes for the Bangle side of things. Fixes #2854
=> Gpstrek - Handle GPX 1.0 in interface.html

apps/multitimer/ChangeLog, apps/multitimer/app.js, apps/multitimer/metadata.json
A small bugfix leftover from #2781 - the previous PR changed how hardmode worked, but didn't update how new alarms/timers were created.
=> multitimer: fix hardmode in new alarms/timers

README.md
Fix typo in the git submodule init command - `git submodule --init` is not valid.
=> Fix git submodule init command

apps/messagesoverlay/ChangeLog, apps/messagesoverlay/lib.js, apps/messagesoverlay/metadata.json
Fixes #2878 by not switching on the backlight for every lock event.
=> messagesoverlay - Fix overlay keeping the LCD on

apps/multitimer/ChangeLog, apps/multitimer/app.js, apps/multitimer/metadata.json
I find I regularly want to set timers/alarms, and this speeds up that interaction.
There is a 1-byte memory leak however - have we seen this kind of pattern before?
```javascript
>Bangle.loadWidgets()
=undefined
>Bangle.drawWidgets()
=undefined
>process.memory().usage
=3540                       // base
>eval(require("Storage").read("multitimer.app.js"))
=undefined
>process.memory().usage
=4023                       // initial app load
>Bangle.setUI()
=undefined
>process.memory().usage
=3800                       // app loads modules, memory remains bumped
>eval(require("Storage").read("multitimer.app.js"))
=undefined
>process.memory().usage
=4024                       // second app load - 1 byte more in use
>Bangle.setUI()
=undefined
>process.memory().usage
=3801                       // …
```
=> multitimer: fastload

apps/messagesoverlay/ChangeLog, apps/messagesoverlay/lib.js, apps/messagesoverlay/metadata.json
The lock handler had kept a reference to the first created overlay buffer, which caused the first message to be shown again on unlock (and used memory). Additionally the switch from normal to low memory mode did not work correctly because the buffer was not recreated with 1 bit depth.
=> Messagesoverlay - Fix low memory handling when overlay already visible

apps/openstmap/ChangeLog, apps/openstmap/app.js, apps/openstmap/metadata.json
Bugfix: In the last PR I forgot to power the compass. I have a script that powers on the compass in the background which is why I had no issue when testing. Just remembered that.
Sorry for the noise.
=> openstmap: Enable Compass if needed

android.html, index.html
Make apps installable even with the same version number as an advanced option. This is helpful during development where the version is not always updated for every change. Needs https://github.com/espruino/EspruinoAppLoaderCore/pull/51 ;
=> apploader - Additional option to allow updates regardless of version

typescript/types/layout.d.ts
A minor tweak to `layout.d.ts` from some local development to permit "real" usage
=> layout.d.ts: render() takes a RenderedHierarchy (x/y/w/h)

apps/timerclk/ChangeLog, apps/timerclk/app.js, apps/timerclk/lib.js, apps/timerclk/metadata.json
On my Bangle 2 I noticed that the existing Timer Clock app seems to be unusually fickle with registering swipes to switch to the various screens compared to other apps, sometimes requiring me several attempted swipes to get to the desired mode. So I took a look at the code and managed to make a couple of small changes that make it a lot more reliable.
The first change significantly increases the sensitivity (that is, decreases the minimum swipe length) required to activate the switch to timer, stopwatch, or alarm modes. Since the main screen only cares about left vs. right swipes, decreasing the length to just 5 from 50 works well, as the Bangle 2 touchscreen already seems to have a fair bit of hysteresis in movement before registering a drag to begin with.
The other change fixes a coding …
=> timerclk: Improve swipe responsiveness on main clock screen

apps/fastload/ChangeLog, apps/fastload/boot.js, apps/fastload/metadata.json
broken since e2ba3ca64 (fastload - Replace E.CRC32 with Storage.hash, 2023-07-24)
Storage.hash() expects a regex (or apparently the name as a string) to match files that should be hashed, but was called with the contents of the file
=> fastload: fix caching

apps/multitimer/ChangeLog, apps/multitimer/app.js, apps/multitimer/metadata.json
This fixes multitimer's fastload support, from #2879
=> multitimer: ensure onDrag is registered after all E.showXYZ calls

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
This fixes a bug I discovered in the Alarms app. When editing an event, any changes to the date do not get saved to the alarm if the user taps Confirm on the menu… only when pressing back. This is because the code for saving the alarm when tapping back did not match the code for the Confirm menu button; the latter only saved the time and not the date.
This patch adjusts the two pieces of code to match each other. Probably an even better idea would be to wrap this “save and quit” code into a small function and reference it by name in both the back and Confirm button entries rather than copy/paste the code. This would ensure that both actions in the UI cannot accidentally diverge and cause bugs like this.
=> Alarm: Fix date not getting saved when tapping Confirm in event menu

apps/widanclk/ChangeLog, apps/widanclk/metadata.json, apps/widanclk/widget.js
Currently adds the days date behind the clock hands in the `g.theme.bgH` color.
Should this:
- just be added like this, always on?
- be configurable via settings?
- be a new separate widget?
=> widanclk: add todays date behind clock hands.

apps/dragboard/ChangeLog, apps/dragboard/lib.js, apps/dragboard/metadata.json
Reference https://github.com/espruino/BangleApps/issues/2910.
This should work, does in the testing I've done on fw 2v18.115. Also on older firmwares if I did things correctly (not tested).
=> dragboard: Compat w backswipe on newer firmwares

apps/openstmap/ChangeLog, apps/openstmap/README.md, apps/openstmap/app.js, apps/openstmap/metadata.json
By simply clicking on screen instead of going to menu to zoom in/out, navigation can be much quicker.
=> Allow zooming map in/out by clicking.

apps/draguboard/lib.js
Reference https://github.com/espruino/BangleApps/pull/2934 and https://github.com/espruino/BangleApps/pull/2936.
I don't think it warrants a version bump.
=> draguboard: remove arguments from `catchSwipe`

apps/chargerot/ChangeLog, apps/chargerot/boot.js, apps/chargerot/metadata.json
A small tweak to `chargerot` to avoid exceptions on boot
=> chargerot: handle missing settings (e.g. first install)

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json
Allow alarms to be enabled or disabled from Gadgetbridge, without deleting them from the watch.
Needs https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3240, but stays backwards compatible.
=> android: Allow alarm enable/disable

apps/lcdclock/ChangeLog, apps/lcdclock/app.js, apps/lcdclock/metadata.json
This just rearranges code to match the behaviour of other clocks, meaning any dependencies between widgets and clock info is consistent
See also #2900 / [this comment](https://github.com/espruino/BangleApps/pull/2900#issuecomment-1663510899)
=> lcdclock: load clockinfo before widgets

apps/bootgattbat/ChangeLog, apps/bootgattbat/boot.js, apps/bootgattbat/metadata.json, apps/bthometemp/ChangeLog, apps/bthometemp/app.js, apps/bthometemp/metadata.json
Following on from #2912, this handles `Bangle.bleAdvert` being an array instead of an object
=> bootgattbat & bthometemp: handle bleAdvert array

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json, apps/gbridge/PROTOCOL.md, apps/gbridge/widget.js, apps/health/ChangeLog, apps/health/lib.js, apps/health/metadata.json
Add a simple API for ativify fetching from Gadgetbridge. The API receives the start timestamp, and returns activity up until the current timestamp.
PR on Gadgetbridge: https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3212
Not incredibly happy with the code, but I am trying to avoid iterating through entire months needlessly, since sync might happen periodically.
Still very much a WIP.
Fixes #718
=> Implement API for activity fetching

apps/bikespeedo/ChangeLog, apps/bikespeedo/app.js, apps/bikespeedo/metadata.json
Fixes #2961 - the original code needed exactly a number, not a boolean
=> bikespeedo: fix locale units setting

apps/recorder/interface.html
According to https://developers.google.com/kml/documentation/kmlreference#kml-extension-namespace-and-the-gx-prefix
> This namespace URI must be added to the <kml> element in any KML file using gx-prefixed elements
As the exported kml tracks always contain such elements, add the namespace.
=> Add missing gx namespace for kml extensions

apps/hwid_a_battery_widget/ChangeLog, apps/hwid_a_battery_widget/metadata.json, apps/hwid_a_battery_widget/widget.js
In some cases, if another app/widget changes the background color, hwid_a_battery_widget is drawn incorrectly.
=> Fix hwid_a_battery_widget background color

apps/boot/ChangeLog, apps/boot/bootupdate.js, apps/boot/metadata.json, apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js
This uses NRF.resolveAddress() on newer firmwares, to try to resolve "random private resolvable addresses" of peers that connect, before checking the whitelist.
Now we can finally whitelist smartphones that change their address :)
=> boot, setting: whitelist: try to resolve peer address

apps/health/ChangeLog, apps/health/app.js, apps/health/metadata.json
This just fixes a typo introduced by commit 31fb8f8d02 which causes the movement daily summary graph to freeze on the “Loading…” screen and print an error to the console due to trying to access the field name “hr” when it should be “day”.
While I was at it, I noticed what I thought might have been a potential out-of-bounds subscripting error in the *PerDay() functions. The array size is 31 (indeces 0…30) but the indeces actually returned by readDailySummaries are 1…31. However, it appears that the graph never displays a partial day's data before it rolls over, so maybe this would never be a problem because presumably the 31st day of the month would not display? It's technically inconsistent with the fact that the hourly funcs dimension the array to 24 rather than 23, though, but since I'm …
=> Fix health daily movement graph again :-)

apps/messagelist/ChangeLog, apps/messagelist/app.js, apps/messagelist/metadata.json
`new Layout(...)` [calls `Bangle.setUI()`](https://github.com/espruino/BangleApps/blob/master/modules/Layout.js#L81), causing `uiRemove()` to be called whenever a new messages arrives, instead of only when the app exits.
This fixes that by unsetting `Bangle.uiRemove` before calling `Layout`, and restoring it afterwards.
Also: add some `debug()` lines, enabled by setting `global.DEBUG_MESSAGELIST = true`
(Proper fix instead of https://github.com/espruino/BangleApps/pull/2975)
=> Messagelist setUI proper fix

apps/messages/ChangeLog, apps/messages/lib.js, apps/messages/metadata.json, apps/messages/settings.js
This adds a second Repeat option for phone calls. I like having a single buzz for messages (sms/emails/etc.), but a continuing repeated buzzing for phone calls.
This seemed like a nice easy/small tweak, but let me know if there's anything that needs to change!
=> Add repeatCalls option

apps/lightswitch/ChangeLog, apps/lightswitch/lib.js, apps/lightswitch/metadata.json
This ensures we always have a widget object (not `undefined`), even if the widget hasn't loaded.
Fixes #2985
=> lightswitch: fix tap listener widget assumption

apps/gipy/README.md
@wagnerf42 coincidentally I used gipy the other morning - great app! This PR fixes the links in the readme (no need for a version bump since there's no code changes)
Closes #3010
=> gipy: fix links and trim whitespace

apps/widbat/ChangeLog, apps/widbat/metadata.json, apps/widbat/widget.js
Green fork is not easily visible, which can be confusing.
=> widbat: Use flash, not fork to indicate charging

apps/pomoplus/ChangeLog, apps/pomoplus/app.js, apps/pomoplus/common.js, apps/pomoplus/metadata.json, apps/pomoplus/settings.js
see https://notevil.github.io/BangleApps/?q=pomoplus
- adds setting "Show clock"
If set, returns to clock (`Bangle.showClock()`) after start/resume.
- minor changes
- (changed*) buzz pattern of long break
- added `g.clear()` and adjusted `.clearRect` in `drawTimerAndMessage`
- replaced `g.getWidth()` and `g.getHeight()` with `w` and `h`
@bruceblore is this in conflict with your vision for this app?
*nothing changed since atm the last buzz immediately follows the second one
=> pomoplus: new setting and minor changes

apps/backswipe/ChangeLog, apps/backswipe/boot.js, apps/backswipe/metadata.json
`undefined` handlers are created when we [remove listeners] part-way through the array. This fixes `backswipe` for all firmwares, but leaves the door open for a potential firmware change.
See also https://github.com/espruino/BangleApps/issues/2953#issuecomment-1747428051
[remove listeners]: https://github.com/bobrippling/Espruino/blob/0f16231a4369bb2d154b9fab5a0d806122cddb39/src/jswrap_object.c#L1035-L1035
=> backswipe: ignore `undefined` handlers

apps/hrrawexp/ChangeLog, apps/hrrawexp/README.md, apps/hrrawexp/app.js, apps/hrrawexp/metadata.json
Updated to work with new API. Additional capability includes:
1. Now also records upto 2 hours - if you cancel at any time the CSV file will still be there, the timer you set at the start is more so that you get an alert when it's complete.
2. Along with raw PPG readings, it also records bandpassed filtered data in a second column, available in the new API.
3. Rather than overwriting 1 data file, the app will record upto 5 files before recording to a generic data file as a fallback if all 5 allocated files remain on the watch storage. The limit is in place to avoid going over storage limits as these files can get large over time.
=> Updared to HRM recorder app

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
auto expiration for events:
- Set default value
- Add "delete after expiration" checkbox to events.
repeat menu: Do not change value on back (fixes #2930)
Instead of saving repeat argument as originalRepeat create a new changed repeatObj
=> alarm auto expiration for events + fix repeat back

modules/Slider.js, modules/Slider.md
WIP
[Companion PR to Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3241).
This is meant to become a flexible and as lightweight/performant implementation of ui with input sliders as I can manage.
https://thyttan.github.io/BangleApps/apps/slidertest/screenshot-1.png
To try it out:
1. Install [updated Android Integration](https://thyttan.github.io/BangleApps/?q=android) to be able to send new `vg` command (vg = Volume Get level).
2. Install [the test app](https://thyttan.github.io/BangleApps/?q=slidertest)
3. Start the app named "Slider test" from your watch's launcher.
4. Optionally install and try [this modified "Remote for Spotify"](https://thyttan.github.io/BangleApps/?q=spotrem) to see the library used in a proper app.
5. Build Gadgetbridge from source with …
=> [Slider] New library for input via sliders

apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js
...and stop event propagation.
Closes https://github.com/espruino/BangleApps/issues/2188
I thought about intercepting drag events as well. But didn't bother. Can add it if wanted.
=> setting: Prepend 'LCD->Calibration' touch listener

apps/scicalc/ChangeLog, apps/scicalc/README.md, apps/scicalc/app.js, apps/scicalc/metadata.json
Swiping up has now the same effect as hitting the "<" button.
@berkenbu Hope this is ok with you. I find it easier to correct typos that quickly appear with a single swipe instead of navigating to the correct screen first.
=> scicalc: Add swipe up action

apps/pebbled/ChangeLog, apps/pebbled/metadata.json, apps/pebbled/pebbled.app.js
This ensures `pebbled` continues to draw - similar changes could be made to `pebble` and `pebblepp`, but the former has had no bugs reported and the latter's code is simple enough that it doesn't appear likely to raise exceptions when drawing.
The issue is likely an exception in `pebbled`'s drawing code, but this solves the watch redraw problem while we wait to hear about possible debug logs.
Closes #3043.
=> pebbled: prevent exceptions halting the draw cycle

apps/calclock/ChangeLog, apps/calclock/calclock.js, apps/calclock/metadata.json
The main reason why I developed CalClock is for me to not make sure I don't forget any upcoming events I have in my calendar.
So I added a subtle buzzing that notifies me of upcoming events.
TODO: In future I want to put this into the boot code, as then I could always be reminded of upcoming events, even if I have any other app open.
=> CalClock: Add buzzing before events

apps/sunrise/ChangeLog, apps/sunrise/app.js, apps/sunrise/metadata.json
A minor tweak to sunrise - ensure we render the clock when a minute ticks over, so the time shown on screen lines up with other widgets (e.g. chimer).
Leaving as a draft until #3063 is merged, to avoid introducing conflicts.
=> sunrise: redraw the clock exactly when a minute ticks

apps/fastreset/ChangeLog, apps/fastreset/boot.js, apps/fastreset/metadata.json
Add inner timeout of 150 ms so user has more time to release the button before clock ui is initialized and adds it's button watcher for going to launcher.
Install this update (v.0.03) from my app loader: https://thyttan.github.io/BangleApps/?q=fastreset
Ideally I'd want to use something else than the inner timeout. But the other things I tested didn't work out. I haven't tried with a promise which maybe could be better. But I don't see how I'd make it work here.
I tried e.g.:
```js
{let buzzTimeout;
let shouldReset;
setWatch((e)=>{
if (buzzTimeout) {clearTimeout(buzzTimeout); buzzTimeout=undefined;}
if (shouldReset) {shouldReset=undefined; Bangle.showClock();}
if (e.state) buzzTimeout = setTimeout(()=>{Bangle.buzz(80,0.40);shouldReset=true;}, 250);
},
BTN,{repeat:true,edge:'both'});
}
``` …
=> fastreset:(partly) fix accidental load of launcher

apps/astral/ChangeLog, apps/astral/app.js, apps/astral/metadata.json
This fixes the sanity check warning:
```
Clock astral file calls loadWidgets before setUI (clock widget/etc won't be aware a clock app is running)
```
(there's no affected code between the old and new locations of `setUI()`)
=> astral: setUI before loading widgets

apps/cards/ChangeLog, apps/cards/app.js, apps/cards/metadata.json
With this PR we hide widgets while showing the barcode/QR and show them back while going back to the card's info. In this way, widgets are not covering part of the displayed code
Fixes: https://github.com/espruino/BangleApps/issues/3052
=> cards: hiding widgets while showing the code

apps/setting/settings.js
The code logic does not work because the function with no return, returns undefined. Ends up that both `prependListener` and `on` are called, creating 2 callbacks, yet only 1 is removed.
Noticed it from running lcd calibration, then touch anything else and it goes back into calibration.
=> settings: lcd calibration bug

apps/ios/ChangeLog, apps/ios/README.md, apps/ios/boot.js, apps/ios/metadata.json, apps/weather/ChangeLog, apps/weather/lib.js, apps/weather/metadata.json
Adds the ability for the bangle.js to receive weather data contained in custom notifications.
Calendar shortcut: https://www.icloud.com/shortcuts/baee5a95a55a4c5c8e6e582e09db020f
Weather shortcut: https://www.icloud.com/shortcuts/f21cd4c1753445a4aadec84b55c3e7e6
(requires OWM api key)
**Caveats:**
While notifications are automatically dismissed, they take up the top of the screen for a few seconds
- this can be avoided with a focus mode
Calendar does not send the `color` field
- defaults to `0`
- I couldn't figure out how to do this on the side of iOS. It may be possible to replicate this by assigning calendar names to colors.
Weather does not give a forecast--just the current weather conditions
- this might be an issue with my understanding of the bangle.js weather library
relevant …
=> Add weather and calendar data to iOS integration

apps/recorder/ChangeLog, apps/recorder/metadata.json, apps/recorder/widget.js
Resolves [an issue](https://github.com/espruino/BangleApps/pull/3098#issuecomment-1813310835) where the recorder widget might load without having a settings file, leading to:
```
>
Uncaught Error: Cannot read property 'forEach' of undefined
at line 1 col 2805 in recorder.wid.js
...Recorders();settings.record.forEach(r=>{var recorder=recorders[r...
^
in function "getActiveRecorders" called from line 1 col 4959 in recorder.wid.js
...Headers(getActiveRecorders()).join(",")){options.force="new"...
^
in function "setRecording" called from line 11 col 368 in recorder.app.js
...["recorder"].setRecording(v).then(function(){loadSettings();showMai...
^
in function called from system
```
=> recorder: handle initial/non-settings load

apps/health/interface.html
Fixes also average bpm on 0 value
When hrm interval in health is off bpm data is only available when another app activates the heart rate monitor, for all other records bpm value is 0.
=> health/interace: Replace moving average for bpm with avg

apps/recorder/ChangeLog, apps/recorder/metadata.json, apps/recorder/widget.js
This will make logs with 1 second periods record time with 1 decimal place precision.
EDIT3 - my first solution seemed to behave weirdly to me. But after sitting on it I realized it was probably just floating point number math doing what it does. The discussion that followed here no longer applies.
=> Recorder: 1 second period with 1 decimal place

apps/altimeter/ChangeLog, apps/altimeter/app.js, apps/altimeter/metadata.json
Use system variables to calibrate altimeter. That means that calibration works for other applications, too, and persists between altimeter starts.
Immediately show altitude after calibration changes, otherwise it is hard to set the calibration as the actual values lag behind reality.
=> altimeter: use system variables to calibrate altimeter.

apps/calendar/interface.html, apps/espruinoterm/interface.html, apps/grocery/interface.html, apps/guitarsongs/manage_songs.html, apps/mylocation/interface.html, apps/noteify/interface.html, apps/openstmap/interface.html, apps/owmweather/interface.html, apps/powermanager/interface.html, apps/rep/interface.html, apps/sched/interface.html, apps/sleepphasealarm/interface.html, apps/tinycmc/interface.html
Added Utils.readStorageJSON and relaxed JSON parser, and swap all interface.html over to using it.
This allows Bangle.js 2v20 (or cutting edge) and later to store a relaxed 'JSON' on internal storage which (while still normal JS) is smaller and faster (and preserves unicode better)
Fixes https://github.com/espruino/Espruino/issues/2429
It'd be great if you could take a look over this as I had to change a bunch of files.  I've tried some (eg openstmap) and they work ok, but it may well be I broke something :(
=> Added Utils.readStorageJSON with relaxed JSON parser

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
If some alarms have their Group set, those groups will appear at the end of the main list of alarms.  Selecting the Group will show the alarms it contains (i.e. alarms that have that same Group).
Also, when coming back from a Group or from editing an existing alarm, the main list of alarms will be scrolled to the position where it was previously (instead of showing the top of the alarm list).
=> [alarm] show alarm groups if setting is ON; scroll alarms menu to previous position when going back

apps/presentor/ChangeLog, apps/presentor/README.md, apps/presentor/app.js, apps/presentor/metadata.json
Finally I got back to using Bangle in school so that warrented me putting time into improvements in the presentor app.
It now works with windows 11 again also!
This PR fixes some issues and makes the experience a lot better. The app is still in beta I guess but it works well enough for me most of the time 😄
=> Presentor V0.08 -> V0.14

apps/spotrem/ChangeLog, apps/spotrem/app.js, apps/spotrem/metadata.json
I did some refactoring to `spotrem` when working on the slider module. I've been using the changes since then.
>I guess it could be taken further. There's pretty much duplication inside the command objects (e.g. `categories: ["android.intent.category.DEFAULT"]`). But this change was easy to start with.
_Originally posted by @thyttan in https://github.com/espruino/BangleApps/pull/2953#discussion_r1349679526_
=> spotrem: some refactoring shortening the code

modules/widget_utils.js
Hi
A clock I'm developing is using hideable widgets. I've noticed that every now-and-then the clock stops updating after showing the widgets. I'm using an interval (not timeout) to update the clock.
I think I found the culprit.
=> widget_utils: use correct variable to clear interval

apps/calendar/ChangeLog, apps/calendar/calendar.js, apps/calendar/metadata.json
Previously events were loaded and as result painted first and a following draw on a holiday would overwrite the event indicator
=> calendar: Load holidays before events

apps/forge/ChangeLog, apps/forge/forge.app.js, apps/forge/metadata.json
... by adding the string `"Bangle.loadWidget()";`. This way Fastload Utils thinks widgets would be present and so fastloads. But in the absence of Fastload Utils no widgets will be loaded, and so no overhead is added for the usual case.
Exiting forge will be done with a regular `load()` call in both cases, since no remove-handler is added to a `Bangle.setUI({})` call.
=> forge: Compatibility with Fastload Utils

apps/90sclk/settings.js, apps/banglexercise/settings.js, apps/bwclk/settings.js, apps/bwclklite/settings.js, apps/circlesclock/settings.js, apps/clicompleteclk/settings.js, apps/fuzzyw/fuzzyw.settings.js, apps/health/settings.js, apps/lcars/lcars.settings.js, apps/limelight/limelight.settings.js, apps/linuxclock/settings.js, apps/mosaic/mosaic.settings.js, apps/pebble/pebble.settings.js, apps/slopeclockpp/settings.js, apps/weather/settings.js, apps/widbgjs/settings.js, apps/widpedom/settings.js, bin/sanitycheck.js
Remove manual boolean formatters - rely on pre-existing default formatter. This continues the work done by @alessandrococco in #1980 / 42c2b5c8a2 and introduces a change to `bin/sanitycheck.js` to catch future introductions.
=> Remove unnecessary boolean formatters

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json
=> android: Fix alarms created in Gadgetbridge not repeating

apps/fwupdate/custom.html
It'd be nice to have the firmware changelogs linked to from the firmware updater. The custom.html page seemed like the best spot for now, until a readme with more detail is made.
I wasn't sure if I should increase the version number or not, since this was more of a documentation fix?
I also fixed a couple small bugs (features?) in the page:
1) When viewed in gadgetbridge, some of the links try to open as a frame inside the popup. It didn't seem intentional, since other links opened in a new window.
2) When clicking the DFU or Advanced toggles, it jumps to the top of the page. Other js links on the page use preventDefault, so I assumed those should too.
Link to my updated app loader:
https://thinkpoop.github.io/BangleApps
=> [fwupdate] Add links to firmware changelogs; couple minor fixes

apps/aviatorclk/ChangeLog, apps/aviatorclk/README.md, apps/aviatorclk/aviatorclk.app.js, apps/aviatorclk/metadata.json
This is an update for the "aviatorclk". Triggered by @nxdefiant 's comment when the app was originally submitted, I've added a way to easily toggle the seconds display (through double taps left or right).
And I found the taps useful to scroll the METAR display, too.
This PR also includes a minor bug fix (set the background colour prior to seconds updates).
=> aviatorclk: added tap event to scroll METAR and toggle seconds display

apps/.eslintrc.json, apps/calculator/app.js, apps/calendar/calendar.js, apps/colorwheel/app.js, apps/configurable_clock/app.js, apps/gbmusic/app.js, apps/marioclock/marioclock-app.js, apps/messagesoverlay/lib.js, apps/score/score.app.js, apps/waternet/app.js
When declaring variables inside switch cases, the variables are also available in the other switch cases, with some special rules. This is basically never the intention, and can lead to weird bugs. I suggest requiring switch blocks when variables are declared, which limits the scope of the variable to the individual case.
=> Require switch blocks when declaring variables

apps/health/README.md
reference:
> The health app on the Bangle only stores data every 10 minutes. The '3 minute' option is for the heart rate - it'll take 3 HRM samples every 10 minute slot and use the best/average value of HRM readings - but it only stores one reading per 10 minutes.
https://forum.espruino.com/conversations/386312/#comment16972306
=> health: add hrm info to readme

apps/flightdash/flightdash.settings.js
This drops the warning we keep seeing (`Settings for flightdash has a boolean formatter - this is handled automatically, the line can be removed`). No change in behaviour, no need for a version bump.
=> flightdash: drop unnecessary boolean formatter

apps/.eslintrc.json, apps/andark/app.js, apps/aptsciclk/ChangeLog, apps/aptsciclk/app.js, apps/aptsciclk/metadata.json, apps/carcrazy/ChangeLog, apps/carcrazy/app.js, apps/carcrazy/metadata.json, apps/doztime/ChangeLog, apps/doztime/app-bangle1.js, apps/doztime/metadata.json, apps/hwid_a_battery_widget/ChangeLog, apps/hwid_a_battery_widget/metadata.json, apps/hwid_a_battery_widget/widget.js, apps/novaclock/app.js, apps/red7game/ChangeLog, apps/red7game/metadata.json, apps/red7game/red7.js, apps/spacew/prep/minitar.js, apps/tabanchi/ChangeLog, apps/tabanchi/app.js, apps/tabanchi/metadata.json
The `no-empty` rule checks that there are no empty blocks defined in the code, similar to the check for unused variables.
I have disabled the check for empty catch blocks, because they are a useful shortcut for trying something and failing softly. Obviously it would be better to enforce explicit error handling for all try blocks, but I think this is one of the cases where the benefit doesn't outweigh the extra work for contributors.
Warnings about empty blocks can make the developer restructure their code to be more readable, have less overhead, and can help them find bugs. I actually think I found one in the `carcrazy` app. @Ronin0000 is it on purpose that level 7 is ignored? It seems like it should be included in the check at line 49 :)
I have tested these apps to the point where I'm …
=> Warn about empty blocks

apps/linuxclock/ChangeLog, apps/linuxclock/app.js, apps/linuxclock/metadata.json
Date.getMonth() returns an integer from 0 to 11, so to display the date I think it's better to add 1.
I did not try to install the app by deploying the full website but I did test the simple change by modifying the app directly with the IDE.
For such a simple change I hope it's enough.
=> linuxclock - Bugfix Add 1 to month received from Date.getMonth (0..11)

apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js
This was breaking a reload of the settings app after cancelling battery recalibration
=> settings: fix typo

apps/messagegui/ChangeLog, apps/messagegui/README.md, apps/messagegui/app.js, apps/messagegui/metadata.json
Swipe up/down on a shown message to show newer/older message.
I would personally rather map up/down to older/newer. But I think up/down mapped with newer/older makes more sense with how 'tick' and 'cross' swipes are done and how the messages are presented in the scroller list. 
Thoughts? @gfwilliams @bobrippling
The change can be tried by installing from my app loader: https://thyttan.github.io/BangleApps/?q=messagegui
=> messagegui: swipe up/down on msg goes to newer/older msg

apps/sched/ChangeLog, apps/sched/README.md, apps/sched/metadata.json, apps/sched/sched.js, apps/sched/settings.js, typescript/types/sched.d.ts
... so an alarm will buzz until it is stopped by the user.
Also updated `sched`'s readme to align it with the latest code.
=> sched: permit buzz count to be infinite

apps/rep/interface.html
`reps` is global to `interface.html`, no longer assigned after fcebbf3ef4d4 / #3110. This resolves that issue
=> rep: fix interface.html

apps/sleeplog/ChangeLog, apps/sleeplog/lib.js, apps/sleeplog/metadata.json
@storm64 is this a change you'd be happy with? I found my storage would populate with files containing an empty array, which slowed down listing files (e.g. connecting from the app loader)
=> sleeplog: only write log if we have something to write

apps/sched/interface.html
This gives `sched`'s `interface.html` the ability to select which days an alarm will trigger on.
Deployed on [my gh-pages](https://bobrippling.github.io/BangleApps/?q=sched)
=> sched: add day selection to interface.html

apps/sched/ChangeLog, apps/sched/lib.js, apps/sched/metadata.json, apps/widalarm/ChangeLog, apps/widalarm/metadata.json, apps/widalarm/widget.js, apps/widalarmeta/ChangeLog, apps/widalarmeta/metadata.json, apps/widalarmeta/widget.js
This allows `widalarmeta` to update itself when alarms change, which happens if we modify them and use fastload utils to return to the clock face without a full widget reload.
@nxdefiant is this change alright by you?
=> widalarmeta: recheck latest alarm when alarms change

apps/widlockunlock/ChangeLog, apps/widlockunlock/metadata.json, apps/widlockunlock/widget.js
This avoids having to try to dodge the lock/unlock widget when going back
=> widlockunlock: disable tap-to-lock if back button is present

.github/workflows/nodejs.yml, bin/exempt-lint.mjs, bin/sync-lint-exemptions.mjs
It seems there is still a use case for nodejs 18, so this PR ensures everything runs on v18. I also downgraded the CI to v18 because as you say, it ensures the scripts work for as many people as possible :)
=> Support Nodejs 18

apps/clock_info/ChangeLog, apps/clock_info/README.md, apps/clock_info/lib.js, apps/clock_info/metadata.json, apps/smpltmr/ChangeLog, apps/smpltmr/clkinfo.js, apps/smpltmr/metadata.json, typescript/types/clock_info.d.ts
@gfwilliams @sir-indy I'd like `smpltmr`'s `clkinfo` menu to reset to the "main" menu (showing the time remaining on the timer) after no interaction from the user.
To do this requires shuffling around some clkinfo code to create an API for selecting a given menu. If this seems reasonable to you both, I'll give it a test.
([git's `diff.colormoved`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt) might be useful for seeing which lines have moved but are otherwise unchanged)
=> smpltmr: reset clkinfo to "main" timer after no interaction

apps/lint_exemptions.js, apps/timerclk/ChangeLog, apps/timerclk/alarm.js, apps/timerclk/metadata.json, apps/timerclk/timer.js
Closes #3273
The `timerclk` app uses indirect variable access and it fooled me into believing that this change was safe.
=> Revert changes to timerclk

apps/rep/app.ts, typescript/types/layout.d.ts
`ExtractIds` wasn't picking out the IDs (`id: ... extends string` rather than `id?: ... extends string`) and the resulting union of objects needed to be merged.
Closes #3251
Confirmed with a demo app and `apps/rep` (no version bump as changes are type-level only -> no `.js` changes)
=> Fix typescript for `Layout`

apps/chargent/ChangeLog, apps/chargent/README.md, apps/chargent/boot.js, apps/chargent/metadata.json
This allows a user to silence the buzz/notification once seen
=> chargent: allow a tap on the notification to silence it

apps/fwupdate/custom.html
It is somewhat confusing that the NRF firmware files are double-zipped. I was not able to upload firmware because of this, and I could not find the documentation which noted that you need to manually unzip the file once before uploading it. Now that I know this, it is still a tedious extra step to unzip the file every time I want to test something on my watch.
Therefore I suggest this change, which allows the firmware loader to understand double zipped firmware files. It works by checking if the zip file contains nothing but a single zip file inside it. If yes, the firmware is assumed to be inside the zipped zip file, and so that file is unzipped and used as if that was what the user had uploaded.
I have tested this change with all the firmware files available in the [Firmware Build …
=> `fwupdate` Support double zipped firmware files

apps/vpw_clock/ChangeLog, apps/vpw_clock/app.js, apps/vpw_clock/metadata.json
Fix some issues with colors when using dark themes by setting complete theme. Additionally remove the VGA8 font.
=> vpw_clock - Restore whole theme and unload VGA8 font

apps/widbata/widbata.wid.js
this just brings the battery icon up by 2 pixels so that is is centered vercially on the 24px widget band
=> Battery Widget Themed fix: center widget vertically

apps/lint_exemptions.js, apps/recorder/ChangeLog, apps/recorder/app.js, apps/recorder/metadata.json
The exemption for this file was broken in #3297 but the warning was not fixed.
The code includes an unused variable that seems safe to remove. I have tested the app and it does not seem to break in any way.
The code seems to be written by @gfwilliams, maybe you can check it to be sure?
=> `recorder` Remove unused variable

apps/bigdclock/ChangeLog, apps/bigdclock/bigdclock.app.js, apps/bigdclock/metadata.json
The value of "width" was being reset somewhere, which meant that the battery usage feature wasn't working - it was resetting to "battery empty" whenever the clock updated.
So "width" has been renamed to "batteryUsedWidth", which is better anyway, as it is more descriptive of what the variable does.
=> New bug in bigdclock.app.js

apps/health/ChangeLog, apps/health/app.js, apps/health/metadata.json, apps/lint_exemptions.js
`health` sets a single variable in the global scope that seems like it can be removed safely. I have tested this change and could not find any issues with it.
=> `health` Remove unused variable

apps/hrm/ChangeLog, apps/hrm/heartrate.js, apps/hrm/metadata.json, apps/lint_exemptions.js
`hrm` currently adds two variables to the global scope, this should keep them local.
I have tested these changes and could not find any bugs.
=> `hrm` Fix memory leaks

apps/fastload/README.md
This adds a warning to the fastload README regarding bad behaviour in combination with the new automatic reload of the apploader.
=> fastload - Add warning about automatic reload apploader option

apps/lint_exemptions.js, apps/ratchet_launch/ChangeLog, apps/ratchet_launch/app.js, apps/ratchet_launch/metadata.json
In #2719, the app was updated to access storage via the variable `s` which is not defined. This was flagged by the new linting rules, which is how it caught my attention. Unless you are lucky and something else has defined `s` for you, this means the launcher cannot even open.
It turns out there is also a bug with the default `blankImage`, it is not supported by the `Layout` library. I assume that this worked when the app was designed, but that later revisions of Espruino disallowed images with no height. I have added newlines to give the image a bit of height, which makes it work again.
=> Fix bugs in `ratchet_launcher`

apps/messagegui/ChangeLog, apps/messagegui/app.js, apps/messagegui/metadata.json
So that the user can read the long message uninterrupted :)
=> [messagegui] Fix: When user taps on a new message, clear unread timeout

apps/imgclock/ChangeLog, apps/imgclock/app.js, apps/imgclock/metadata.json
There is an issue, where if you open an app that has graphics on the bottom, and hold down BTN3 to go to the image clock, a small amount of the apps graphics (about 10px) will show on the bottom. This update just adds an initial clear, which clears other app's graphics.
I am using a banglejs v1 (firmware 2v21).
=> Fix other app's graphics showing on image clock (BANGLEJS 1)

apps/bthrm/ChangeLog, apps/bthrm/README.md, apps/bthrm/bthrm.js, apps/bthrm/default.json, apps/bthrm/lib.js, apps/bthrm/metadata.json, apps/bthrm/recorder.js, apps/bthrm/settings.js
Moves the caching of device characteristics out of the library code and into the settings. Reduces the lib by about 1/6 and potentially saves on flash writes since the connect is now strictly read only. Caching now only happens once during initial pairing with the sensor.
=> bthrm - Move caching of characteristics into settings

apps/gpsinfo/ChangeLog, apps/gpsinfo/gps-info.js, apps/gpsinfo/metadata.json, apps/lint_exemptions.js
`gpsinfo` currently adds a lot of random numbers to the global scope, this should keep the variables local.
I am unfortunately not able to test these changes because my watch refuses to aquire a GPS fix. Maybe some of you can give it a quick check? I am pretty confident that the changes work :)
=> `gpsinfo` Fix memory leaks

apps/clock_info/ChangeLog, apps/clock_info/lib.js, apps/clock_info/metadata.json, typescript/types/clock_info.d.ts
This avoids issues when we have multiple clkinfos visible. The first clkinfo may want to focus itself, but a second clkinfo may then unfocus, deleting the first's effects (i.e. setting `CLKINFO_FOCUS`).
In detail:
`CLKINFO_FOCUS` will be set (to `true`) by the first handler (left hand clkinfo) and then unset (/ `delete`d) by the second handler (right hand clkinfo).
This is done in [the `touchHandler`](https://github.com/espruino/BangleApps/blob/c2ea454a3bc7bfaefbc39a5b376510bb9d7d4ec8/apps/clock_info/lib.js#L313-L324).
This commit makes `CLKINFO_FOCUS` a count.
- When we have a tap on a previous clkinfo (previous as in, earlier in the event handler list), it'll focus itself, `CLKINFO_FOCUS++`
- The later handler comes along, unfocuses itself, `CLKINFO_FOCUS--`
- `CLKINFO_FOCUS` is now …
=> clkinfo: make `CLKINFO_FOCUS` a counter

apps/fileman/ChangeLog, apps/fileman/manage_files.html, apps/fileman/metadata.json
This adds a small interface to the app loader to manage files in the app loader and not just on the watch. You can list, delete and show files in the loader and it shows the storage stats.
=> fileman: allow managing files in the app loader

apps/messagegui/ChangeLog, apps/messagegui/app.js, apps/messagegui/metadata.json
This MR does two things:
- move the code that sets the `unreadTimeout` to a new function called `resetReloadTimeout`
- each time a new message is received, call `resetReloadTimeout`
This way, if you receive a lot of consecutive messages, you are guaranteed to be able to read the last one, because your timeout starts from its reception and not from the reception of the first one like before.
=> [messagegui] fix: handle the unreadTimeout better

apps/ha/ChangeLog, apps/ha/README.md, apps/ha/ha.app.js, apps/ha/ha.lib.js, apps/ha/metadata.json, modules/Slider.js, modules/Slider.md
... for example, to adjust light brightness:
Currently this works through a non-GadgetBridge shim I have, which pretends to be GB in order to respond to these messages. Interested in what people think.
@peerdavid would you find anything like this useful to include in `ha`? I can move this to another app (although the changes shouldn't interfere with the original behaviour)
@thyttan I've made a few tweaks to the slider library too, mainly:
- Pass `e` through to the callback (the drag event)
- Reset `dragActive` at the end of a drag
- Always send through the final event (so users can detect `e.b == 0` i.e. finger lift up)
=> ha: add value triggers

apps/bootgatthrm/ChangeLog, apps/bootgatthrm/boot.js, apps/bootgatthrm/metadata.json
This allows a user to (manually) place a config file to keep BLE connected - this prevents bluetooth from disconnecting every time a HRM event fires
@AnotherStranger does this look ok to you?
=> bootgatthrm: allow option to prevent disconnect

apps/multitimer/ChangeLog, apps/multitimer/boot.js, apps/multitimer/metadata.json
A minor bugfix to prevent exceptions in the multitimer event handler
=> multitimer: handle undefined alarm.data

apps/owmweather/ChangeLog, apps/owmweather/lib.js, apps/owmweather/metadata.json
[One Call API 2.5 will be deprecated in June 2024](https://openweathermap.org/api/one-call-api).
Upgrade to One Call API 3.0.
Add pressure to weather.json
=> owmweather: upgrade to One Call API 3.0

apps/drained/ChangeLog, apps/drained/app.js, apps/drained/app.ts, apps/drained/metadata.json
This makes it more clear when the user enables bluetooth, and allows them to also turn it back off
=> drained: change enable/disable BLE depending on state

apps/backswipe/ChangeLog, apps/backswipe/boot.js, apps/backswipe/metadata.json, apps/backswipe/settings.js
fix for https://github.com/espruino/BangleApps/issues/3388
=> backswipe:fix could not blcklist messagegui.new.js

apps/chargent/ChangeLog, apps/chargent/boot.js, apps/chargent/metadata.json, apps/notify/notify_bjs2.js
Introduced by and documented in #3262.
This also shortens the message length to fit on the screen
=> chargent: fix manual/tap hiding of notification

apps/messagesoverlay/ChangeLog, apps/messagesoverlay/lib.js, apps/messagesoverlay/metadata.json
* Listeners added with `prependListener` were not tracked,
* 2v21.104 renamed the internal variable for callbacks stored with setWatch from `callback` to `cb`. This should handle both variants
=> messagesoverlay - Handle prependListener and setWatch callback variable name change

apps/widdevst/ChangeLog, apps/widdevst/README.md, apps/widdevst/metadata.json, apps/widdevst/wid.js
This change tweaks the drawing of `widdevst` to be fired by a change of a peripheral (such as a HRM event), so that:
- if peripherals are on, it'll redraw as regularly as it did before this change
- if periperhals are off, it'll redraw at the same (lower) frequency, or possibly not at all if the next option is enabled (saving draw time & battery)
The setting change allows us to configure the widget to only draw when a peripheral changes, at the cost of not having directly up-to-date bars for storage & memory.
@notEvil what do you think? I'm going to try this out for a little while and see how it compares time-wise to the current implementation
=> widdevst: add ability to only redraw when a peripheral changes

apps/run/ChangeLog, apps/run/metadata.json, apps/runplus/ChangeLog, apps/runplus/metadata.json, modules/exstats.js
This is definitely not the correct fix - in my case:
```
>state.startSteps
=336651
>Bangle.getStepCount()
=47487
```
What I expect has happened is that `startSteps` is from a previous run and hasn't been reset overnight, whereas the step count has. I'm not familiar with exstats, @gfwilliams / @GrandVizierOlaf what do you think?
=> exstats: fix steps being negative

bin/sanitycheck.js
Following on from #3256, this lets us catch warnings in PRs and makes it more clear for the PR author, who might miss the messages that are tagged onto the file view.
=> sanitycheck: promote warnings to errors in CI

modules/widget_utils.js
Currently a swiped down widget bar stays on display when fastloading from clock to launcher. This cleans up the overlay if nothing else called `setLCDOverlay` in the meantime.
This will fail if something else replaces `setLCDOverlay`. That might not be problematic since there are limited use cases for doing that?
=> widget_utils - Remove the overlay on cleanup

apps/multitimer/ChangeLog, apps/multitimer/app.js, apps/multitimer/metadata.json
e.g. a `showMenu()`'s `setUI` call.
Without this, a `showMenu`'s call doesn't get its `remove` callback called.
=> multitimer: preserve original `uiRemove`

apps/clkinfocal/ChangeLog, apps/clkinfocal/clkinfo.js, apps/clkinfocal/metadata.json
Remove duplicated day in calendar when format setting is 'dd MMM'
You can test the branch here https://vczb.github.io/BangleApps/?c=clkinfo&q=clkinfocal
Close #3429
=> clkinfocal: remove duplicate day in calendar when format setting is 'dd MMM'

apps/bootgattbat/ChangeLog, apps/bootgattbat/boot.js, apps/bootgattbat/metadata.json, apps/bootgatthrm/ChangeLog, apps/bootgatthrm/boot.js, apps/bootgatthrm/metadata.json, apps/btadv/ChangeLog, apps/btadv/app.ts, apps/btadv/metadata.json, apps/bthome/ChangeLog, apps/bthome/boot.js, apps/bthome/metadata.json, apps/openhaystack/ChangeLog, apps/openhaystack/custom.html, apps/openhaystack/metadata.json, modules/ble_advert.js, modules/ble_advert.ts, tsconfig.json
This adds a module to coordinate BLE advertising, for apps such as openhaystack, gattbat and gatthrm.
Currently the code doesn't work because `NRF.setAdvertising` modifies the passed in object, so we lose track of which entry is for which BLE Service ID
<details>
<summary> Example of NRF type conversion </summary>
```
>ba=require("ble_advert") // old version
=...
>ba.set(0xffff, y={})
Uncaught TypeError: If specifying an object, it must be of the form {data : ..., count : N} or {callback : fn} - got {  }
at line 24 col 280 in .boot0
...etAdvertising(a.bleAdvert,j)
in function "set" called from line 1 col 20
ba.set(0xffff, y={})
>Bangle.bleAdvert
=[
new Uint8Array([2, 1, 6, 3, 3,  ... 32, 54, 53, 102, 48]).buffer,
new Uint8Array([30, 255, 76, 0, 18,  ... 80, 230, 104, 3, 0]).buffer,
new …
```
=> Add `ble_advert` module

apps/messagesoverlay/ChangeLog, apps/messagesoverlay/lib.js, apps/messagesoverlay/metadata.json, modules/widget_utils.js
Adapt to changes made for #3417.
=> Adapt widget_utils and messagesoverlay to new LCD overlay code for remove callbacks

apps/runplus/ChangeLog, apps/runplus/app.js, apps/runplus/metadata.json, apps/runplus/settings.js
For example, when doing reps with 1 minute rests, a user can configure runplus so it automatically resumes if started within the minute
=> runplus: add option to always resume

apps/astrocalc/ChangeLog, apps/astrocalc/astrocalc-app.js, apps/astrocalc/metadata.json
I noticed a bug in the Moon > Times menu.
My (very basic) understanding is that the `rise` and `set` members of the `times` object returned by the `getMoonTimes` function car actually be `undefined`, depending on if the moon rise or set actually occur on the current day.
This MR handles these cases.
=> fix(astrocalc): handle when moon rise/set don't occur on current day

apps/vpw_clock/ChangeLog, apps/vpw_clock/app.js, apps/vpw_clock/metadata.json
As per this discussion: https://forum.espruino.com/conversations/395233
Do not remove the VGA8 font as part of the remove `handler`
=> VPW clock: do not remove VGA8 font for fast loading

apps/widbtstates/widget.js, apps/widbtstates/widget.ts
I might be wrong but I think there is a mistake here, because cyan is much more readeable on a black background, and same for blue on a white background
=> BT States Widget fix: handle colors themes better

apps/recorder/interface.html
Useful for downloading all files at once, deployed to my [gh-pages](https://bobrippling.github.io/BangleApps/?id=recorder).
Changes:
- Ability to download all tracks (as kml/gpx/csv)
- Show currently downloading/deleting filename
- An unrelated fix (ecf1f2e) for when we try to save a CSV with no non-header lines
=> Recorder: add ability to download all tracks at once

apps/boot/ChangeLog, apps/boot/bootupdate.js, apps/boot/metadata.json, apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js, typescript/types/main.d.ts, typescript/types/settings.d.ts
This follows on from espruino/Espruino#2506, providing an easy way for a user to configure BLE privacy.
Currently the simple modes are supported:
- Off
- On
- On with the device's name hidden
---
This also updates typescript types for the settings object, and brings in typings from espruino (espruino/Espruino#2516)
=> Add BLE privacy setting

apps/widdst/ChangeLog, apps/widdst/metadata.json, apps/widdst/settings.js
... for example, when fastload is installed, so we don't jump back to the clock with the old DST settings.
=> widdst: ensure DST is applied when leaving settings

apps/daisy/ChangeLog, apps/daisy/README.md, apps/daisy/app.js, apps/daisy/metadata.json, apps/daisy/settings.js
Hi, I saw https://forum.espruino.com/conversations/395838/ and I wanted to implement it on my favorite clock. So I did.
Maybe @hughbarney has a review comment it being your app?
I decided not to check the firmware version when toggling the setting, this could be added if wanted (it being off by default I don't think people enable it if they aren't on the most recent version, or that those people couldn't find out the issue then :D)
Edit: After running around with this I realized that the big hour estimate is really not something I want to convert in my head, so I changed it now that it shows days instead. As soon as we get in the lower region the actual estimate jumps really noticeably, I am unsure if I should "catch" this here and probably just not display them, or if the function should …
=> Update Daisy clock to add battery estimate in hs

apps/setuichange/ChangeLog, apps/setuichange/boot.js, apps/setuichange/metadata.json
as per https://forum.espruino.com/comments/17443678/
=> setuichange: fix push to undefined btnWatches array

apps/setting/ChangeLog, apps/setting/metadata.json, apps/setting/settings.js, apps/swiperclocklaunch/ChangeLog, apps/swiperclocklaunch/boot.js, apps/swiperclocklaunch/metadata.json
swiperclocklaunch now reliably detects a clock, using existing logic in `setUI` instead of inspecting arguments
=> swiperclocklaunch: fix detection of clock

apps/daisy/ChangeLog, apps/daisy/app.js, apps/daisy/metadata.json, apps/daisy/settings.js
=> Daisy Fix: Put default to False for battery display

apps/ffcniftyapp/ChangeLog, apps/ffcniftyapp/app.js, apps/ffcniftyapp/metadata.json
If other languages than English are used, comparing the weather description to determine the appropriate weather icon fails. This pull request alters this behaviour:
1. Check for the current locale
2. Use weather code if a language other than English is used instead of description to choose icon
The code in question was borrowed and adapted from the weatherClock app.
=> ffcniftyapp: Fix weather icon on non-English locale

apps/slopeclockpp/ChangeLog, apps/slopeclockpp/app.js, apps/slopeclockpp/metadata.json
@eyecreate @myxor @hughbarney what do you think of this? I feel like there might be a better way to ensure the clock info is always visible
=> slopeclockpp: avoid reusing background colour for clkinfo

apps/promenu/bootb2.js, apps/promenu/bootb2.ts
This fixes promenu to:
- return a `scroller` (permitting it to work with the alarm app)
- avoid calculations on menu items with image strings, assuming the app has figuring this out already
=> Fix promenu behaviour: scroller & image strings

apps/locale/locale.html
I have been using these features a lot on my local server and I really like them, so I thought I would try to upstream them.
I have added  the option "Advanced: Customize the date and time formats.". When you enable it, you get some input boxes that allow you to change the  date and time formats before uploading the locale to your watch. I think this is really useful, as people often have personal preferences that don't align with the default format for their country. I am at least one of those people.
As you can see on the screenshot, I have added a few suggestions for each input that appear in a drop down when you click the input. This will hopefully help users a bit, but if this PR is accepted, I also want to write a tutorial that describes the formats in more details.
Most people have …
=> locale: Support custom date and time formats, save the last uploaded locale

apps/messagegui/ChangeLog, apps/messagegui/app.js, apps/messagegui/metadata.json, apps/reply/ChangeLog, apps/reply/lib.js, apps/reply/metadata.json
Adds support for the canned responses/reply lib to the default messagegui app.
By clicking on a notification to head to the notification settings, the user will see a "reply" menu item if the message can be replied to, which will trigger the reply library flow
=> Add support for reply lib to messagegui app

apps/locale/ChangeLog, apps/locale/metadata.json
I forgot to release a new version when updating `locale` in #3535 and #3547
=> locale: Release new version

apps/gbmusic/ChangeLog, apps/gbmusic/metadata.json, apps/gbmusic/settings.js
This removes the deprecated translation system and adds the new translation system.
I have intentionally removed the translation of the `< Back` string because it will be rendered as a red back button with no text, but if it is translated, the red button disappears and a new entry is added to the menu with the translated version of `< Back`. That is not very nice.
=> gbmusic: Upgrade to new translation system

apps/pomoplus/ChangeLog, apps/pomoplus/README.md, apps/pomoplus/app.js, apps/pomoplus/metadata.json
for legibility and ease of use.
Changes made primarily for the Bangle.js 2. I haven't run them on an actual Bangle.js 1 watch - only the emulator. The update can be tried here (please report back if you try!): https://thyttan.github.io/BangleApps/?id=pomoplus
@bruceblore @notEvil thoughts?
Edit: After measuring ram use it think it still fits on the Bangle.js 1.
=> pomoplus: increase size of fonts and buttons

apps/calculator/ChangeLog, apps/calculator/app.js, apps/calculator/metadata.json
If the resulting number is longer than can be displayed, truncate it so that the (usually) significant part is displayed.
A '-' is append to indicate a truncated number (the font doesn't provide a better character for this than '-').
For example, before this change a simple "5 / 3" resulted in only 6s being displayed - rather than a more useful "1.666666-".
=> calculator: truncate long numbers

apps/promenu/bootb2.js, apps/promenu/bootb2.ts
Currently titles are truncated, e.g. `"Settings for cl..."`. This change scrolls the item when focused, so each frame you see:
```
"Settings for cl..."
"ettings for clo..."
"ttings for cloc..."
"tings for clock..."
"ings for clockf..."
"ngs for clockfa..."
"gs for clockfac..."
```
=> promenu: scroll long titles

.eslintrc.js, apps/locale/locale.html, apps/locale/locales.js, apps/locale/sanitycheck.js, bin/sanitycheck.js
I have removed the old sanitycheck which ran in the frontend. I have added a more comprehensive sanitycheck library that is used in two places:
- It runs as part of the CI sanitycheck, which means it should catch all issues before the code is merged.
- It runs in the frontend if the user chooses to customize their locale. If it detects an issue, the user is warned about the errors, but is still allowed to upload the locale if they wish. Example:
The upper limits on text length corresponds to the limits I defined in #3530
=> Improve sanity check for locales

apps/counter/ChangeLog, apps/counter/counter.js, apps/counter/metadata.json
Add support for translations with the `/*LANG*/` comment. I have split the strings into separate sentences to make the translation process a bit nicer, and also make it more likely that translations can be reused across apps.
=> counter: Support translations

apps/locale/locale.html, apps/locale/locales.js
Related to #3534
These formatting symbols are not used, and they should not be used because most apps only work with the time string `HH:MM:SS` and they expect the meridian to be accessible from the separate `meridian` function. I suggest removing these symbols.
The removal changes nothing for existing users of the app.
=> locale: Remove meridians from time patterns

apps/widbtstates/metadata.json
Change for sorting on apploader.
Not sure if version bump is needed for this.
=> fix: widbtstates is not clkinfo

apps/lcdclock/ChangeLog, apps/lcdclock/app.js, apps/lcdclock/metadata.json, apps/lcdclockplus/ChangeLog, apps/lcdclockplus/app.js, apps/lcdclockplus/metadata.json
When syncing e.g. weather info on the watch, the display/layout for temperature is broken/misplaced/invisible on `lcdclock` and `lcdclockplus` inside the clockinfo menus.
This PR fixed that issue by removing special characters from the clockinfo item text that can't be displayed by `7seg` font. The width calculation for the size definition becomes more accurate, which leads to a correct placement of the text.
=> lcdclock/lcdclockplus: fix special characters in clockinfo menus

apps/android/ChangeLog, apps/android/boot.js, apps/android/metadata.json, apps/reply/ChangeLog, apps/reply/lib.js, apps/reply/metadata.json
I realised during development of the "reply" library that Gadgetbridge contains support for setting canned responses/replies directly through the app, which is preferable to customising via ``interface.html`` as it can support emojis/Unicode using text as bitmaps.
This PR consists of 2 main changes:
- Add a "disp(lay)" field to the ``replies.json`` file used by the reply lib. If display is set for a particular canned reply, it will be shown on the menu instead of the default "text" field, which is what is sent to Gadgetbridge as a response. This way, the "disp(lay)" field shown on the watch can contain image representations of emojis and other Unicode characters, while the reply to Gadgetbridge contains the raw Unicode bytes
- Expand the Android integration app to listen for a …
=> Support Gadgetbridge Canned Responses

apps/locale/locales.js, apps/locale/sanitycheck.js, bin/sanitycheck.js
I think it would be useful to have a test locale for when you want to make sure your app can support all locales, even those with very long strings. Right now, you have to guess how much space to give each string, and that is a tedious and error prone method.
The length of each string in the test locale is as long as it is allowed to be, according to these limits:
| String              | Max characters   |
|---------------------|------|
| decimal point   | 1  |
| thousands sep  | 1 |
| speed              | 4     |
| distance          | 3     |
| temperature  | 2     |
| am/pm           | 3     |
| short time      | 5     |
| long time       | 8     |
| short date      | 11   |
| long date       | 14    |
| short month  | 4     |
| long month    | 11  |
| short day       | 4     |
| long …
=> Add a test locale

apps/hadash/ChangeLog, apps/hadash/README.md, apps/hadash/hadash.app.js, apps/hadash/interface.html, apps/hadash/metadata.json
This PR implements 2 suggestions by @bobrippling for the HA-Dashboard (hadash):
- return to the same position within the menu (after a HA query/call)
- a "silent" option for service calls
=> hadash: remember scoll positions of menus; "silent" option for service calls

apps/promenu/ChangeLog, apps/promenu/bootb2.js, apps/promenu/bootb2.ts, apps/promenu/metadata.json
This fixes `hadash`'s use of `showMenu`, which uses `menu[""]` (previously `delete`'d)
=> promenu: don't modify the menu object

apps/alarm/ChangeLog, apps/alarm/app.js, apps/alarm/metadata.json
This PR seems to fix the following. Tested in the Bangle.js 1 emulator on the Web IDE.
Just tried on emulated Bangle.js 1 and got:
```console
Uncaught Error: Can't read property 'scroll' of undefined
at line 20 col 1070 in alarm.app.js
...mMenu,10,e,index,undefined,scroller.scroll,group)
^
in function "onchange" called from line 3 col 106
...onchange)a.onchange(a.value);Bangle.touchHandler==u&&d.draw(...
^
in function "select" called from line 1 col 22
a?d.move(a):d.select()
^
in function "d" called from line 1 col 3
d()
^
in function called from system
> 
```
Looking at the git blame it seems to have been around since 2023-11-14.
_Originally posted by @thyttan in https://github.com/espruino/BangleApps/issues/3604#issuecomment-2397608781_
=> alarm: fix uncaught error if no scroller (Bangle 1)

apps/alarm/ChangeLog, apps/alarm/README.md, apps/alarm/app.js, apps/alarm/metadata.json
This will let the user toggle existing alarms, timers and events from the main menu of the app. Either by long touch of the menu entries or by touch on the icon on the right.
This change requires to send the touch event used in showScroller through to `alarm` app. Both `showScroller` and `showMenu` needs changes to make it work. So in this draft state of this PR I add two boot files for modifying those two functions. Have a look at the individual commits to see the diff from firmware version, which I copied over and committed unchanged before tweaking them.
Test it via: https://thyttan.github.io/BangleApps/?id=alarm
The tests fail for the showMenu boot file, but it works on the watch. Enough for testing purpouses.
=> alarm: toggle alarms from main menu

apps/recorder/interface.html
... to allow a user to save as GPX, then instantly as CSV, rather than waiting to download the same data again.
=> recorder: cache downloaded tracks

apps/promenu/ChangeLog, apps/promenu/bootb2.js, apps/promenu/bootb2.ts, apps/promenu/metadata.json
Following on from #3570, truncated titles which are scrolled in don't have "..." appended.
```
"Settings for cl..."
"ettings for clo..."
"ttings for cloc..."
"tings for clock   "
"ings for clock    "
"ngs for clock     "
```
=> promenu: don't show "..." when a string is fully scrolled in

apps/trail/ChangeLog, apps/trail/README.md, apps/trail/metadata.json, apps/trail/trail.app.js
Got down from 2 seconds per update to < 0.5 sec.
=> trail 0.10: Redesign to make screen updates fast

apps/dtlaunch/ChangeLog, apps/dtlaunch/app-b2.js, apps/dtlaunch/metadata.json
Draw the first screen, then load in the rest of the icons from storage.
=> dtlaunch: postpone load icons not initially needed

apps/drained/ChangeLog, apps/drained/app.js, apps/drained/app.ts, apps/drained/metadata.json
previously the assumption was that the `"changing"` event would be fired periodically when charging.
fixes #3625
=> drained: fix not restoring when charge threshold met

apps/sched/interface.html
This displays if an alarm is from an app (`appid`) and sorts it to the bottom if so
=> sched interface: handle app-based alarms

apps/reply/metadata.json
The reply lib metadata.json file currently does not list Bangle JS 1 support, which then blocks newer versions of the Messages app from installing on Bangle JS 1 devices as the lib can't be found. This adds support for Bangle JS 1, as I've tested in the emulator and there doesn't appear to be anything blocking this running on both devices
=> Update reply lib metadata.json to support Bangle JS 1

apps/android/lib.js, apps/messagegui/ChangeLog, apps/messagegui/lib.js, apps/messagegui/metadata.json
e.g. a call is answered, and the user has `auto-open` disabled. This allows a user to have infinite buzz (`Vibrate timer`) while the phone is ringing, but the buzz will stop when the call is answered (or declined)
=> messagegui: stop buzzing for a message when it's removed

apps/tinyheads/ChangeLog, apps/tinyheads/app.js, apps/tinyheads/lib.js, apps/tinyheads/metadata.json, apps/tinyheads/settings.js
as from title.
I did not like the visual effect of the widget bar having a completely different bg color from the rest of the clockface.
So I changed it, IMHO it looks much better now.
please let me know what you think @retcurve
=> tinyhead: change widget bg and fg colour so that widgets blend in with the rest of the clockface

apps/kbedgewrite/ChangeLog, apps/kbedgewrite/lib.js, apps/kbedgewrite/metadata.json
As discussed in https://github.com/espruino/BangleApps/pull/3633 setUI removes the back button by clearing a rectangle, even if the widget bar is hidden, so this PR moves hiding the widget bar and the draw of any initial text until after this has happened.
=> EdgeWrite: Draw initial text after setUI in case it removes a back button

apps/podadrem/ChangeLog, apps/podadrem/app.js, apps/podadrem/metadata.json, apps/spotrem/ChangeLog, apps/spotrem/app.js, apps/spotrem/metadata.json
On `edgewrite` keyboard the top left corner would be overwritten with a
square in solid background colour, the size and position of the red back
button of the previous menu.
Reproducible with with `edgewrite` installed and this code:
```js
E.showMenu({
"": {title: "hi there", back: ()=>{}},
"this": ()=>{}
});
//E.showMenu();
require("textinput").input({text:"Top left gets cleard by menu back button removal?"});
```
First brought up on https://github.com/espruino/BangleApps/pull/3632#discussion_r1825290432.
=> podadrem/spotrem: Fix linter warnings

apps/drained/app.js, apps/drained/app.ts, typescript/types/main.d.ts
To aid in usability when toggling options, such as BLE enabled
=> drained: restore menu position

apps/backswipe/ChangeLog, apps/backswipe/boot.js, apps/backswipe/metadata.json
Seems to mitigate some conflicts when switching between `edgeclk` (with seconds active) and `dtlaunch`. Sometimes the seconds redraw timeout of `edgeclk` would draw over `dtlaunch`. I don't really understand the conflict but it seems to be resolved by this change..
Can be tried via https://thyttan.github.io/BangleApps/?id=backswipe
=> backswipe: change to prepend swipe listener

bin/sanitycheck.js, package-lock.json, package.json
To help with PRs such as #3642
=> sanitycheck: parse ecma2020 constructs (`??`)

apps/smpltmr/ChangeLog, apps/smpltmr/app.js, apps/smpltmr/metadata.json
btn -> btnRelease as to not fire unintentionally when long pressing the button to reset the watch.
=> smpltmr: adapt to new setui

apps/dtlaunch/ChangeLog, apps/dtlaunch/app-b2.js, apps/dtlaunch/metadata.json, apps/dtlaunch/settings-b2.js
@bobrippling interested what you think about this!
Available on https://thyttan.github.io/BangleApps/?id=dtlaunch
=> dtlaunch: remember page between dtlaunch instances

apps/owmweather/ChangeLog, apps/owmweather/lib.js, apps/owmweather/metadata.json
After see the issue #3444 and the pull request #3427, I re-read the documentation I referenced in my pull request #3387 and  realize I misinterpreted the information.
The post says they upgraded the __One Call API 2.5__ to __One Call API 3.0__, but this app uses the [__Current weather data API__](https://openweathermap.org/current), which is different and free, and it does not require a payment method.
This pull request undoes that change.
I apologize for any inconvenience caused.
=> Undo change to One Call API 3.0

apps/owmweather/ChangeLog, apps/owmweather/boot.js, apps/owmweather/metadata.json
Fix an infinite loop when settings.updated is not defined. This issue was draining the entire battery within a day.
Fix some missing semicolons.
=> owmweather: Fix infinite loop when settings.updated is not defined

apps/andark/ChangeLog, apps/andark/app.js, apps/andark/metadata.json
I was using this clock face a lot, so I wanted to improve it. Thanks for the design @HeiLaut 
1. When unlocked, the second hand would not draw right away.
2. The second hand would not move on the second, rather it would move a second after being unlocked.
3. Sometimes locking or unlocking would not trigger the second hand to start drawing.
I tried to address these by using `queueDraw` and `updateState` approach from `antonclkplus`, and it seems to have fixed my problems.
```
____                 _
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
|_| espruino.com
2v24 (c) 2024 G.Williams
>Bangle.loadWidgets();Bangle.drawWidgets();
=undefined
>process.memory().usage
=4225
>eval(require("Storage").read("andark.app.js"))
=undefined …
```
=> andark: queue redraws and enable fastload 

apps/agenda/ChangeLog, apps/agenda/agenda.js, apps/agenda/metadata.json
Currently, allDay events are off by one day for negative timezones. Per the CalendarContract:
If allDay is set to 1 eventTimezone must be "UTC" and the time must
correspond to a midnight boundary.
For example, in GMT-2:00, an all day event on December 2nd (beginning at 00:00:00) will be wrongly displayed as starting on December 1st, since the locale will determine that the event's start time is actually 22:00:00 on Dec 1.
Source:
https://developer.android.com/reference/android/provider/CalendarContract.Events.html
This commit:
* Corrects the offset back to UTC 00:00:00 for allDay events
* Fixes the conditional for single-day all day events in showEvent()
* Fixes the display of formatDateShort() for some English locales by also removing any trailing commas or whitespace when the year is …
=> fix(agenda): all day event offsets, locale display

apps/andark/ChangeLog, apps/andark/app.js, apps/andark/metadata.json
PR #3678 removed immediate redrawing on charging, which is inconvenient, since when you connect the charger, watches may be locked and thus not redrawing, not showing the charging status. Additionally, I did a small correction regarding to the cleanup order to make fast loading work well, since one timeout was removed before a callback that could reset it again. Also, I did some (I hope) reasonable refactoring. I did all in separate commits to make the review easier.
=> andark: Restore redraw on charging and small fixups

apps/mylocation/interface.html
[Link to app](https://thinkpoop.github.io/BangleApps/?id=mylocation)
The map (leaflet.js) uses "lng" for longitude, while the MyLocation.json uses "lon". When re-loading the lat/lon from JSON, the original code wasn't mapping "lon" to "lng".
To recreate using BangleJS.com/apps version: 
1. Open the interface, add a marker, and click save.
2. Re-open the interface and click save without clicking on the map.
3. MyLocation.json will have an undefined longitude; quick test is just re-open the interface again and it'll give an error in the console about it.
Adding a "Locate" button to center on your current location and a "Find" button to center on your marker's location.
What the Locate button looks like before setting a marker
What both buttons look like after setting a marker
=> [mylocation] fix missing lon; add locate & find-marker buttons

apps/taglaunch/ChangeLog, apps/taglaunch/README.md, apps/taglaunch/app.js, apps/taglaunch/metadata.json
If an app has no tags (e.g. [Drained](https://banglejs.com/apps/?id=drained&readme), in my case), it caused taglauncher to crash because of a missing check (and in turn running .split on undefined). This missing check was added and apps without the tag are now added to the Misc category automatically.
I also fixed some code indentation issues.
Real changes to app.js only from lines 51-61 in the old app.js (or ll. 75-90 in the new app.js).
=> Fixed taglauncher crashing with certain apps installed

apps/spotrem/ChangeLog, apps/spotrem/app.js, apps/spotrem/metadata.json
NOT TO BE MERGED (at least initially)
This conforms to the changes to setUI here: https://github.com/espruino/Espruino/pull/2526
=> spotrem: refactor to handle ui all inside setUI

apps/bwclk/ChangeLog, apps/bwclk/app.js, apps/bwclk/metadata.json, apps/bwclklite/ChangeLog, apps/bwclklite/app.js, apps/bwclklite/metadata.json
This modifies how the time string is generated so it respects the system's locale settings, specifically for 12-hour time.  This is done with the locale package, which also simplifies some of the string handling since the package creates a complete time string.  Note this does not add any display of AM/PM, but neither do any other clock faces.
=> bwclk & bwclklite: Support 12-hour time format.

apps/calendar/ChangeLog, apps/calendar/calendar.js, apps/calendar/metadata.json
This is a partial fix for feature request #3707.  This allows synchronized events (stored in "android.calendar.json") to be shown in the app, alongside the manually entered events and alarm events that are already shown.
This is a sort of minimum viable implementation of the feature request, as it does not address most of what @nxdefiant and I discussed.  I hope we can work toward those in the future.  Specifically:
- The file "calendar.days.json" is still read from and written to when creating events in the app.
- All events from "android.calendar.json" are assumed to not be holidays, just regular events.
- No UI is added to expose the extra information available in the synchronized events (e.g. duration, description).
=> calendar: read events synchronized from Gadgetbridge

apps/calendar/ChangeLog, apps/calendar/calendar.js, apps/calendar/metadata.json
Discovered that, in the events synchronized from Gadgetbridge, all-day events have timestamps that disregard local timezones.  Specifically, all-day events always start at midnight UTC, which caused calendar to display them starting at a different time depending on time zone offset (e.g. for my offset of -5, I see all-day events start at 19:00 the day before).  Borrowed [logic from the agenda app](https://github.com/espruino/BangleApps/blob/c51785467c006b5521def8985b0602e013719653/apps/agenda/agenda.js#L33-L39) to correct this.  This logic shifts an all-day event's start time to start at midnight in the current time zone.
Also specify all-day events as type "o" (other) so the full day is highlighted and the start time is not displayed.
Note that this does nothing to handle all-day events …
=> calendar: properly display synced all-day events.

apps/batterybooster/Changelog, apps/cutelauncher/Changelog, apps/onewordclock/Changelog
This was causing problems while trying to clone the repository: https://github.com/espruino/BangleApps/commit/38bce756a2c33820abc44bd0f6902a40a9becd33#diff-d24e4cc8e51380b4b47f84875bfed211ad8fa2c92e96bfaf5985a4d7d2fbd734
=> cleanup removing wrongly named "Changelog" for three apps

apps/agenda/ChangeLog, apps/agenda/agenda.js, apps/agenda/metadata.json
This fixes a bug where the "Today" and "Tomorrow" labels display on future weeks due to matching on day of the week instead of date, e.g. if today is Thursday an event on Thursday next week will be labelled "Today".
=> agenda: Fixed bug where "Today" and "Tomorrow" labels display in non-current weeks.

apps/promenu/ChangeLog, apps/promenu/bootb2.js, apps/promenu/bootb2.ts, apps/promenu/metadata.json, typescript/types/bangle_extensions.d.ts
promenu declares and uses a global variable, `settings`. This is common in apps such as `settings` and `alarms`, which will come along and overwrite said variable.
This has the effect of all settings in promenu being falsy (unless a setting name overlaps with one from bangle settings). Renaming the variable resolve this problem.
=> promenu: fix settings overwriting

apps/launch/ChangeLog, apps/launch/app.js, apps/launch/metadata.json, apps/launch/settings.js
0.24: Fix fullscreen when fastloading the launcher. (TODO:fix back btn flicker)
Fix respecting the showClocks setting.
Try it via my app loader: https://thyttan.github.io/BangleApps/?id=launch
closes #3786 and #3785
@gfwilliams because it is a core app.
=> launch: fix fullscreen and showClocks setting

apps/noteify/ChangeLog, apps/noteify/README.md, apps/noteify/clkinfo.js, apps/noteify/metadata.json
This adds a clock info list for Noteify, with each note as an entry in that list.  This gives a way for a user to put a note directly on any clock with a clock info area.  Loosely inspired by the scratchpad of the Advanced Casio Clock (advcasio).
Tested on my Bangle2 on multiple clocks (bwclk 0.34, circlesclock 0.26, slopeclockpp 0.11, lcdclock 0.07, lcdclockplus 0.03, lato 0.04) with zero notes, one note, and multiple notes.  Notes don't always show up well on all clocks, depending on line count and line length.  This code does not attempt to shorten the notes to display better because the clocks are all so different in how they display the text.
=> noteify: make notes available to clock info.

apps/agenda/ChangeLog, apps/agenda/agenda.clkinfo.js, apps/agenda/metadata.json
All-day events synchronized from Gadgetbridge always start at midnight UTC, which causes them to display as different days depending on time zone offset (specifically negative offsets display the date as one day early).  This was previously fixed in the agenda app in pull request #3695 (commit bcf88c3). This commit replicates that fix in the clockinfo that agenda provides.
Tested this on my Bangle2 with time zone offsets that are negative, positive, and zero.
=> agenda: fix all-day event offsets in clock info.

apps/pace/ChangeLog, apps/pace/app.js, apps/pace/app.ts, apps/pace/metadata.json
=> pace: handle GPS skew, allow reset of time/splits

apps/runplus/ChangeLog, apps/runplus/app.js, apps/runplus/metadata.json
Only redraw layout if we might've shown a setRecording prompt
=> runplus: optimise UI rendering

apps/edgeclk/ChangeLog, apps/edgeclk/app.js, apps/edgeclk/metadata.json
Helps in some situations if using fastload utils where the graphics from the previous app would not be cleared.
What triggered the issue for me was:
1. Use fasload utils
2. have a message notification pending showing with `widmsggrid`
3. exit `spotrem` by clicking the HW button on the main ui.
4. edgeclk is displayed but the `spotrem` graphics are showing behind the clock graphics.
I didn't figure out what exactly caused it, but maybe somehow the theme bg color ended up transparent or not set for the `g.clear()` call. This change seems to fix it. But don't know if we should be looking to fix something somewhere else.
=> edgeclk: Reset graphics before initial clearing of the screen.

apps/jsonclock/ChangeLog, apps/jsonclock/app.js, apps/jsonclock/metadata.json
After a week of daily-wearing the JsonClock, the only issue seen was the commas being drawn incorrectly.
This PR repairs that.
=> Fixed comma drawing on JsonClock

apps/folderlaunch/app.ts, apps/promenu/ChangeLog, apps/promenu/bootb2.js, apps/promenu/bootb2.ts, apps/promenu/metadata.json, typescript/types/main.d.ts
See #3804 and:
- https://github.com/espruino/BangleApps/pull/3604
- https://github.com/espruino/Espruino/pull/2565
- https://github.com/espruino/BangleApps/pull/3609
- https://github.com/espruino/Espruino/pull/2569
Also update types in folderlaunch (no need for new version)
=> promenu: forward on touch event

apps/bwclk/ChangeLog, apps/bwclk/app.js, apps/bwclk/metadata.json
Previously, all text in a clock info entry was centered.  This caused long lines to spill off both sides of the screen, and entries with more than two lines to cover the time.  With this change, clock info text is arranged so it only ever spills off the right and bottom. This allows the start of any text to always be visible, and the time to never be covered, regardless of the amount of text.  To achieve this, multiple lines are now left-aligned instead of center-aligned.
This fixes some of my own issues, but I am open to feedback on this because it might not be the best way to handle arbitrary clock info text.  Also, I have not copied this over to bwclklite yet, but I can do that after everyone is happy with the change.
Here are comparative screenshots for reference.
One long line …
=> bwclk: Adjust clkinfo positions for long text.

apps/bwclklite/ChangeLog, apps/bwclklite/app.js, apps/bwclklite/metadata.json
This copies changes from bwclk into bwclklite.  For reference, see PR #3845 and commits 83bedcd and 04f3475.
Previously, all text in a clock info entry was centered.  This caused long lines to spill off both sides of the screen, and entries with more than two lines to cover the time.  With this change, clock info text is arranged so it only ever spills off the right and bottom. This allows the start of any text to always be visible, and the time to never be covered, regardless of the amount of text.  To achieve this, multiple lines are now left-aligned instead of center-aligned, and single lines are wrapped.
Here's a screenshot showing one before-and-after, example, but see PR #3845 for more thorough comparisons with bwclk.
| bwclklite 0.35 | this PR |
|--------|-------|
| …
=> bwclklite: Adjust clkinfo positions for long text.

apps/contacts/README.md
It took me a `logcat` to realise that this was the reason the contacts apps wouldn't call. Ideally it would be nice if it displayed the error message on the phone or watch, but in the meantime, mentioning it in the README is an improvement IMHO.
=> docs(contacts): mention GadgetBridge intents requirements

apps/chess/ChangeLog, apps/chess/app.js, apps/chess/metadata.json
With falling edge and current firmware menu will always reopen on close.
=> Chess: Use button rising edge for Menu

apps/crsclock/README.md, apps/crsclock/crsclock.js
This single PR addresses two separate issues:
Bugfix: Non-ASCII punctuation in crsclock.js
Installing via the Development App Loader produced parsing errors and garbled text, whereas uploading via Web IDE did not. After investigation, non-ASCII dashes in the source were being mangled by the Espruino minifier/firmware, causing:
Syntax error:
Uncaught SyntaxError: Got UNFINISHED REGEX expected ']'
(due to U+2212 MINUS SIGN in BT calibration menu, ≈ lines 612–614)
Mojibake:
EN DASH (U+2013) in the sleep-window and range prompts rendered as â on device (lines 84–86, 714 & 723)
Fix: Normalise all EN DASH and MINUS SIGN characters to the ASCII hyphen-minus (-).
Documentation: Patent & Licensing clarity in README.md
To reinforce transparency around our UK-patented method while preserving …
=> Replace non-ASCII dashes in code & clarify patent/licensing terms for non-commercial use in README

apps/crsclock/crsclock.js
This pull request addresses an issue where non-ASCII punctuation (specifically EN DASH U+2013 and MINUS SIGN U+2212) in crsclock.js caused runtime errors and display corruption when the app was installed via the Development App Loader.
=> Removing non-ASCII characters

apps/weather/ChangeLog, apps/weather/app.js, apps/weather/metadata.json
This uses the already available UV index data from weather updates and displays it centered below the icon where there was available space. 
This was in regards to discussion [7791](https://github.com/orgs/espruino/discussions/7791).
=> weather: Add UV index display

apps/weather/ChangeLog, apps/weather/README.md, apps/weather/app.js, apps/weather/metadata.json
Separated the UV index display from the icon container as it made the icons smaller and interfered with the lazy rendering so that it wouldn't clear properly when drawing a new icon. It's now positioned under the wind speed and hides when the UV index is 0.
I also added "haze" in the BangleDumpWeather shortcut that maps to weather code "741" along with mist and fog and "shower" that maps to code "521" that was previously not used by the shortcut. I put the new link in the README. There is still one icon that this shortcut is not utilizing yet called drawBrokenClouds when it's in the 800's but not 800, 801, or 802. Any ideas of what we could filter for to show that? We already have "wind" and "part" map to "801" for drawFewClouds, and "cloud" maps to "802" for drawCloud. …
=> weather 0.28: Fix UV positioning, hide when 0

apps/widalarmeta/ChangeLog, apps/widalarmeta/metadata.json, apps/widalarmeta/widget.js
I have this widget set to show seconds only while unlocked, but before this change it wouldn't redraw the widget to show seconds when the display wakes up.
I've been testing it for the past few weeks.
=> [widalarmeta] Add listeners to draw when unlocked

apps/crsclock/crsclock.js
This PR addresses two critical bugs that occur only when installing the app via the development App Loader (they do not appear when uploading the script directly through the Web IDE):
Malformed regex / syntax error
Cause: The source uses the Unicode minus sign (U+2212) in the BT calibration menu, which the Espruino minifier mis-parses and embeds into crsclock.app.js as an unfinished regex.
Symptom:
Uncaught SyntaxError: Got UNFINISHED REGEX expected ']'
Location: crsclock.js ≈ lines 612–614.
Garbled on-device text
Cause: Use of the EN DASH (U+2013) in prompt strings for the sleep window and range selections.
Symptom: Dash characters render as â (mojibake) on Bangle.js.
Locations:
Sleep window label (lines 84–86)
Range prompts (lines 714 & 723)
All non-ASCII dashes have been normalised to …
=> Replace non-ASCII dashes with ASCII hyphens to fix loader parsing and display issues

apps/twenties/ChangeLog, apps/twenties/README.md, apps/twenties/boot.js, apps/twenties/metadata.json
This PR refactors the buzzing functionality in the `twenties` app to enhance energy efficiency:
**Key Improvements:**
- Simplifies and consolidates the logic determining active work hours (Mon–Fri, 8 am–6 pm).
- Optimizes scheduling to avoid unnecessary checks outside working hours, significantly improving battery performance.
- Renames variables for clearer readability (`isWorkTime`, `LOOP_INTERVAL`, `BUZZ_INTERVAL`).
=> `twenties`: improve energy efficiency and simplify scheduling logic

apps/bbreaker/ChangeLog, apps/bbreaker/README.md, apps/bbreaker/app.js, apps/bbreaker/metadata.json
Now it looks better, playable and tested on my BangleJS (found it!)
=> Fixed some part of the flickering and the position of the HUD

apps/wid_a_battery_widget/ChangeLog, apps/wid_a_battery_widget/metadata.json, apps/wid_a_battery_widget/widget.js
Rather than defaulting to black or white, this uses the background and foreground colors that the rest of the bangle uses, for greater cohesion with users’ themes.
=> [A Battery Widget] Background color matches Bangle’s theme

apps/promenu/ChangeLog, apps/promenu/bootb2.js, apps/promenu/bootb2.ts, apps/promenu/metadata.json
See https://github.com/orgs/espruino/discussions/7697#discussioncomment-13782299 and espruino/Espruino#2648
Tested - bug is gone on 2v27 with this workaround
=> promenu: workaround `setUI` touch handler bug (2v26/2v27)

apps/recorder/README.md, apps/recorder/interface.html
Features Added
- Interactive maps: Click any GPS point to see detailed data
- Data charts: 6 chart types (HR, battery, steps, elevation, speed, barometer) with PNG export
UI Changes
- Card layout → Accordion with lazy loading
- Added track stats (distance, duration)
This can be tested at https://stweedo.github.io/BangleApps/?id=recorder
=> recorder: Add interactive maps with clickable track points and data charts

apps/ios/README.md
I noticed that the shortcut for BangleDumpWeather was the outdated one that still uses the OpenWeather API. This PR changes it to the new shortcut created by me and @stweedo using Apple weather in the readme.
=> [iOS] Readme updates

apps/widalarmeta/ChangeLog, apps/widalarmeta/metadata.json, apps/widalarmeta/settings.js, apps/widalarmeta/widget.js
Link: https://thinkpoop.github.io/BangleApps/?id=widalarmeta
Adds an option to the Alarm ETA widget to only show when on the clock face.
I started using a widget to show the time when not on a clock. This way I see the alarm ETA when on the clock and the current time when not on the clock.
=> [widalarmeta] Add option to only show when on clock

apps/antonclk/ChangeLog, apps/antonclk/app.js, apps/antonclk/metadata.json, apps/antonclkplus/ChangeLog, apps/antonclkplus/app.js, apps/antonclkplus/metadata.json, apps/slopeclockpp/ChangeLog, apps/slopeclockpp/app.js, apps/slopeclockpp/metadata.json
To allow other apps/bootcode to redraw without a reload
=> anton/slope clocks: pass `redraw` to allow `Bangle.uiRedraw()`

apps/fwupdate/custom.html
Hi! I noticed this was preventing the fwupdate app from actually downloading and installing firmware updates on my watches, because the accidental dangling apostrophe in the URL for each firmware entry both would cause a 404, but also prevents the `downloadURL` function from passing because it expects the URL to end with `.zip` or `.hex`.
=> fix: Erroneous apostrophe preventing firmware updates

apps/mtnclock/ChangeLog, apps/mtnclock/app.js, apps/mtnclock/metadata.json
Because the Mountain Pass Clock app reacts to the weather events directly, it breaks when the Weather app requires weather data v2. The clock reads the fields that are not in v2 data, and this sets the temperature to "undefined".
To not add mandatory dependency of Weather app, I have added both options. React to Weather app update if it's installed and use old (but fixed) way if the app is not installed.
=> Fix mntclock for weather v2 data

apps/smartbatt/ChangeLog, apps/smartbatt/README.md, apps/smartbatt/metadata.json, apps/smartbatt/module.js
This just returns more in the exports.get() function, and has updated documentation along with it. Because the most recent update (maybe a day ago) is not yet deployed to the app loader, should I change the version for this one as well?
=> [Smart Battery Module] API changes
