- apps/settings.js
It's very rudimentary, but it works.
> Settings menu for manually setting the time/date

- apps.json
- apps/miclock/clock-mixed.js
- apps/sbat/widget-battery.js
- apps/sclock/clock-simple.js
- apps/wclock/clock-word.js
fix simple clock tags
add  drawWidgets()
add color to battery widget
> some small fixes

- apps/gpsinfo/gps-info.js
Some tweaks to the GPS info app:
- Speed is shown on the screen
- "Animation" on the "Waiting for GPS" screen
- With 10px padding feels a bit nicer :)
> GPS needs more speed!

- apps.json
- apps/gbridge/Changelog
- apps/gbridge/widget.js
It was quite difficult to read small text with contrast of #b0b0b0 text on #404040 background.
> ✨ gbridge: increase contrast

- package.json
Helps to speed up development without having to rely on GitHub pages.
> Added npm task to run locally

- apps/locale/locales.js
Adding tr_TR language to locale app
> Adding tr_TR language

- apps/gbridge/Changelog
This file is duplicate of apps/gbridge/ChangeLog file
> Deleting duplicate Changelog file

- apps/locale/locales.js
correct syntax error on spanish locales
> Syntax error

- index.js
Hi !
I was tired of clicking on the tag after a refresh of the page.
I decided to put the tag in the url.
Let me know if this need any modification
> Auto activeFilter using url

- index.js
Added a check to validate the tag from the url, fallback to "all"
Fix the behavior when click on all
Sorry again for that double PR
> Fix autoFilter behavior

- apps/boot/bootloader.js
Add an event on BTN2 to open launcher when no clock detected
See #147
> Fixing issue #147

- apps.json
- apps/swatch/ChangeLog
- apps/swatch/stopwatch.js
- made lap logs count up from 1
- made it such that logs scroll to next column after 18th entry
- can now display 36 entries without going off-screen
> Update of lap log feature stopwatch app 

- apps/locale/locales.js
> Wrong long date pattern for HU locale

- apps.json
- apps/aclock/ChangeLog
- apps/aclock/clock-analog.js
Refactored analog clock to get my feet wet with Bangle.js and Espruino:
- simplify timers to a single second timer
- fix draw widgets order of call 
- make seconds ticks more readable
- add elapsed seconds display
- add date
> Analog clock updates

- apps/gbridge/PROTOCOL.md
This shows currently possible commands and events
> Documents gadgetbrigde protocol

- apps.json
- apps/barclock/ChangeLog
- apps/barclock/clock-bar.js
1. Fix date screen area not being cleared at midnight
2. Code cleanup
> Barclock fix and cleanup

- apps/miclock/clock-mixed.js
just found one app using local.lang
> switch_to_local_name

- apps.json
- apps/marioclock/ChangeLog
- apps/marioclock/marioclock-app.js
Use user setting of a 12 or 24 hour clock  when rendering the time in MarioClock
> MarioClock [Bug Fix] - 12/24hr setting to be respected

- apps.json
- apps/toucher/ChangeLog
- apps/toucher/app.js
The lcd stay on because of the load function.
I don't have workaround yet
> Improvement: Close launcher when lcd turn off

- apps.json
- apps/aclock/ChangeLog
- apps/aclock/clock-analog.js
> Analog Clock (aclock) fixes for widget area

- apps.json
- apps/toucher/ChangeLog
- apps/toucher/app.js
Rewrite and add asked feature  on issue #210 
Not sure about the perf, i didn't tried lcd mode 80x80 though;
> Rewrite and add asked feature  on issue #210

- apps.json
- apps/marioclock/ChangeLog
- apps/marioclock/marioclock-app.js
* You can now `SWIPE-RIGHT` to toggle the character between `Mario` and `Toad`! (On a loop)
* You can now `SWIPE-LEFT` to toggle `DAY/NIGHT MODE` (The clock was burning my eyes out at night) (On a loop)
* Trees no longer high as clouds (didn't quite look right)
* Minor performance enhancements
> Mario Clock [Enhancement] - Multi characters and Night Mode

- apps.json
- apps/gpsinfo/ChangeLog
- apps/gpsinfo/gps-info.js
Shows number of satellites while waiting for GPS fix like Speedo app does
> GPS Info: Show number of satellites while waiting for fix

- apps.json
- apps/toucher/ChangeLog
- apps/toucher/app.js
I once again followed your tips ( #210 )
> Toucher - Improve the rendering performance

- apps.json
- apps/widpedom/ChangeLog
- apps/widpedom/settings.js
- apps/widpedom/widget.js
Fix #250 
Draws progress as part of a circle
(default goal: 10.000 seems to be common-ish?)
> widpedom: Add goal setting

- apps.json
- apps/widpedom/ChangeLog
- apps/widpedom/settings.js
- apps/widpedom/widget.js
Looks like it actually didn't work at all, no idea how I managed to convince myself that it did :-(
> widpedom: Fix daily goal, don't store settings in separate file

- apps/locale/locales.js
I've added `ampm` missing property in some locales (it_CH, it_IT, wae_CH), cause of following problem that make impossible to update Bangle's locale.
> Fixed missing ampm property for some locales

- CHANGELOG.md
- index.html
- js/index.js
- js/ui.js
- js/utils.js
* library select/unselect apps/widgets
* as library  section
* as upload
* deny unselect  for boot and setting
> add favourite functionality

- apps.json
- apps/snake/ChangeLog
- apps/snake/README.md
- apps/snake/snake.js
I fixed screen flickering passing to 120x120 LCD mode, added game pause and improved the graphic.
I've also improved the code under the hood.
> Improvements of snake game

- apps.json
- apps/chronowid/ChangeLog
- apps/chronowid/README.md
- apps/chronowid/app.js
- apps/chronowid/widget.js
0.02: Setting to reset values, timer buzzes at 00:00 and not later (see readme)
> Chrono Widget 0.02

- apps.json
Changelog is already at version 0.07, last update forgot to bump `apps.json`
> wohrm: fix `apps.json` version

- apps.json
- apps/files/ChangeLog
- apps/files/files.js
Gives users a choice to erase app files, data, or both.
> App Manager: Add support for data files

- apps.json
- apps/calculator/ChangeLog
- apps/calculator/README.md
- apps/calculator/app.js
- apps/calculator/tests.html
- Javascript rounded float issues
- Reset after equals wasn't done properly
- Introduce unit tests 🤗
> Fix App Calculator issues

- apps.json
- apps/activepedom/ChangeLog
- apps/activepedom/README.md
- apps/activepedom/app.js
- apps/activepedom/widget.js
- apps/chronowid/ChangeLog
- apps/chronowid/widget.js
Active Pedometer:
- The graph module is now part of the source code.
- I implemented data logging to file and an app to view data as graph
Chrono Widget:
- Display only minutes:seconds (00:00) when less than 1 hour is left on timer
> Active Pedometer 0.03 / Chrono Widget 0.03

- apps.json
Add a reference to the existing README.md file for gpsnav so that it can be read in the app loader - a nice feature that I have just become aware of.
> Update apps.json entry for gpsnav

- apps.json
- apps/toucher/ChangeLog
- apps/toucher/app.js
- apps/toucher/settings.js
A week or two too late, sorry for those who waited.
> Toucher : Complete rewrite in 80x80, better perf, add settings

- apps.json
- apps/pong/ChangeLog
- apps/pong/README.md
- apps/pong/app.js
Fixes:
- sometimes the AI would be stuck in a loosing scheme, now its not but I hope the new AI won't be too difficult, it's possible to win but hard 🗡️ 
- sometimes the ball would bounce into a paddle instead of bouncing on to it, it should be fixed
Change/New:
- The "down" button is now BTN2 instead of BTN3, it was annoying to quit the game if we pressed BTN3 too long
- a screen that tells these buttons are inverted is shown when the game starts
- there is now a timer before the ball is thrown the first time (I don't know if it is of use, let's say it's convenient)
- 2 player mode over local (I know it's hard to play over one watch but why not ahahah)
> Pong app - improve ai, add 2 player local

- apps.json
- apps/hidcam/ChangeLog
- apps/hidcam/README.md
No changes in code, only enhancements for usability in app loader : added keywords and a read more
> keywords and readme update

- apps.json
- apps/impwclock/ChangeLog
- apps/impwclock/clock-impword.js
This could also be used to stop https://github.com/espruino/BangleApps/tree/master/apps/wclock from flashing every interval.
> Stop impwclock from flashing every interval

- apps/files/files.js
Added sub-menu to "App Manager" app to sort apps:
- alphabetically ascending (by name)
- alphabetically descending (by name)
- manually
Since I think there might be "LOW MEMORY" issues when sorting manually very fast or when sorting asc/desc in rapid succession and then sorting manually, any suggestions, especially concerning these memory problems, are welcome!
> App Manager: Add app sorting functionality

- apps/files/ChangeLog
- apps/files/files.js
@gfwilliams I've updated the app by your suggestion, here's the pull request. Thanks again!
> App Manager Sorting: use less memory

- apps.json
- apps/qrcode/ChangeLog
- apps/qrcode/custom.html
Related [issue](https://github.com/espruino/BangleApps/issues/393)
You can preview [here](https://v1nc.github.io/BangleApps/)
> Add wifi QR code generation

- apps/locale/locales.js
We're pretty inconsistent when it comes to units here, but we are
theoretically a metric nation.
> Update en_CA locale units

- apps.json
- apps/batchart/ChangeLog
- apps/batchart/widget.js
Remove widget icon and improve listener and setInterval handling for widget (might help with https://github.com/espruino/BangleApps/issues/381)
> BatteryChart 0.10

- apps/files/files.js
Just changed from write to writeJSON as per recommendation for now.
> Switch from writeJSON to write to possibly mitigate memory leak in writeJSON

- apps.json
- apps/gpsnav/ChangeLog
- apps/gpsnav/README.md
- apps/gpsnav/app.js
- apps/gpsnav/waypoints.html
- apps/gpsnav/waypoints.json
This version has a waypoint editor that uses the interface mechanism. Consequently, it is invoked by clicking on the download data icon from app icon in the app loader. This is a little misleading as the waypoint editor both downloads and then updates the edited waypoints.json data to the Bangle.
> Update gpsnav app to 0.03 with waypoint editor

- .gitignore
Add .vscode folder to gitignore to allow for customized editor settings
> chore: ignore .vscode folder

- apps/locale/locales.js
Change thousands separator and modify the speed unit
> Update French locales

- apps.json
- apps/widviz/ChangeLog
- apps/widviz/widget.js
Many thanks for the suggestion Gordon.
It no longer needs the setup interface and the operation is much more intuitive.
> Update of widviz to use swipe rather than buttons. 

- js/index.js
Add a link to the github page for apps in the My Apps tab
This exists in the library tab, but not in My Apps.
Found it convenient to have the link there too.
Also boyscouted and fixed indening a bit
> Add github link to My Apps

- apps/imgclock/app.js
Flash the : separator; even seconds off, odd seconds on
> Make : between hours and minutes flash

- apps/locale/locale.html
Feel free to merge or cherry pick.
> locale fixes + memory

- apps.json
- apps/metronome/ChangeLog
- apps/metronome/metronome.js
In combination with some widgets, the position of the bmp string was wrong on my watch. I fixed it.
> Fix position

- apps/locale/locales.js
local "en_AU" had some incorrect values, Australia is fully metric, and date is %d/%m/%y.
> en_AU updated to values metric and corrected date

- apps/locale/locales.js
> back translation

- apps.json
- apps/banglerun/ChangeLog
- apps/banglerun/app.js
Missing modulo 60 caused the minutes not to reset when hitting 60
> banglerun fix timer

- apps/locale/locale.html
- small number rouding to 1 dec. point
- number format
- dow, month single var
> locale improvements

- apps.json
- apps/weather/ChangeLog
- apps/weather/app.js
- apps/weather/lib.js
Fixes https://github.com/espruino/BangleApps/issues/483
> Weather: Fix flickering last updated time

- apps/boot/bootloader.js
Haven't done benchmarks, how internally Espruino works.
> load only clock apps

- apps.json
- apps/largeclock/ChangeLog
- apps/largeclock/largeclock.js
Tweak the layout to work better with the new vector font, and add support for 12 hour time.
> Largeclock changes

- apps.json
- apps/gbridge/ChangeLog
- apps/gbridge/sample_messages.js
- apps/gbridge/widget.js
- apps/notify/ChangeLog
- apps/notify/README.md
- apps/notify/notify.js
- apps/notifyfs/ChangeLog
- apps/notifyfs/notify.js
Fixes #527 
(Having so much duplicate code in both `notify` and `notifyjs` really bugs me, but I guess it can't be helped.)
> Notify api

- apps.json
- apps/marioclock/ChangeLog
- apps/marioclock/marioclock-app.js
Add jumping sprites for all characters
> Update MarioClock - Jumping sprites

- apps.json
- apps/viewstl/ChangeLog
- apps/viewstl/README.md
- apps/viewstl/viewstl.app.js
- apps/viewstl/viewstl.min.js
Add a third rotation mode: rotation follows accelerometer and magnetometer readings.
> Add accelerometer/magnetometer rotation mode

- apps.json
- apps/minionclk/ChangeLog
- apps/minionclk/app.js
Clearing the screen on startDrawing(), to the date string on the bottom of the screen. This is currently not happening, unless the display is turned on at midnight.
> minionclk v0.04

- apps.json
- apps/cscsensor/ChangeLog
- apps/cscsensor/cscsensor.app.js
Added a graphical indicator for the sensor battery. 
More robust tracking of moving time. 
Correct saving of total distance traveled on exit and reset.
Reconnect on sensor disconnect.
> Add sensor battery indicator, small bugfixes

- apps.json
- apps/rpgdice/ChangeLog
- apps/rpgdice/app.js
Changed text colour to grey while bouncing, changing to white on final bounce except for critical rolls. Critical hit is red text on black, critical miss is black text on red.
> Cosmetic changes to rpgdice 

- apps/smtswch/README.md
> Improve readibility to README.md

- apps/activepedom/ChangeLog
- apps/activepedom/widget.js
A getter so that other Apps can access todays step count.
> 0.06: Added WIDGETS.activepedom.getSteps()

- apps.json
- apps/gpsservice/ChangeLog.txt
- apps/gpsservice/README.md
- apps/gpsservice/test-bed.js
- apps/gpsservice/widget.js
added gps_get|set_settings, restore to SuperE setup on poweroff(), updated README
bumped version number
added change log
> added gps_get|set_settings, restore to SuperE setup on poweroff()

- apps.json
- apps/lazyclock/ChangeLog
- apps/lazyclock/lazyclock-app.js
- Fix bug with times between 12:30 and 13:00
- Tweak phrases
- Only update on threshold change, not every minute
> feat(app): Update "Lazy Clock" app to v0.02

- apps.json
- apps/heart/ChangeLog
- apps/heart/app.js
* added graphing of latest 164 measurements of chosen record file
* graphing code is based on batchart
Signed-off-by: Andrwe Lord Weber <github@andrwe.org>
> added graphing for Heart Rate Recorder

- apps/locale/locales.js
Just adds a new pt_PT locale.
Tested it on my Bangle.js and seems to work just as expected. =-)
PS - Thank you for all your work on Bangle.js. I may not be a very active community member, but your work is highly appreciated.
> Adds pt_PT locale

- apps.json
- apps/heart/ChangeLog
- apps/heart/app.js
* Add loading screen for viewRecord
* List average, minimum & maximum measurement in viewRecord
* Disable recording only when current recording file is erased
* Fix timezone offset
* Draw chart based on height and width of display instead of hard-coded limits
* Reduce memory usage by ~30%
* Generate scale based on defined minimum and maximum measurement
* Added background line on 50% to ease estimation of drawn values
> [Heart] many improvements

- apps.json
- apps/trex/ChangeLog
- apps/trex/settings.js
- apps/trex/trex.js
Hi there!
I really like this little game and added a highscore feature. I also enabled the move forward and backward buttons.
Highscore can be reset in app settings -> T-Rex. One little detail that I did not get to work is to show the T-Rex menu after reset, not going back (line 12 in settings.js -> what to put there to show the submenu?)
Any comments are welcome.
Kind regards,
neshanjo
> T-Rex: Made x movements work and added highscore

- apps.json
- apps/hourstrike/ChangeLog
- apps/hourstrike/app.js
- apps/hourstrike/boot.js
- apps/hourstrike/hourstrike.json
- apps/largeclock/ChangeLog
- apps/largeclock/README.md
- apps/largeclock/largeclock.js
- apps/largeclock/largeclock.json
- apps/largeclock/settings.js
This pull request fixes the file-not-found bug in the app Hourstrike.
> Bug fix for Hourstrike; New feature for Large Clock

- apps.json
- apps/choozi/README.md
As suggested in #806, I've added a README.
I didn't know this was possible, else I'd have done it the first time :).
> Add README to Choozi

- modules/Layout.js
- modules/Layout.min.js
Demo here: https://www.espruino.com/ide/?gist=cc5f26ad897ecaa531b698781d47964a
The overhead of the lazy rendering logic seems overall comparable to the amount of time it saves by not re-rendering things. In the demo most of the time is spent calling `layout.update()`.
The one thing this change doesn't currently handle is background colors on "h" or "v" layoutObjects. Those are kind of tricky, since their children are drawn on top of them.
> Add lazy rendering support to Layout

- apps.json
- apps/weather/ChangeLog
- apps/weather/app.js
- apps/weather/lib.js
- apps/weather/widget.js
This should reduce the memory usage of the ram widget by up to 70
JSVars, depending on the weather.
> Weather: refactoring and reduced ram usage

- apps.json
- apps/cscsensor/ChangeLog
- apps/cscsensor/README.md
- apps/cscsensor/cscsensor.app.js
add support for cadence sensor
> CSC sensor app

- apps.json
- apps/multiclock/ChangeLog
- apps/multiclock/multiclock.app.js
Stupid bug where minute tick only ticked once - not easy to spot on Bangle but obvious on Bangle 2!
> fix minute tick bug in multiclock

- apps/ffcniftya/app.js
- apps/ffcniftyb/app.js
Small fix where the day of the week is display instead of day of the month.
> Fixed wrong day being displayed in nifty clocks

- apps.json
- apps/pomodo/CHANGELOG.md
- apps/pomodo/ChangeLog
- apps/pomodo/pomodoro.js
Made the pomodo app work on Banglejs2 in addition to Banglejs1.
> Port pomodo to Banglejs2

- apps.json
- apps/chargeanim/ChangeLog
- apps/chargeanim/app.js
Update chargeanim to make it compatible with Bangle.js 2.
> chargeanim Bangle.js 2 compatibility

- apps.json
- apps/antonclk/ChangeLog
- apps/antonclk/app.js
Added simple day of week text under date for quick, access to this information.
> add day of week to anton clock

- apps/messages/app.js
Tiny change for telegram
Original below:
> messages: add telegram icon

- apps.json
- apps/health/ChangeLog
- apps/health/app.js
- apps/toucher/settings.js
And Toucher: Debugging default = false
> Health, supress bleed through of Showmenus when displaying barcharts

- README.md
- bin/sanitycheck.js
- modules/Settings.js
Something like this would be useful, as mentioned in http://forum.espruino.com/conversations/369160/#16245740
This works, but some issues/bikeshedding before merging:
- Maybe remove (some of) the error checks to make it lighter. I really don't know how much that would improve Things, as I think most of this would just be executed from Flash anyway? But it seems a bit much compared to most of the other code...
- To get at global settings, you need to pass the `Bangle` object as app, we could pick some other value (or just anything falsey)
- There's probably room for some optimization before pushing this out for widespread use.
- I figured that for malformed JSON, throwing the error would be more informative than just returning the default value, as someone should probably take a look at …
> create Settings library

- apps.json
- apps/gbmusic/ChangeLog
- apps/gbmusic/app.js
> gbmusic: fix "previous" button image

- apps/schoolCalendar/boot.js
- apps/schoolCalendar/custom.html
Fixed a bug after the wrong files were merged.
> Fix School Calendar Bug 

- apps.json
- apps/slevel/ChangeLog
- apps/slevel/spiritlevel.js
A very small update to the Spirit Level app to make it usable on the Bangle.js 2.
> Update Spirit Level to work on Bangle.js 2

- apps.json
- apps/thermom/ChangeLog
- apps/thermom/app.js
What changed?
- Add degree Celsius sign after temperature value (°C)
- Made loading message more clear what actually happens ("Reading temperature")
> Update degree Celsius temperature app

- apps.json
- apps/gpsrec/ChangeLog
- apps/gpsrec/app.js
- apps/recorder/ChangeLog
- apps/recorder/app.js
Hi,
I don't know what the etiquette is around modifying apps authored by other people. In any case, I have noticed a few bugs in the recorder apps:
1. The label for the back button and the total distance label were put into fixed positions, designed for the Bangle.js 1
2. The X axis label (there was only one!) was odd and misaligned
3. In Recorder, the speed and altitude plotting tools didn't handle missing coordinates (this doesn't affect GPS recorder, as that one doesn't log records for situations where a GPS fix is not available) (Incidentally, I think the graph library should handle `NaN`s better)
> Assorted bugfixes to the recorder apps

- css/main.css
- index.html
This PR makes some minor CSS tweaks to the App Loader. Let me know if you think this feels like an improvement.
**Before:**
**After:**
> Tweak styling to give a more aligned and spaced out layout

- apps.json
- apps/authentiwatch/ChangeLog
- apps/authentiwatch/app.js
- apps/authentiwatch/interface.html
Make JSON save format meet Puck library module requirements
> Fix JSON save format

- apps/mylocation/README.md
Fix spelling of the Scottish capital city in the README :)
> Spelling issue in mylocation README

- apps.json
- apps/qrcode/ChangeLog
- apps/qrcode/custom.html
* Integer scaling of the qr code
* Warning/Error message in case of to much data or similar conditions
* New options
* Prevent integer scaling
* Set backlight to max. while QR is shown
* Do not lock or dim while showing QR
* Hide Description
* Replacement of default description
* Error correction Level
> Integer scaling and additional configuration options for the Custom QR Code app

- apps.json
- apps/locale/locales.js
- apps/weatherClock/ChangeLog
- apps/weatherClock/app.js
Added translations for English with Dutch units
> Update locales.js with en_NL and weatherClock

- apps.json
- apps/numerals/ChangeLog
- apps/numerals/README.md
- apps/numerals/numerals.app.js
- apps/numerals/numerals.settings.js
enhance for use with Bangle2, add new draw mode
> update Numerals clock

- apps.json
- apps/clicompleteclk/ChangeLog
- apps/clicompleteclk/README.md
- apps/clicompleteclk/app.js
Just a small update:
- Load steps from Health Tracking app (if installed)
> CLI complete clock v0.02

- apps.json
- apps/impwclock/ChangeLog
- apps/impwclock/README.md
- apps/impwclock/clock-impword.js
Copied changes from wclock to handle different screen geometry of both BangleJS and BangleJS2 cases. Tested on both devices.
> Updates for impwclock BangleJs2 compatibility

- apps.json
- apps/clicompleteclk/README.md
- apps/clicompleteclk/app.js
- apps/clicompleteclk/settings.js
- All additional data can be toggled via settings
- Support for 6x8 font
> CLI complete clock v0.03

- apps/locale/locales.js
Added polish diacritics to charFallbacks, and Polish locale to locales list.
> Added polish locale

- apps.json
- apps/weatherClock/ChangeLog
- apps/weatherClock/app.js
On Bangle.js 2 there still was a layout overlap issue for wind text.
This update fixes it. Tested for different input lengths in emulator, also for Bangle.js.
> weatherClock Bangle.js 2 layout compatibility 

- apps.json
- apps/android/ChangeLog
- apps/android/boot.js
Fixes the issue mentioned in http://forum.espruino.com/conversations/370923/
> android: Send notification id when handling notifications

- apps.json
- apps/dtlaunch/ChangeLog
- apps/dtlaunch/app-b1.js
- apps/dtlaunch/app-b2.js
- apps/dtlaunch/settings-b1.js
- apps/dtlaunch/settings-b2.js
- apps/dtlaunch/settings.js
- Allows to selectively show/hide launchers and clocks.
- Adds setting to directly launch on touch with Bangle 2
> Desktop launcher: Adds settings page

- apps.json
- apps/pooqroman/ChangeLog
- apps/pooqroman/README.md
- apps/pooqroman/app.js
Add an option to enable the backlight on wrist-twist.
> pooq Roman: autolight

- apps.json
- apps/thermom/ChangeLog
- apps/thermom/app.js
Make temperature value readable on smaller screens
> Thermometer app working on BangleJS 2

- apps/locale/locales.js
Added Latvian diacritics in "charFallbacks"
Added "lv_LV" locale
Sorted "charFallbacks" alphabetically
Also just looking at the ISO map, I guess for all lowercase diacritics we have to add uppercase ones too, right?
> Added Latvian language to "locales.js"

- apps.json
- apps/widpedom/ChangeLog
- apps/widpedom/widget.js
Works around espruino/Espruino#2116 in order to fix #961
> widpedom: Save lastUpdated as a unix timestamp

- apps.json
- apps/messages/ChangeLog
- apps/messages/app.js
- apps/messages/lib.js
- apps/messages/widget.js
> messages: don't buzz during Quiet Mode

- apps.json
- apps/hcclock/ChangeLog
- apps/hcclock/README.md
- apps/hcclock/hcclock.app.js
Small addition : adds support for opening messages using BTN3:
- Only enabled when app is present
- Only visible when messages are present
> High Contrast Clock : Added Support for messages

- apps/locale/locales.js
> corrected cs_CZ "trans" messages

- apps.json
- apps/setting/ChangeLog
- apps/setting/settings.js
The list didn't have min and max set and only clipped to a correct value meaning the scroll didn't work correctly at the extrema (v could go up or down beyond the bounds).
> Fix bug with debug info

- apps.json
- apps/qrcode/ChangeLog
- apps/qrcode/custom.html
In some conditions (and with some smartphone cameras) a brightness change can help the qr scan to work better.
> Custom QR Code: Change brightness on touch

- apps.json
- apps/weatherClock/ChangeLog
- apps/weatherClock/app.js
If weather code is available. use weather condition code for icon selection else use textual representation as before.
See 
https://github.com/espruino/BangleApps/issues/1049#issuecomment-1003538475
--
Changes for Weather app (not clock) will come soon.
> WeatherClock: Use weather condition code for icon selection

- apps.json
- apps/weather/ChangeLog
- apps/weather/app.js
- apps/weather/lib.js
If weather code is available. use weather condition code for icon selection else use textual representation as before.
See
#1049 (comment)
> Weather app v0.14: use weather condition code for icon selection

- apps.json
- apps/weather/ChangeLog
- apps/weather/lib.js
- apps/weather/widget.js
Only the widget was broken, not the app.
Fixes https://github.com/espruino/BangleApps/issues/1049#issuecomment-1005560918
> weather: fix widget icon

- apps.json
- apps/gpsinfo/ChangeLog
- apps/gpsinfo/gps-info.js
- apps/widbatpc/ChangeLog
- apps/widbatpc/widget.js
GPS Info App: Resolve one FIFO_FULL case and exit App with button press.
Battery Level Widget (with percentage): Increase screen update rate when charging - as requested by issue https://github.com/espruino/BangleApps/issues/1137
> Update GPS Info App and "Battery Level Widget (with percentage)"

- apps.json
- apps/wid_a_battery_widget/ChangeLog
- apps/wid_a_battery_widget/widget.js
Increase screen update rate when charging.
> Update "A Battery Widget (with percentage)"

- apps/ptlaunch/README.md
The README.md for ptlaunch missed some information and was not totally clear on how to install that app. I added this information. The original author crazysaem reviewed the changes and gave approval, see http://forum.espruino.com/conversations/370865/?offset=25#comment16339021
It's just some documentation change, no change in the actual app. Therefore, I have not changed the version number.
> ptlaunch: Improve documentation in README.md

- apps.json
- apps/recorder/ChangeLog
- apps/recorder/README.md
- apps/recorder/app.js
- apps/recorder/widget.js
* Add recording for battery stats
* Fix execution of other recorders (*.recorder.js)
* Modified icons and colors for better visibility
* Only show plotting speed if Latitude is available
> Recorder improvements

- apps.json
- apps/locale/ChangeLog
- apps/locale/locales.js
Added Swedish localisation with English text
> Update locale with en_SE

- apps.json
- apps/qalarm/ChangeLog
- apps/qalarm/qalarm.js
Just one keystroke was needed to fix the bug where Q Alarm did not activate sometimes!
> 0.04 Fix alarm not activating

- apps.json
- apps/lapcounter/ChangeLog
- apps/lapcounter/app-icon.js
Icon now works in dark and light theme.
> Lap Counter - Use themeable icon

- apps/antonclk/README.md
- apps/antonclk/app.js
I fixed the typo and format of the new option in readme.md
Furthermore I removed my testdata "weekday name" hardcoded to "thursday" - would be a mess if it is always thursday ;)
and tagged the string "week" that it has to be added in locale-app
> Antonclk clock 0.05 show weeknumber *bugfix*

- apps.json
- apps/gpsinfo/ChangeLog
- apps/gpsinfo/gps-info.js
Fixes FIFO_FULL error -> #1251
> Fix: GPS Info FIFO_FULL error

- apps.json
- apps/circlesclock/ChangeLog
- apps/circlesclock/README.md
- apps/circlesclock/app.js
Small bugfix release:
- Show correct percentage values in circles
- Show humidity as weather circle progress
> Circlesclock: Show correct percentage values in circles & show humidity as weather circle progress

- apps.json
- apps/antonclk/ChangeLog
- apps/antonclk/README.md
- apps/antonclk/app.js
- apps/antonclk/settings.js
& some code rework
+ moved settings-helper method def to load settings method
+ settingsfile as const
+ isBangle1 via HWVERSION==1
cal Week is buffered until date or timezone changes
fixes #1271
> Anton clock 0.06 - fixes #1271

- apps.json
- apps/bthrm/ChangeLog
- apps/bthrm/boot.js
- apps/bthrm/bthrm.js
- apps/bthrm/recorder.js
* Prevent readings from internal sensor mixing into BT values
* Mark events with src property
* Show actual source of event in app
> BTHRM - Prevent mixed readings from both sensors

- apps.json
- apps/assistedgps/ChangeLog
- apps/assistedgps/custom.html
Fewer GNSS systems could decrease time to fix.
This patch adds a checkbox for each choice.
> Select which GNSS system to use

- apps.json
- apps/vectorclock/ChangeLog
- apps/vectorclock/app.js
- apps/vectorclock/settings.js
Vector clock was too monochrome for my taste.
I decided to try and change the weekday font colour to yellow.
Well, one thing led to another, and I ended up configuring a possible different colour for each "section".
Then I also added a configuration file, and a settings menu to configure it.
It ended up looking good enough to "go public".
I hope I didn't bloat the app too much, as I'm not very experienced with JS, and is my first foray into programming on such a memory starved device.
Any feedback is more than welcome, so I guess you can consider this PR more like a "request for comments". =-)
> Add colour configuration to vector clock

- apps.json
- apps/circlesclock/ChangeLog
- apps/circlesclock/README.md
- apps/circlesclock/app.js
- apps/circlesclock/settings.js
* Allow settings empty circles
* Support to choose between humidity and wind speed for weather circle progress
* Support to show time and progress until next sunrise or sunset
* Quicker lookup of circle positions
* Code cleanup 
* Remove pedometer widget from dependencies as steps are optional and steps can be obtained from Bangle health
**The clock looks pretty much feature complete for me now :-)**
> Circlesclock v0.06: sun progress and more

- apps.json
- apps/gpsinfo/ChangeLog
- apps/gpsinfo/gps-info.js
- apps/slevel/ChangeLog
- apps/slevel/spiritlevel.js
Does anybody ever seen a GLONAS satellite?
> 1. GPS Info App: Show satellites "in view" separated by GNS-system; 2. Spirit Level App: Now also visible on Bangle.js 2

- lang/de_DE.json
Improved the recently added translations for de_DE
> Improved the recently added translations for de_DE

- .gitignore
Let git ignore apps.json so that nobody tries to commit it
> Let git ignore apps.json

- apps.json
- bin/firmwaremaker.js
- bin/firmwaremaker_c.js
- ported bin/firemwaremaker*.js to metadata.json
- Offer an easy way to use a restricted apps.json
> Jekyll apps.json changes

- apps/fileman/metadata.json
Hi, Sorry about the previous pull request I realized that was not a good idea. This is just a pull request for making File Manager compatible with Bangle.js 2.
> Just File Manager For Bangle.js 2

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
- apps/circlesclock/settings.js
* Allow configuration of minimal heart rate confidence
> Circlesclock 0.07

- apps/lapcounter/ChangeLog
- apps/lapcounter/app.js
- apps/lapcounter/metadata.json
* 1 bit icon on opening screen (appears in fg color)
* Say "button 1" instead of "button"
> Make lapcounter behave better on `Bangle.js 1`

- apps/health/ChangeLog
- apps/health/app.js
- apps/health/boot.js
- apps/health/metadata.json
Allow to take HRM every 3 minutes while waiting 1 minute on data from HRM
> health - Adds 3 minute setting

- apps/acmaze/metadata.json
- apps/ftclock/metadata.json
Both apps were tested on a `bangle.js 1` by forum user Mi: https://forum.espruino.com/comments/16376253/ (thanks for testing).
> `acmaze` and `ftclock` are `bangle.js 1` compat

- apps/morse/morse-code.js
> fixed Font-Name in Morse App

- apps/vectorclock/ChangeLog
- apps/vectorclock/app.js
- apps/vectorclock/metadata.json
- apps/vectorclock/settings.js
Chimes the time with a up/down swipe
> Add "Chime the Time" to Vector Clock

- index.html
Show bangle info on more page on the Web UI when a Bangle.js is connected.
Should be merged together with https://github.com/espruino/EspruinoAppLoaderCore/pull/13
**Screenshot:**
> Web UI: Show bangle info on more page when connected

- apps/circlesclock/ChangeLog
- apps/circlesclock/README.md
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
- apps/circlesclock/settings.js
* Support to show temperature, air pressure or altitude from internal pressure sensor
* Fix sunprogress calculation during night
*  Refactor settings menu
* The color of each circle can be configured. The following colors are available:
* Basic colors (red, green, blue, yellow, magenta, cyan, black, white)
* Color depending on value (green -> red, red -> green)
* Good HRM value will not be overwritten so fast anymore
Changes were beta tested by @halemmerich and some idea are from him. Thx for that :)
> Circlesclock v0.09

- apps/torch/ChangeLog
- apps/torch/app.js
- apps/torch/metadata.json
- apps/torch/settings.js
#540 
Add color options for torch app in settings.
> Add Torch App Color Options

- apps/launch/ChangeLog
- apps/launch/app.js
- apps/launch/metadata.json
- apps/launch/settings.js
Closes https://github.com/espruino/BangleApps/issues/1015
I use Desktop Launcher as a model, I am still learning :-)
> Launcher - New option to hide clocks from the app list

- apps/widgps/README.md
GPS widget: remove out of date 'requires firmware' messages
> GPS widget: remove out of date 'requires firmware' messages

- apps/route/custom.html
> route viewer: typo

- apps/sleeplog/ChangeLog
- apps/sleeplog/boot.js
- apps/sleeplog/metadata.json
Fixes 
```
Uncaught Error: Expecting a string, got undefined
at line 93 col 59 in sleeplog.boot.js
...(storage.read(this.logfile)));
```
see https://github.com/espruino/BangleApps/issues/1423
> sleeplog: fix #1423

- apps/red7game/ChangeLog
- apps/red7game/README.md
- apps/red7game/metadata.json
- apps/red7game/red7.js
I left a big bug in the game where game wouldn't end in some situations. Fix it now.
> Fix bug and update red7 game.

- apps/mylocation/mylocation.app.js
- apps/widmp/ChangeLog
- apps/widmp/metadata.json
- apps/widmp/widget.js
see forum.espruino.com/conversations/371985
> Moon Phase Widget: Replace the 8 phases by a more exact drawing

- apps/ruuviwatch/ChangeLog
- apps/ruuviwatch/README.md
- apps/ruuviwatch/metadata.json
- apps/ruuviwatch/ruuviwatch.app.js
Add ability to rename tags.
Add Sauna, Fridge & Freezer alert. Support °F based on locale.
Prepare for Bangle 2 w/ swipe support (maybe – need to read up on that and try the emulator).
> Support naming, Farenheit, and alerts.

- apps/bthrm/ChangeLog
- apps/bthrm/README.md
- apps/bthrm/boot.js
- apps/bthrm/default.json
- apps/bthrm/metadata.json
- apps/bthrm/recorder.js
- apps/bthrm/settings.js
There are 4 new modes: Off,Default,Both,Custom
These all set a valid subset of the settings.
> BTHRM - Allow settings modes

- apps/dtlaunch/ChangeLog
- apps/dtlaunch/app-b2.js
- apps/dtlaunch/metadata.json
Allows multiple words in one line and splits camel case app names to allow wrapping those.
> dtlaunch - Optimize line breaks for Bangle 2

- apps/vectorclock/ChangeLog
- apps/vectorclock/app.js
- apps/vectorclock/metadata.json
https://github.com/espruino/BangleApps/issues/1437
> Vector Clock: Fix problem with "Bangle.CLOCK"

- apps/bthrv/ChangeLog
- apps/bthrv/app.js
- apps/bthrv/metadata.json
This works in most situations, but the kill handler set on line 98 just doesn't trigger. That causes lines without \n in the csv file when currently taking measurements.
> bthrv - Always write interval data on kill and reset if at least the first measurement is available

- apps/timecal/ChangeLog
- apps/timecal/README.md
- apps/timecal/metadata.json
- apps/timecal/testing/timecal.app.test.js
- apps/timecal/timecal.app.js
- apps/timecal/timecal.settings.js
next try ;)
replaces PRQ #1464
---
fixes FRQ #1154 
All settings are tested with testscript /testing/ folder
Update Date on Day change might be buggy.....
---
0.03: a lot of more settings for outline, colors and highlights
0.04: finalized README, fixed settings cancel, fixed border-setting
----
Calendar View can be customized
* < Save: Exist and save the current settings
* Show date: Choose if and how the date is displayed: none, locale (default), monthfull or monthshort.yearshort #weeknum with 0 prefixed
* Start wday: Set day of week start. Values: 0=Sunday, 1=Monday,...,6=Saturday or -1=Relative to today (default 0: Sunday)
* Su color: Set Sundays color. Values: none (default), red, green or blue
* Border: show or none (default)
* Submenu Today settings - choose how today is highlighted …
> v 0.04 fixes #1154

- apps/antonclk/ChangeLog
- apps/antonclk/metadata.json
- apps/antonclk/settings.js
- apps/messages/ChangeLog
- apps/messages/app.js
- apps/messages/metadata.json
- apps/messages/settings.js
- apps/messages/widget.js
Aligned default settings with app.js, otherwise the initial displayed settings will be confusing to users. I was puzzled by it everytime I had to reset my watch and wanted to change settings.
> Anton Clock v0.07

- apps/stopwatch/ChangeLog
- apps/stopwatch/metadata.json
- apps/stopwatch/stopwatch.app.js
> Stopwatch touch - adjust on touch for x,y outside the dimensions of g.getW/H

- modules/exstats.js
It seems to fix it. +1
https://github.com/espruino/BangleApps/issues/1479
> Fixed stepHistory

- apps/messages/app.js
I added the threema icon but i wasn't sure about the size of the icon.
Should it be 32x32px or 48x48px? The code suggests it to be 48x48px but it looked to big for me so i made it 32x32px.
--
As this is just a minor change i did not increase the version and changelog.
> Messages: Threema icon

- apps/messages/app.js
Alarm clock reports as "alarmclockreceiver" on my side but i guess it is "alarm" on some other devices
> Messages: icon for alarms

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
- apps/circlesclock/settings.js
* New color option: foreground color
* Improve performance, reduce memory usage
* Small optical adjustments
> Circlesclock v0.11

- apps/terminalclock/metadata.json
I forgot to update the version in the last pull request
> update forgoten metadata.json

- apps/info/README.md
- apps/speedalt/ChangeLog
- apps/speedalt/README.md
- apps/speedalt/app.js
- apps/speedalt/metadata.json
- apps/vectorclock/ChangeLog
- apps/vectorclock/app.js
- apps/vectorclock/metadata.json
also includes fix for "Vector Clock v0.07 makes widgets "blink" #1534"
> GPS Adventure Sports App: Full functionality on Bangle.js 2

- apps/lcars/ChangeLog
- apps/lcars/lcars.app.js
- apps/lcars/metadata.json
> Fix LCARS clock alarm not to go bigger than 100;

- apps/crowclk/ChangeLog
- apps/crowclk/crow_clock.js
- apps/crowclk/metadata.json
- apps/dtlaunch/ChangeLog
- apps/dtlaunch/app-b1.js
- apps/dtlaunch/metadata.json
> Fix Crow Clock For Dark Mode and Fix Desktop Launcher Bangle.js 1 not showing white images.

- apps/touchtimer/ChangeLog
- apps/touchtimer/app.js
- apps/touchtimer/metadata.json
This is an update to the touch timer app so that you are able to repeat the last run timer and not have to create a new one each time.
> touchtimer: ADD ability to repeat the timer

- apps/touchtimer/ChangeLog
- apps/touchtimer/app.js
- apps/touchtimer/metadata.json
- apps/touchtimer/settings.js
- This is a configurable option (Default is off) for the timer to buzz
each second when there are 5 seconds left.
> touchtimer: ADD 5 second count down buzzer

- apps/clockcal/ChangeLog
- apps/clockcal/README.md
- apps/clockcal/app.js
- apps/clockcal/metadata.json
- apps/clockcal/settings.js
also removed a bug with the small calendar not coloring the current day.
> ClockCal: Configurable launch gestures

- apps/waypointer/ChangeLog
- apps/waypointer/README.md
- apps/waypointer/app.js
- apps/waypointer/metadata.json
Bangle.js 2 compatibility
recalculated layout to rescale on BangleJs2.
ping @hughbarney - if you want to take a look
> waypointer

- apps/run/settings.js
Fix additional entry in new menu and exception in old menu
> [RUN] Fix exception on Dist/Step/Time pattern selection in settings

- apps/pebble/ChangeLog
- apps/pebble/README.md
- apps/pebble/metadata.json
- apps/pebble/pebble.app.js
- apps/pebble/pebble.settings.js
Modifications to pebble clock:
* Added setting to choose theme
* Added option to show lock on watchface when screen is locked
@hughbarney hope you don't mind the changes I've made to your app! 
All changes are optional and must be enabled in settings, by default it is exactly as before.
> Modifications to pebble clock

- apps/aclock/metadata.json
- apps/berlinc/metadata.json
- apps/calculator/metadata.json
- apps/cliock/metadata.json
- apps/ffcniftyb/metadata.json
- apps/floralclk/metadata.json
- apps/hcclock/metadata.json
- apps/impwclock/metadata.json
- apps/intclock/metadata.json
- apps/intervals/metadata.json
- apps/ios/metadata.json
- apps/numerals/metadata.json
- apps/pipboy/metadata.json
- apps/promenu/metadata.json
- apps/score/metadata.json
- apps/showimg/metadata.json
- apps/sunclock/metadata.json
- apps/supmariodark/metadata.json
- apps/touchmenu/metadata.json
- apps/waveclk/metadata.json
I have found several apps that have a README.md but do not mention it in the metadata.json.
So it is not shown in the apploader. This PR fixes the problem.
> Add README.md to metadata.json if exists

- apps/game1024/ChangeLog
- apps/game1024/app.js
- apps/game1024/metadata.json
- apps/game1024/settings.js
> v0.09 added settings menu, removed symbols button, added highscore reset, clockmode optional

- apps/messages/ChangeLog
- apps/messages/README.md
- apps/messages/metadata.json
- apps/messages/settings.js
- apps/messages/widget.js
Update ChangeLog, metadata.json, README.md and settings.js:
- Add option to toggle icon flashing.
Update widget.js:
- Add option to toggle icon flashing.
- Correct clearRect y2 value.
- Moved icon 1px up to be more centered.
> massages: Add option to disable icon flashing

- apps/mylocation/ChangeLog
- apps/mylocation/metadata.json
- apps/mylocation/mylocation.app.js
Corrected check for selected location = "???".
> mylocation: Fix selecting Frankfurt not saved

- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/metadata.json
- Read alarms from new scheduling library
- account for higher acceleration sensor noise on Bangle.js 2
> sleepphasealarm

- apps/accellog/app.js
- apps/boot/bootupdate.js
- apps/dane_tcr/app.js
- apps/gpsinfo/gps-info.js
- apps/gpsrec/app.js
- apps/gpstime/gpstime.js
- apps/health/app.js
- apps/ltherm/app.js
- apps/thermomF/app.js
- apps/toucher/app.js
- apps/viewstl/viewstl.app.js
- apps/viewstl/viewstl.min.js
Incidentally, where does the "Loading..." message that is displayed when pressing btn1 on bangle2 when the clock is displayed come from?
> Tagging bootloader messages, and all "Loading..." messages

- apps/widcal/ChangeLog
- apps/widcal/metadata.json
- apps/widcal/widget.js
Repeated redrawing would create multiple redraw-timeouts
> widcal: fix memory leak

- apps/choozi/ChangeLog
- apps/choozi/appb2.js
- apps/choozi/metadata.json
fixed a couple bugs when tested on real watch
> Choozi Fix a couple bugs

- css/main.css
Reverts espruino/BangleApps#1571
because of http://forum.espruino.com/conversations/374984/#comment16485263
> Revert "main.css: Force line break for smaller resolutions"

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
~~I made some refactor to improve the readability of the code.~~
~~I also renamed some functions to better explain their behavior (eg.: `decodeTime` &rarr; `millisToTime`, etc.)~~
~~AFAIK the code is minified before being sent to the watch so a few more characters should not be a problem.~~
I removed the refactor from my PR due to conflicts with #1722 and kept only the bug fix.
---
Fix #1676
> [Alarms & Timers] Fix #1676

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
- apps/sched/ChangeLog
- apps/sched/lib.js
- apps/sched/metadata.json
- apps/sched/sched.js
- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/metadata.json
- css/main.css
As communicated in #1679, moved a few functions to scheduler lib.
> Refactor some methods to scheduling library

- apps/kbswipe/ChangeLog
- apps/kbswipe/lib.js
- apps/kbswipe/metadata.json
This solves issue #1737 regarding incorrect vertical positioning of the marker.
> [Swipe keyboard] Consider widget field for marker positioning

- apps/health/ChangeLog
- apps/health/app.js
- apps/health/metadata.json
This PR add the `LANG` placeholders to **Health** app.
---
Is there a reason this app settings are in the app instead of the global Settings menu?
> [Health Tracking] Add LANG placeholders, minor tweaks

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
Fix issue introduced with #1722.
I open a new PR because the old one (#1729) contains other stuff also.
---
Fix #1735
> [Alarms & Timers] Fix #1735

- apps/health/ChangeLog
- apps/health/app.js
- apps/health/metadata.json
- apps/health/settings.js
As suggested in https://github.com/espruino/BangleApps/pull/1734#issuecomment-1108413622.
> [Health Tracking] Move settings

- apps/clockcal/ChangeLog
- apps/clockcal/metadata.json
- apps/heartzone/ChangeLog
- apps/heartzone/metadata.json
- apps/stardateclock/ChangeLog
- apps/stardateclock/metadata.json
> Fix some version numbers

- apps/alarm/ChangeLog
- apps/alarm/README.md
- apps/alarm/app.js
- apps/alarm/metadata.json
This PR adds ~~an option to set~~ the "Save on Back" (https://github.com/alessandrococco/BangleApps/issues/5) and three new menu items:
- `Enable All` (iff at least one alarm/timer is OFF)
- `Disable All` (iff at least one alarm/timer is ON) 
- `Delete All` (iff at least one alarm/timer exists)
~~Moreover it removes the custom boolean formatter since the new menu system handles the booleans better.~~
> [Alarms & Timers] "Save on Back", bulk actions

- apps/activityreminder/README.md
- apps/activityreminder/settings.js
- Fixed typos
- Improved settings usability
- No version increase as this is just minor stuff
> Activity Reminder: Minor improvements

- apps/activityreminder/ChangeLog
- apps/activityreminder/README.md
- apps/activityreminder/app.js
- apps/activityreminder/metadata.json
- apps/activityreminder/settings.js
- Obey system quiet mode
- Extend allowed dismiss delay
> ActivityReminder: Obey system quiet mode & extend allowed dismiss delay

- apps/kbtouch/ChangeLog
- apps/kbtouch/README.md
- apps/kbtouch/lib.js
- apps/kbtouch/metadata.json
- apps/kbtouch/settings.js
@gfwilliams 
Updated keyboard can be loaded here: https://thyttan.github.io/BangleApps/?q=touch%20keyboard
I considered making a new app instead but decided it felt better to use settings for this app as to not clutter the app loader. 
A pro for doing a new app could be some small performance improvement, I guess. Any thoughts?
> [Touch keyboard] Introduce settings for changing layout and functionality

- apps/gpsautotime/ChangeLog
- apps/gpsautotime/metadata.json
- apps/gpsautotime/settings.js
- apps/gpsautotime/widget.js
- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/README.md
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/metadata.json
gpsautotime: Add setting to hide the widget
sleepphasealarm: Add check for correct day of week
> Changes to gpsautotime / sleepphasealarm

- apps/alarm/app.js
Small code change,  [as suggested during the review](https://github.com/espruino/BangleApps/pull/1773#pullrequestreview-961431288).
> [Alarms & Timers] forEach

- apps/golfview/ChangeLog
- apps/golfview/custom.html
- apps/golfview/golfview.js
- apps/golfview/metadata.json
This PR adds a more reasonable way to search for your course. Future improvements include the ability to see how well a given course is supported and the ability to store more than one course at a time.
> [GolfView] Course search

- apps/widgps/ChangeLog
- apps/widgps/metadata.json
- apps/widgps/widget.js
Periodically update the gps widget so the always on display of the BangleJS 2 does show current GPS fix
> widgps: add intervall to update the widget

- apps/neonx/ChangeLog
- apps/neonx/README.md
- apps/neonx/metadata.json
- apps/neonx/neonx.app.js
- apps/neonx/neonx.settings.js
This PR improves the animation when the bangle is locked / unlocked for the NeoX watch face. I tested both, NeoX and Neo IO X.
> [NeoX] Better lock animation.

- apps/terminalclock/ChangeLog
- apps/terminalclock/app.js
- apps/terminalclock/metadata.json
- apps/terminalclock/settings.js
Thanks to the Altimeter app, where I borrowed the altitude reading code from.
> [terminalclock] Add altitude to terminalclock

- apps/terminalclock/README.md
I just realized I forgot to update the description, so this small addition to #1805
> [terminalclock] Update description for v0.05

- apps/game1024/ChangeLog
- apps/game1024/metadata.json
- apps/game1024/settings.js
fixed typo in settings that did not handle clockMode correctly
> fix clockmode setting

- apps/health/ChangeLog
- apps/health/app.js
- apps/health/metadata.json
This PR fixes #1366 (there was a division by zero). It also restores the var I replaced with let some weeks ago.
> [Health] Fix #1366

- apps/sleeplog/ChangeLog
- apps/sleeplog/README.md
- apps/sleeplog/lib.js
- apps/sleeplog/metadata.json
Reduced log size further to 750 entries
> [sleeplog] Reduced log size further, see #1835

- apps/rebble/ChangeLog
- apps/rebble/metadata.json
- apps/rebble/rebble.app.js
-added localization
-removed deprecated code
> [Rebble Clock] added localization

- apps/alarm/app.js
New PR because #1853 was merged too early 😄
> [Alarms & Timers] Fix repeat when user unchecks ALL the days

- apps/multitimer/ChangeLog
- apps/multitimer/alarm.js
- apps/multitimer/app.js
- apps/multitimer/metadata.json
Update Multi Timer for time_utils module, plus a few tweaks.
> [Multi Timer] update

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/default.json
- apps/circlesclock/metadata.json
- apps/circlesclock/settings.js
* Allow configuration of update interval
> Circlesclock v0.12

- apps/messages/ChangeLog
- apps/messages/app.js
- apps/messages/metadata.json
- apps/messages/widget.js
Closes #1873 
---
I didn't add an option for this because I think it is wrong that the screen turns on when the unread timeout expires but I'm open to discussion :-)
> [Messages] Don't turn on the screen after unread timeout expires

- apps/homework/app.js
- apps/homework/metadata.json
- apps/homework/subjects.html
Rename subjects.txt to homework.subjects.txt and add it to the data section in metadata
> Homework app cleanup

- apps/barclock/ChangeLog
- apps/barclock/README.md
- apps/barclock/clock-bar.js
- apps/barclock/metadata.json
- apps/barclock/settings.js
- modules/ClockFace.js
- modules/ClockFace.md
- modules/ClockFace_menu.js
Builds on [this PR](https://github.com/espruino/BangleApps/pull/1893)
Settings for showing date, loading widgets, and font
> barclock: add settings using ClockFace

- apps/speedalt2/README.md
Fixed a couple of small typos in the readme file.
> Fixed Typos

- apps/calendar/ChangeLog
- apps/calendar/calendar.js
- apps/calendar/metadata.json
To work with firmware 2v13.123.
> calendar: Fix scope of let variables

- apps/widmp/ChangeLog
- apps/widmp/metadata.json
- apps/widmp/settings.js
- apps/widmp/widget.js
Dark mode, custom colour for the moon, and fix a bug with acting on mylocation changes
> Moon phase widget - dark mode, custom colours, and small bugfix

- apps/bigdclock/ChangeLog
- apps/bigdclock/bigdclock.app.js
- apps/bigdclock/metadata.json
(Apologies for the mess earlier on - I find git awkward to use, and it always seems to get in my way).
> Big Digit Clock - Internationalisation; small bug fix

- apps/bigdclock/ChangeLog
- apps/bigdclock/bigdclock.app.js
- apps/bigdclock/metadata.json
> bug fix (again!): confused setTimeout with setInterval

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
This PR adds support for seconds in timers.
> [Alarms & Timers] Add seconds to timers

- apps/ffcniftya/ChangeLog
- apps/ffcniftya/app.js
- apps/ffcniftya/metadata.json
This PR upgrades the **Nifty-A Clock** to the  **ClockFace** library (thank @rigrig!)
(I plan to update **Nifty-B Clock** and some other clocks as well)
> [Nifty-A Clock] ClockFace

- apps/ffcniftya/app.js
Part 2 of #1935 - I didn't realize it was that easy 😅
(I wouldn't upgrade the app version)
> [Nifty-A Clock] Read settings file via ClockFace

- apps/activityreminder/ChangeLog
- apps/activityreminder/app.js
- apps/activityreminder/boot.js
- apps/activityreminder/lib.js
- apps/activityreminder/metadata.json
- apps/activityreminder/settings.js
> [ActivityReminder] Bug fixes for the 2.13 cutting edge and 2.14 firmware 

- apps/cassioWatch/ChangeLog
- apps/cassioWatch/README.md
- apps/cassioWatch/app.js
- apps/cassioWatch/metadata.json
First of all, @Santagain thank you so much for the great cassio watch face. I have seen some todos that you added and implemented some of those: 
I added support for heart rate and the watch also shows the temperature now if weather data is available. Daily steps are also shown now.
Here is a screenshot:
> [cassioWatch] Version 0.10 - Show daily step count, temperature as well as heartrate.

- apps/widbaroalarm/ChangeLog
- apps/widbaroalarm/README.md
- apps/widbaroalarm/default.json
- apps/widbaroalarm/metadata.json
- apps/widbaroalarm/settings.js
- apps/widbaroalarm/widget.js
* Use Prompt with dismiss and pause
* Improve barometer value median calculation
> Baroalarm v0.04

- .github/workflows/nodejs.yml
- .gitignore
- README.md
- package-lock.json
Updated Github actions to v3 and replaced TravisCI badge in readme with badge for Github action.
> Updates Github action and replaces TravisCI badge

- apps/health/interface.html
No version update, because only interface.html was changed.
> [health] Fix load after delete

- README.md
- typescript/types/globals.d.ts
Documents all four possible widget areas
> Document all widget areas

- apps/_example_widget/widget.js
Resolves https://github.com/espruino/BangleApps/pull/1967#issuecomment-1157493161
> warn about bottom area widgets

- apps/hrm/ChangeLog
- apps/hrm/heartrate.js
- apps/hrm/metadata.json
VC31 and VC31b create different raw values. This dynamically scales according to the biggest seen value every time the graph starts on the left side.
> HRM raw graph autoscaling

- apps/hwid_a_battery_widget/ChangeLog
- apps/hwid_a_battery_widget/README.md
- apps/hwid_a_battery_widget/widget.js
Fixed position after unlocking
> H battery widget

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
- Load step goal from Bangle health app as fallback
- Memory optimizations
> CirclesClock v0.13

- apps/widbaroalarm/ChangeLog
- apps/widbaroalarm/metadata.json
- apps/widbaroalarm/widget.js
> Widget Barometeralarm: Fix exception

- apps/kbmulti/ChangeLog
- apps/kbmulti/README.md
- apps/kbmulti/lib.js
- apps/kbmulti/metadata.json
Implements additional mode for moving the cursor in the edited text. Swipe down for changing modes.
> Multitap Keyboard

- apps/bthrm/ChangeLog
- apps/bthrm/README.md
- apps/bthrm/boot.js
- apps/bthrm/metadata.json
- apps/bthrm/recorder.js
- apps/bthrm/settings.js
* Fix HRM fallback handling -> #2009
* Use default boolean formatter in custom menu and directly apply config if useful
* Allow recording unmodified internal HR
* Better connection retry handling
> BTHRM - Various improvements

- apps/messagesmusic/ChangeLog
- apps/messagesmusic/README.md
- apps/messagesmusic/app.js
- apps/messagesmusic/metadata.json
... making the app a little more reliable. Specifically while testing @rigrig's rewrite of  the Messages app.
The functionality is intact for the official Messages app.
> [Messagesmusic] Remove unnecessary line of code

- apps/ios/ChangeLog
- apps/ios/boot.js
- apps/ios/metadata.json
- apps/messages/ChangeLog
- apps/messages/lib.js
- apps/messages/metadata.json
Added support for more iOS apps and fixed typo for `lieferando`.
> [ios & messages] Added more iOS apps

- apps/widdst/ChangeLog
- apps/widdst/boot.js
- apps/widdst/metadata.json
- apps/widdst/widget.js
As per the feedback from version 0.01. Thanks!
> widdst - checks firmware; E.setDST(...) moved to boot.js

- apps/messages/ChangeLog
- apps/messages/lib.js
- apps/messages/metadata.json
Nextbike (bike sharing), Mattermost (instant messaging), etar (open source calendar, re-use calendar icon), opentasks (re-use todo icon), newpipe (re-use youtube icon)
> Added some notification icons

- apps/kbmorse/ChangeLog
- apps/kbmorse/lib.js
- apps/kbmorse/metadata.json
As I said on #2056, kbmorse is currently broken because of what seems to be an [Espruino bug](https://github.com/espruino/Espruino/issues/2240). This small update fixes the library by changing the code order.
> Fix kbmorse

- apps/hwid_a_battery_widget/ChangeLog
- apps/hwid_a_battery_widget/metadata.json
- apps/hwid_a_battery_widget/widget.js
> Handling exceptions

- apps/macwatch2/ChangeLog
- apps/macwatch2/app.js
- apps/macwatch2/metadata.json
I liked the watch but wanted it to show 12/24 hour time based on locale settings.
> Update macwatch2 app to use time based on locale settings

- apps/agenda/ChangeLog
- apps/agenda/agenda.js
- apps/agenda/metadata.json
Hide the time on `allDay` events, needs an up-to-date gadgetbridge to get the field right.
> agenda: added awareness of allDay field

- apps/thermom/ChangeLog
- apps/thermom/app.js
- apps/thermom/metadata.json
> [Thermometer] Add back button

- apps/chimer/ChangeLog
- apps/chimer/metadata.json
- apps/chimer/settings.js
- apps/chimer/widget.js
Fixed some sleep bugs. Added a sleep mode toggle
> Updated to version 0.02

- modules/wear_detect.js
removes temperature due to weather situations
this function achieved 97.3% [pr auc](https://stats.stackexchange.com/a/123370) on the dataset.
> Use 10-minute acceleration and charging for isWorn()

- apps/torch/ChangeLog
- apps/torch/app.js
- apps/torch/metadata.json
could not test it on Bangle.js 1 (don't have one) that everything works fine there.
> feature: set Brightness default to full

- apps/activityreminder/ChangeLog
- apps/activityreminder/app.js
- apps/activityreminder/metadata.json
I'm unsure if this change breaks the app on Bangle.js 1?
> [Activity Reminder] sofware back button via setUI

- apps/widtwenties/ChangeLog
- apps/widtwenties/metadata.json
- apps/widtwenties/widget.js
The watch would vibrate all night, harming battery life. This PR makes the watch only vibrate from 8 AM - 5 PM.
> Twenties - vibrates during work hours

- apps/numberchaser/metadata.json
The tags were updated to game,fun
> Updated tags on metadata.json

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/app.js
- apps/iconlaunch/metadata.json
- apps/imageclock/ChangeLog
- apps/imageclock/app.js
- apps/imageclock/metadata.json
Launcher -> Clock works fast on 2v15, the other way around only works for 2v15.20 upwards.
Diff seems to be gigantic, but it's mostly whitespace changes by indention of the surrounding blocks for GC and var->let.
> Fast switch for imageclock and iconlaunch

- apps/imageclock/ChangeLog
- apps/imageclock/app.js
- apps/imageclock/custom.html
- apps/imageclock/metadata.json
- Generated drawing code creates less promises
- Additional option in customizer to force drawing directly
- Fix possible early clearing of timeouts created by delay function
- Allow calls to setMatchedInterval without delay parameter to work correctly
> Imageclock - Improvements

- apps/gpstrek/ChangeLog
- apps/gpstrek/README.md
- apps/gpstrek/app.js
- apps/gpstrek/metadata.json
- apps/gpstrek/widget.js
Reduces number of file writes and makes the options a bit more explicit by moving them into their own submenu.
> gpstrek - Improve background/widget handling

- apps/setting/ChangeLog
- apps/setting/metadata.json
- apps/setting/settings.js
Changes to make use of [#2274](https://github.com/espruino/Espruino/pull/2274)
Launcher is configurable like a clock.
> Allow setting a launcher

- apps/aiclock/ChangeLog
- apps/aiclock/README.md
- apps/aiclock/aiclock.app.js
- apps/aiclock/metadata.json
The prob. of horizontal lines is now correlated with the battery level. So if the watch-face shows only a few lines its time to charge the bangle again ;)
> [AI Clock] The probability of horizontal lines is correlated with the battery level

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/app.js
- apps/iconlaunch/metadata.json
With ~40 apps this takes about 140ms of the start of iconlauncher.
> Iconlaunch - Cache icons on demand

- apps/gpstrek/ChangeLog
- apps/gpstrek/app.js
- apps/gpstrek/metadata.json
- apps/gpstrek/widget.js
* Changes to custom UI to prevent menu opening method being called multiple times caused by drag handling of leftright-UI.
* Correctly add and remove listeners for sensors on starting and stopping background mode
* Fix listener for accel beeing active all the time
> GPS Trekking - Improve UI and widget

- apps/weather/readme.md
Added documentation regarding Tiny Weather Forecast Germany and QuickWeather. Also mentioned Weather Notification.
> Added some documentation

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
Use Bangle.setUI({remove:...}) to allow loading the launcher without a full reset on 2v16
> Circlesclock v0.15

- apps/circlesclock/ChangeLog
- apps/circlesclock/app.js
- apps/circlesclock/metadata.json
- Fix const error (i was seeing lots of "Uncaught TypeError: Assignment to a constant" errors)
- Use widget_utils if available
> CirclesClock v0.16

- apps/widmsggrid/README.md
No code change/version bump
Discussed in https://github.com/espruino/BangleApps/pull/2186
> widmsggrid: improve README (installation: disable default widget)

- apps/quicklaunch/ChangeLog
- apps/quicklaunch/boot.js
- apps/quicklaunch/metadata.json
- apps/quicklaunch/settings.js
* Do not scan all apps on every boot
* Do not override setUI
> Quicklaunch - Improve performance

- apps/calculator/ChangeLog
- apps/calculator/app.js
- apps/calculator/metadata.json
> [Calculator] Exit with short press to BTN1 on Bangle.js 2

- apps/torch/ChangeLog
- apps/torch/README.md
- apps/torch/app.js
- apps/torch/metadata.json
If the screen is unlocked pressing upper left corner exits to watch face.
> [Torch] exit by pressing upper left corner

- apps/agpsdata/ChangeLog
- apps/agpsdata/app.js
- apps/agpsdata/lib.js
- apps/agpsdata/metadata.json
As suggested in https://github.com/espruino/BangleApps/issues/2223#issuecomment-1303746133
I am using Promises and some delay for writing the chunks of AGPS data into the Serial.
Lets see if this helps.
Any comments are welcome.
> agpsdata: Write AGPS data chunks with delay to improve reliability

- apps/powermanager/ChangeLog
- apps/powermanager/README.md
- apps/powermanager/boot.js
- apps/powermanager/lib.js
- apps/powermanager/metadata.json
- apps/powermanager/settings.js
Sets the battery calibration value after 3 hours of charging without reloads.
> powermanager - New option to automatically calibrate the battery

- apps/dtlaunch/ChangeLog
- apps/dtlaunch/app-b2.js
- apps/dtlaunch/metadata.json
- apps/dtlaunch/settings-b2.js
Fast loading requested [here](https://forum.espruino.com/conversations/381203/#comment16751193).
I changed most instances of var to let.
There is some small ram leak going back and forth between this dtlaunch and the slope clock, but pretty minor by my judgement. Edit: This has been solved with @halemmerich's help.
Edit: Added in the timeout to clock functionality from Icon Launcher.
> [Desktop Launcher] Fast load to clockface on B2

- apps/imageclock/ChangeLog
- apps/imageclock/app.js
- apps/imageclock/custom.html
- apps/imageclock/metadata.json
* Use widget_utils module
* Some caching for performance
* Add UI when drawing is finished to prevent drawing over the launcher
* Fix custom color setting inside generated code
> Imageclock

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/app.js
- apps/iconlaunch/metadata.json
Resets the timeout while actively using the launcher.
> Iconlaunch - Better timeout handling

- apps/torch/ChangeLog
- apps/torch/app.js
- apps/torch/metadata.json
Inspiration: https://github.com/espruino/BangleApps/pull/2243#issuecomment-1308513138
> [Torch] Widget field background follows torch colour

- apps/slopeclockpp/ChangeLog
- apps/slopeclockpp/app.js
- apps/slopeclockpp/default.json
- apps/slopeclockpp/metadata.json
- apps/slopeclockpp/settings.js
Configuration of colors and whether the steps and weather should be shown.
> Slopeclock++ v0.02

- apps/swp2clk/ChangeLog
- apps/swp2clk/boot.js
- apps/swp2clk/metadata.json
This implements an additional path for firmware newer than 2v15.135 while for now keeping compatibility with older firmware.
> swp2clk - Implement compatibility with Bangle.load/Bangle.showClock

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/app.js
- apps/iconlaunch/metadata.json
> [Icon launcher] Use Bangle.load and Bangle.showClock

- apps/hworldclock/ChangeLog
- apps/hworldclock/app.js
- apps/hworldclock/metadata.json
- apps/widbt_notify/ChangeLog
- apps/widbt_notify/metadata.json
- apps/widbt_notify/widget.js
According to https://forum.espruino.com/conversations/381552
> Added a g.reset()

- apps/widsleepstatus/ChangeLog
- apps/widsleepstatus/metadata.json
- apps/widsleepstatus/widget.js
- Load settings only once
- Better icons
- Read sleep status on every draw
Thanks for the feedback @halemmerich
> Widsleepstatus v0.02

- apps/bthrm/ChangeLog
- apps/bthrm/default.json
- apps/bthrm/lib.js
- apps/bthrm/metadata.json
- apps/bthrm/settings.js
* Fixes an issue where powering down the HRM and then powering on would prevent BTHRM from reconnecting
* Better logging for errors
* Additional setting in debug menu for active scanning
> bthrm - Fix restarting issue and more debug logging

- apps/rebble/ChangeLog
- apps/rebble/metadata.json
- apps/rebble/rebble.app.js
excuse me! I didn't realize that before I introduced a problem in the graphics!
I hope I haven't forgotten anything!
> [Rebble] fix draw before widget hide

- modules/README.md
Newcomers see the error e.g. "Module time_utils not found", Bangle freezes, a search on this repo doesn't list this error in the existing readmes, yet I suspect it is a very common error.  This PR will have it listed and hopefully help the next newcomer :)
> Update README.md, state the IDE error that we are fixing

- apps/mylocation/ChangeLog
- apps/mylocation/README.md
- apps/mylocation/custom.html
- apps/mylocation/metadata.json
Allow setting location from webinterface in the AppLoader
> MyLocation v0.08: Allow setting location from webinterface in the AppLoader

- apps/weather/ChangeLog
- apps/weather/clkinfo.js
- apps/weather/lib.js
- apps/weather/metadata.json
The picture is dynamically generated with the weather lib, maybe not better than having pre-generated pictures but looks quite good on my tests.
> weather: added weather condition to clkinfo

- apps/noteify/interface.html
- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/metadata.json
- apps/taglaunch/ChangeLog
- apps/taglaunch/app.js
- apps/taglaunch/metadata.json
- apps/tetris/metadata.json
> taglaunch: Backport PR 2316 for launch

- apps/barclock/ChangeLog
- apps/barclock/clock-bar.js
- apps/barclock/metadata.json
- modules/ClockFace.js
- modules/ClockFace.md
Depends on the `ClockFace` changes in #2336
> barclock: fast loading

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
> Add "Confirm" button to alarm and timer edit menus

- apps/gallery/README.md
- apps/gallery/interface.html
- apps/gallery/metadata.json
Just for fun Quick & Dirty interface for gallery. Basically just copied imageconverter.html and added some Util.writeStorage()/Util.eraseStorage()
> gallery: Add interface

- apps/qcenter/ChangeLog
- apps/qcenter/app.js
- apps/qcenter/metadata.json
- apps/qcenter/settings.js
qcenter is essentially a launcher and should be able to go back to the clock like one. Needs #2331 to actually trigger fast loading because else the remove method is not set for `setUI`. Should do close to nothing without #2331.
> qcenter - Fastload the clock on swipe

- apps/messageicons/lib.js
Also added some "colors" from the official branding guidelines with a reference to the source info.
Related to #2189
> Added several icons to MessageIcons' lib.js

- apps/aiclock/ChangeLog
- apps/aiclock/aiclock.app.js
- apps/aiclock/metadata.json
https://github.com/espruino/BangleApps/pull/2334#issuecomment-1333636754
> [AI Clock] Change to using widget_utils .hide()

- apps/gpstrek/ChangeLog
- apps/gpstrek/app.js
- apps/gpstrek/metadata.json
I could not find an actual solution to this problem so this at least makes gpstrek usable with minification enabled.
> gpstrek - Workaround minifier issue

- apps/android/ChangeLog
- apps/android/boot.js
- apps/android/metadata.json
- apps/files/ChangeLog
- apps/files/files.js
- apps/files/metadata.json
- apps/hrm/ChangeLog
- apps/hrm/heartrate.js
- apps/hrm/metadata.json
- apps/recorder/ChangeLog
- apps/recorder/app.js
- apps/recorder/metadata.json
- apps/weather/ChangeLog
- apps/weather/app.js
- apps/weather/metadata.json
Same drill as last time, I haven't tested this.. Ok to merge by me.
> [Multiple apps] autotranslate some strings

- apps/gallery/ChangeLog
- apps/gallery/app.js
- apps/gallery/metadata.json
or else depending on the theme settings black on white images end up as white on black.
> gallery: Do not invert image colors

- apps/podadrem/ChangeLog
- apps/podadrem/app.js
- apps/podadrem/metadata.json
... to not remove Quick Launch's listeners when fastloading.
> [Podcast Addict Remote] remove only specific listeners

- apps/messages/ChangeLog
- apps/messages/lib.js
- apps/messages/metadata.json
> messages: erase messages file instead of writing empty []

- apps/widmsggrid/metadata.json
Looks like 3e5c0538a9776014a7f99d8c3521d1372dde8a90 missed this, I was wondering why the default widget kept getting reinstalled ;-)
> widmsggrid: provides a "message" widget

- apps/widmessages/ChangeLog
- apps/widmessages/metadata.json
- apps/widmessages/widget.js
> widmessages: Fix messages not showing if UI auto-open is disabled

- apps/bwclk/ChangeLog
- apps/bwclk/app.js
- apps/bwclk/metadata.json
RAM leaks gone thanks to @BartS23, thanks!
Bug #2361 will not be fixed with this PR.
> [BW Clock] Add fastloading

- apps/mosaic/ChangeLog
- apps/mosaic/metadata.json
- apps/mosaic/mosaic.app.js
let me know if there's something else i need to do
> add localization to mosaic clock

- README.md
I'm not sure about this. But I had a hard time to get the project running locally on my computer. I realized that I have to initialize and update the git submodules first. If this is already documented somewhere and I missed it, then you can delete the PR I think. Or is the approach to get the project running locally different?
> Add info about git submodules

- apps/dragboard/ChangeLog
- apps/dragboard/README.md
- apps/dragboard/lib.js
- apps/dragboard/metadata.json
- apps/dragboard/settings.js
Allow users to make characters more visible to them (by choosing different colors, or forcing caps lock / all uppercase).
> [dragboard] add settings screen for colors and caps lock

- apps/health/ChangeLog
- apps/health/README.md
- apps/health/app.js
- apps/health/lib.js
- apps/health/metadata.json
- Show step goal in daily step chart
- Documentation fixes
Screenshot having 8000 as daily step goal:
> Health: Show step goal in daily step chart

- apps/agpsdata/ChangeLog
- apps/agpsdata/app.js
- apps/agpsdata/metadata.json
- Show last success date
- Do not start A-GPS update automatically
> AGPS data: Minor UI changes

- apps/grocery/ChangeLog
- apps/grocery/app.js
- apps/grocery/interface.html
- apps/grocery/metadata.json
Changes:
- Sort checked items to bottom as I have seen that behavior on most or all shopping/todo apps.
- Enable Widgets, the back button takes the space anyway.
- Allow to edit items without reuploading entire app with interface.html which is a modified grocery.html.
> grocery: sort, interface.html

- apps/widminbat/ChangeLog
- apps/widminbat/metadata.json
- apps/widminbat/widget.js
I've changed a few parts so it would show while charging.
@LeonMatthes what do you think?
> widminbat: Show while charging

- apps/dtlaunch/ChangeLog
- apps/dtlaunch/app-b2.js
- apps/dtlaunch/metadata.json
@jeffmer do you approve or object? :)
EDIT: added code from Icon Launch from PR #2183, by @halemmerich.
> [Desktop Launcher] don't initially mark the first app on a page when moving between pages + Introduce caching

- apps/android/boot.js
Reverts espruino/BangleApps#2472
> Revert "remove null check, since mapping is now down on app side"

- apps/bwclk/ChangeLog
- apps/bwclk/app.js
- apps/bwclk/metadata.json
- modules/clock_info.js
Fixes #2477
pinging @thyttan and @peerdavid
> Update clock_info, fix [BW clock]

- apps/stopwatch/ChangeLog
- apps/stopwatch/metadata.json
- apps/stopwatch/stopwatch.app.js
This keeps the Stopwatch Touch running in the background.
I sometimes accidentally pressed the hw-button which killed the timer.
Notify @hughbarney
> stopwatch: Save state to storage

- apps/ha/ChangeLog
- apps/ha/README.md
- apps/ha/ha.app.js
- apps/ha/metadata.json
- Allow swiping to switch triggers
- Standardize spellings
> Home Assistant: Allow swiping to switch triggers, standardize spellings

- apps/bwclk/ChangeLog
- apps/bwclk/app.js
- apps/bwclk/metadata.json
#2478 #2196
Works well for me with Screen: Normal, Dynamic and Full.
> [BW Clock] use widget_utils

- apps/90sclk/ChangeLog
- apps/90sclk/app.js
- apps/90sclk/metadata.json
- apps/daisy/ChangeLog
- apps/daisy/app.js
- apps/daisy/metadata.json
- apps/lcars/ChangeLog
- apps/lcars/lcars.app.js
- apps/lcars/metadata.json
- apps/limelight/ChangeLog
- apps/limelight/limelight.app.js
- apps/limelight/metadata.json
- apps/neonx/ChangeLog
- apps/neonx/metadata.json
- apps/neonx/neonx.app.js
- apps/notanalog/ChangeLog
- apps/notanalog/metadata.json
- apps/notanalog/notanalog.app.js
- apps/thering/ChangeLog
- apps/thering/app.js
- apps/thering/metadata.json
- apps/widviz/ChangeLog
- apps/widviz/metadata.json
- apps/widviz/widget.js
- apps/widviztime/ChangeLog
- apps/widviztime/metadata.json
- apps/widviztime/widget.js
I've converted the remaining clocks and widgets in #2196 to use widget utils.
I have not tested any of them and don't really intend to. If someone feels up for it please go ahead.
Especially widviz and widviztime I don't know if I've messed up or if they are ok. I can drop them from the PR if that's better.
For the others I feel it could be ok to merge them and if bugs come up we can fix them then?
> [lcars/notanalog/limelight/daisy/thering/widviz/90sclk/widviztime/neonx] Add widget utils

- apps/berlinc/ChangeLog
- apps/berlinc/berlin-clock.js
- apps/berlinc/metadata.json
This is a draft since I did not yet thoroughly test for memory leaks. The changes seem simple enough though ;)
> Berlin clock - Enable fast loading

- apps/gpsinfo/ChangeLog
- apps/gpsinfo/gps-info.js
- apps/gpsinfo/metadata.json
As written in https://forum.espruino.com/conversations/382632/#comment16830755
> GPS Info: Fix number of packets received

- apps/espruinoctrl/ChangeLog
- apps/espruinoctrl/custom.html
- apps/espruinoctrl/metadata.json
Disable not existing BTN3 on Bangle.js 2, set maximum transmit power
> espruinoctrl updates for Bangle.js 2

- apps/2047pp/2047pp.app.js
- apps/2047pp/ChangeLog
- apps/2047pp/metadata.json
Wrapping the whole app in a scope seems to be enough to fix the TwoK class missing after minification.
> 2047pp - Workaround for the minifier removing the class definition

- apps/entonclk/ChangeLog
- apps/entonclk/app.js
- apps/entonclk/metadata.json
Next week I will take time to implement clock_info into my watchface. For now, I have simply adjusted the data for HRM.
> [entonclk] For now, just return the really needed HRM reading

- loader.js
Can potentially fix https://forum.espruino.com/conversations/383162/#comment16836383
But why this happens for the user Hank is not clear to me.
> Fix potential NPE in loader.js

- apps/agenda/ChangeLog
- apps/agenda/agenda.clkinfo.js
- apps/agenda/metadata.json
Just like with sched, this is just to have the progress bar changing (visible for active events in circlesclock), not yet about changing the array when events change, which could be much more involving, as you mentioned once in the forum already.
> agenda: added color field and updating clkinfo periodically

- apps/magnav/ChangeLog
- apps/magnav/lib.js
- apps/magnav/magnav_b1.js
- apps/magnav/magnav_b2.js
- apps/magnav/metadata.json
- apps/waypointer/ChangeLog
- apps/waypointer/app.js
- apps/waypointer/metadata.json
and let waypointer use the lib
Notify @jeffmer @hughbarney
> magnav: Outsource tilt compensation to library

- modules/clock_info.js
May be questionable but i put a range for altitude to be displayed by clocks and let the focused item in `addInteractive` once the screen locks.
> Some changes to the clkinfo

- modules/Layout.js
- modules/Layout.md
These changes provide an option for users to select the color of the buttons (both background and border).
> Updated Layout.js

- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/metadata.json
- apps/widalarmeta/ChangeLog
- apps/widalarmeta/metadata.json
- apps/widalarmeta/widget.js
widalarmeta: Fix Bell not appearing on alarms > 24h and redrawing interval
sleepphasealarm: Fix dated events alarm on wrong date
> widalarmeta & sleepphasealarm fixes

- apps/hwid_a_battery_widget/metadata.json
- apps/wid_a_battery_widget/metadata.json
- apps/widbatpc/ChangeLog
- apps/widbatpc/metadata.json
- apps/widbatpc/settings.js
- apps/widbatpc/widget.js
Add option 'Remove Jitter'='Drop only' to prevent percentage from getting up again when not charging
> widbatpc remove jitter option

- apps/terminalclock/ChangeLog
- apps/terminalclock/app.js
- apps/terminalclock/metadata.json
Add default HRM and altitude value (less precise but allow to show something quickly instead of waiting for a while)
There is also a lot of refactoring to add the fast loading in the future. However it's not enabled yet cause of a memory leak I am unable to fix. The refactor is here in case I get an eureka moment of if someone want to finish to implement it.
> [TerminalClock] Add default HRM and altitude value

- apps/lightswitch/README.md
- apps/lightswitch/settings.js
- apps/lightswitch/widget.js
This adds a "tap to lock" option for the lightswitch widget (and trims whitespace in affected files)
> Lightswitch tapToLock

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/metadata.json
> iconlaunch - Bump version

- apps/qcenter/ChangeLog
- apps/qcenter/app.js
- apps/qcenter/metadata.json
- apps/qcenter/settings.js
This implements a configurable timeout to go back to the clock.
> qcenter - Allow going back to clock on timeout

- apps/sched/interface.html
- apps/sched/metadata.json
- Edit or delete existing events, add new
- Only date, time & message
- Add events from iCalendar file
> sched: add interface.html

- apps/powermanager/ChangeLog
- apps/powermanager/metadata.json
- apps/powermanager/settings.js
Back button for the main menu is added with this PR.
> [Power manager] back button for settings main menu

- apps/widalarmeta/ChangeLog
- apps/widalarmeta/metadata.json
- apps/widalarmeta/widget.js
Fix check for active alarm, either remove brackets or add return for filter in map
> widalarmeta: fix #2542

- apps/agenda/ChangeLog
- apps/agenda/agenda.js
- apps/agenda/metadata.json
- lang/it_IT.json
Also fixed some layout and added a couple of Italian translations
> agenda: show day of the week in date

- apps/tempgraph/ChangeLog
- apps/tempgraph/app.js
- apps/tempgraph/metadata.json
Update to tempgraph app - see ChangeLog.
Carl.
> Update to Temperature Graph

- apps/boot/ChangeLog
- apps/boot/bootupdate.js
- apps/boot/metadata.json
- apps/setting/ChangeLog
- apps/setting/README.md
- apps/setting/metadata.json
- apps/setting/settings.js
- apps/simplest/simplest.app.js
I have attempted to modify settings app and bootupdate.js to handle debug settings
so that you can have 0=off, 1=display, 2=log, 3=both
I have tested but still get stuff drawn on the screen using log when there should be no output to the screen
so not 100% that I have covered all the bases.
Pull request so you have have a look at my code.
> Settings.log, off,display,log, both

- apps/widbgjs/ChangeLog
- apps/widbgjs/README.md
- apps/widbgjs/metadata.json
- apps/widbgjs/settings.js
- apps/widbgjs/widget.js
Fixed wrong filename in settings.
> Widbgjs update to 0.02

- apps/widdevst/ChangeLog
- apps/widdevst/metadata.json
- apps/widdevst/wid.js
see https://github.com/espruino/BangleApps/pull/2583#issuecomment-1436800917
> app widdevst: added support for Bangle.js 2

- apps/powermanager/ChangeLog
- apps/powermanager/README.md
- apps/powermanager/boot.js
- apps/powermanager/default.json
- apps/powermanager/interface.html
- apps/powermanager/metadata.json
- apps/powermanager/settings.js
- apps/powermanager/widget.js
This tries to record information to help diagnose abnormal power use. ~~The values for the activated sensors still seem a bit off and there are some unintended effects when fastloading apps~~.
> powermanager - Add logging of power heavy things

- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/metadata.json
- apps/sleepphasealarm/settings.js
because it was
`format: v => v?"No":"Yes",`
> sleepphasealarm: Fix inverted setting

- apps/powermanager/ChangeLog
- apps/powermanager/README.md
- apps/powermanager/boot.js
- apps/powermanager/metadata.json
- apps/powermanager/widget.js
* Fixes of by one error in indexing the arguments for the wrapped function. This causes the timeout to be given as first argument to functions instead of the actual first argument.
* Fixes widget drawing even if hidden
> Powermanager - Fix wrapping

- apps/widalarmeta/ChangeLog
- apps/widalarmeta/metadata.json
- apps/widalarmeta/widget.js
Remember next alarm to reduce calculation amount
Redraw only every hour when no alarm in next 24h
> widalarmeta: use less cpu time each minute

- apps/iconlaunch/ChangeLog
- apps/iconlaunch/app.js
- apps/iconlaunch/metadata.json
> [app/iconlauncher] fix fullscreen with oneClickExit

- apps/openstmap/ChangeLog
- apps/openstmap/README.md
- apps/openstmap/app.js
- apps/openstmap/metadata.json
If waypoints module is available, display the waypoints on the map. Also update the documentation and fix some english in the documentation.
> openstmap: display waypoints

- apps/hrmmar/ChangeLog
- apps/hrmmar/README.md
- apps/hrmmar/boot.js
- apps/hrmmar/fftelim.js
- apps/hrmmar/metadata.json
- apps/hrmmar/settings.js
- Disable when bthrm is active
- Enable fft elim as default
> hrmmar: bthrm compatibility

- apps/grocery/interface.html
no version update since app is unchanged.
> grocery interface: Automatically scroll down on add

- apps/chargent/ChangeLog
- apps/chargent/boot.js
- apps/chargent/metadata.json
See https://github.com/espruino/BangleApps/pull/2680 for the use case and original idea.
Thanks @bobrippling
> chargent: notification

- apps/messages_light/ChangeLog
- apps/messages_light/messages_light.app.js
- apps/messages_light/metadata.json
commented out of the old code (it could be useful during the re-implementation of the music interface)
#2689
> fix for #2689

- apps/widalarmeta/ChangeLog
- apps/widalarmeta/metadata.json
- apps/widalarmeta/settings.js
- apps/widalarmeta/widget.js
Allow to select between bitmap and teletext font. Allow to disable the hour padding.
> widalarmeta: Selectable font. Optional hour padding.

- apps/bwclk/ChangeLog
- apps/bwclk/app.js
- apps/bwclk/metadata.json
... to extend all the way to the right.
> [BW Clock] make clock_info border one pixel wider

- apps/bwclklite/ChangeLog
- apps/bwclklite/app.js
- apps/bwclklite/metadata.json
... to extend all the way to the right.
> [BW Clock lite] make clock_info border one pixel wider

- apps/glbasic/ChangeLog
- apps/glbasic/glbasic.app.js
- apps/glbasic/metadata.json
Changed font, so '5' and '6' don't look similar.
> Updated glbasic clock

- apps/powermanager/ChangeLog
- apps/powermanager/metadata.json
- apps/ratchet_launch/app.js
@jsphpl hope this is ok - I've added app caching (taken from the launcher app) to the ratcher launcher
> Ratchet launch: add caching

- apps/widalarmeta/ChangeLog
- apps/widalarmeta/metadata.json
- apps/widalarmeta/settings.js
- apps/widalarmeta/widget.js
- Change 4x5 font to more readable 6x8 2xheight
- teletext is now default font
- reload widget on settings change
> widalarmeta: font 4x5 -> 6x8:1x2

- apps/widtemp/ChangeLog
- apps/widtemp/metadata.json
Disallow emulator as the emu link links to a non-existent resource
> Disallow emulator

- apps/shadowclk/interface.html
Lots of fixes, fairly reliable now.
GadgetBridge throws a "Malformed JSON from Bangle.js: No value for t"
> Update interface.html for shadowclk

- apps/popconlaunch/ChangeLog
- apps/popconlaunch/README.md
- apps/popconlaunch/boot.js
- apps/popconlaunch/boot.ts
- apps/popconlaunch/metadata.json
Just to stop the storage/cache potentially filling up with old unused apps
> popcon: trim old entries from the cache

- typescript/types/sched.d.ts
[The docs example](./apps/sched/README.md)
> Tweaks to sched.d.ts to type-check the docs example

- apps/powermanager/ChangeLog
- apps/powermanager/boot.js
- apps/powermanager/interface.html
- apps/powermanager/metadata.json
- apps/powermanager/settings.js
* Use charging state on boot
* Tables for trace log and deferred calls are now horizontally scrollable
* Tracing logs timestamp
* Better formatting for tracing table
> Powermanager - Tweaks

- apps/shadowclk/app.js
- apps/shadowclk/interface.html
- apps/shadowclk/settings.js
Still has comm issues sometimes. I haven't looked into it too much yet since it still mostly works. Last I saw it was getting stuck between comms.js and puck.js
> +settings for UI, less IO r/w, rm timeout from eval

- apps/pebblepp/metadata.json
Sorry for last PR, forgot to make branch
Solves #2769
> Add clockinfo dependency to pebblepp app

- apps/popconlaunch/ChangeLog
- apps/popconlaunch/boot.js
- apps/popconlaunch/boot.ts
- apps/popconlaunch/metadata.json
- apps/popconlaunch/settings.js
- apps/popconlaunch/settings.ts
Some little usability tweaks to the tool
> popcon: add reset ability and don't advertise as a launcher

- apps/pebbled/ChangeLog
- apps/pebbled/metadata.json
- apps/pebbled/pebbled.app.js
- apps/pebbled/pebbled.settings.js
- added option for miles and AM/PM time as per request
> feat: localisation pebbled

- apps/shadowclk/ChangeLog
- apps/shadowclk/app.js
- apps/shadowclk/metadata.json
- apps/shadowclk/settings.js
Updated the app the work with changes made in https://github.com/espruino/BangleApps/pull/2788
> [shadowclk] - Better settings and hour formatting

- apps/chimer/ChangeLog
- apps/chimer/metadata.json
- apps/chimer/widget.js
@aaronrolls would you mind if I published an MR like this to tweak the busy-loop in chimer? I've also generalised the logic for deciding how long to wait for the next hourly/half-hourly/etc chime, if that looks ok to you?
> chimer: use async for chime delay, generalise next-chime logic

- apps/sunrise/ChangeLog
- apps/sunrise/README.md
- apps/sunrise/app.js
- apps/sunrise/metadata.json
* Transition animations
* Fix glitch in minutes
* Always show the widgets
* Lighter sea line
* Show day and month
* Fix bug when mylocation is not installed (emulator)
* More precise sun and finger location
> Improved sunrise watchface

- apps/kbmatry/ChangeLog
- apps/kbmatry/lib.js
- apps/kbmatry/metadata.json
Pretty self explanatory!
Small fix implementing widget utils show / hide to prevent widgets drawing through / behind the fullscreen keyboard.
> kbmatry1.07 Fix glitchy widget showthrough

- apps/podadrem/ChangeLog
- apps/podadrem/app.js
- apps/podadrem/metadata.json
reference: https://github.com/espruino/BangleApps/commit/ba7a2f79968ed26d3caa8ac2821e07856369e60e
> podadrem: Issue newline before GB commands

- apps/swscroll/ChangeLog
- apps/swscroll/boot.js
- apps/swscroll/metadata.json
... by more properly rebasing on latest E_showScroller_Q3.js from Espruino.
> swscroll: fix check boxes not behaving

- apps/chargent/ChangeLog
- apps/chargent/boot.js
- apps/chargent/metadata.json
Fixes boot so resetting the watch doesn't disable chargent.
https://notevil.github.io/BangleApps/?q=chargent
> chargent: fixed boot

- apps/rep/ChangeLog
- apps/rep/app.js
- apps/rep/app.ts
- apps/rep/interface.html
- apps/rep/metadata.json
Two fixes - one to the interface (copied from sched) and the other to the app, where listeners weren't installed after the recorder prompt.
> rep: interface & recorder fixes

- apps/keytimer/ChangeLog
- apps/keytimer/keypad.js
- apps/keytimer/metadata.json
- apps/keytimer/timerview.js
* Use theme colors
* Center icons on timer view buttons
> keytimer - Visual tweaks

- apps/openstmap/ChangeLog
- apps/openstmap/app.js
- apps/openstmap/metadata.json
- Draw a current position marker as mentioned in #2847 (Bangle.js 2 only)
- Enable/Disable previous position marker in new setting "Draw cont. position"
-  Add exit to menu
> openstmap: current position overlay

- apps/flashcards/ChangeLog
- apps/flashcards/README.md
- apps/flashcards/app.js
- apps/flashcards/flashcards.settings.json
- apps/flashcards/metadata.json
- apps/flashcards/settings.js
Code refactored to support fast load
> Fix fast-loading support

- apps/openstmap/ChangeLog
- apps/openstmap/app.js
- apps/openstmap/metadata.json
Replace position marker with direction arrow
see #2881
> openstmap location + direction arrow

- android.html
- index.html
This adds the UI for https://github.com/espruino/EspruinoAppLoaderCore/pull/50
> apploader - Adds button for screenshots

- apps/miclock2/ChangeLog
- apps/miclock2/clock-mixed.js
- apps/miclock2/metadata.json
- Register as clock (setui)
- Implement fast loading
- minor speed improvements
> miclock2 maintenance

- apps/widshipbell/ChangeLog
- apps/widshipbell/metadata.json
Load new buzz.js - see 2b6f7765cc69db5e8dd34fa9ad86051914e26601
> widshipbell: Bump version as commit 2b6f776

- apps/wid_edit/ChangeLog
- apps/wid_edit/boot.js
- apps/wid_edit/metadata.json
This removes a second sort from `widedit`
> widedit optimisation

- apps/astrocalc/ChangeLog
- apps/astrocalc/astrocalc-app.js
- apps/astrocalc/metadata.json
> astrocalc: Enable widgets

- apps/widbaroalarm/ChangeLog
- apps/widbaroalarm/metadata.json
- apps/widbaroalarm/widget.js
Adds Widget on initialization, before widget_utils replaces the draw method.
> widbaroalarm: Compatibility with hideable Widgets

- apps/rescalc/ChangeLog
- apps/rescalc/app.js
- apps/rescalc/metadata.json
This update not only enhances code efficiency and readability, but it also rectifies previous inaccuracies in converting resistance values to color bands, specifically those involving decimal resistances.
> [rescalc] - v0.04 update

- apps/kbmulti/ChangeLog
- apps/kbmulti/lib.js
- apps/kbmulti/metadata.json
Reference and closes https://github.com/espruino/BangleApps/issues/2910
Tested on fw 2v18.115.
> kbmulti: Compatability with `backswipe` on newer firmwares

- apps/dragboard/ChangeLog
- apps/dragboard/lib.js
> dragboard: autoindent lib.js and fix ChangeLog

- apps/draguboard/ChangeLog
- apps/draguboard/lib.js
- apps/draguboard/metadata.json
Reference https://github.com/espruino/BangleApps/pull/2934 and https://github.com/espruino/BangleApps/issues/2910.
This should work, does in the testing I've done on fw 2v18.115. Also shouldn't break on older firmwares if I did things right (not tested).
> draguboard: Compat w backswipe on newer firmwares

- apps/wid_edit/ChangeLog
- apps/wid_edit/boot.js
- apps/wid_edit/metadata.json
- apps/wid_edit/settings.js
> wid_edit: restore alphabetical sort

- apps/kbtouch/ChangeLog
- apps/kbtouch/lib.js
- apps/kbtouch/metadata.json
Reference https://github.com/espruino/BangleApps/pull/2934 and https://github.com/espruino/BangleApps/issues/2910.
> kbtouch: Compat w backswipe on newer firmwares

- apps/kbswipe/ChangeLog
- apps/kbswipe/lib.js
- apps/kbswipe/metadata.json
Reference https://github.com/espruino/BangleApps/pull/2934 and https://github.com/espruino/BangleApps/issues/2910.
> kbswipe: Compat w backswipe on newer firmwares

- apps/calendar/ChangeLog
- apps/calendar/calendar.js
- apps/calendar/metadata.json
- apps/calendar/settings.js
settings: Implement code to edit holidays on device
app: Only refactoring, no changed functionality
> Calendar: Edit holidays on device in settings

- apps/btadv/ChangeLog
- apps/btadv/app.js
- apps/btadv/app.ts
- apps/btadv/metadata.json
Add accelerometer adverts and sensor location to `btadv`
Closes #2907
> btadv: sensor location & accelerometer adverts

- apps/usgs/ChangeLog
- apps/usgs/README.md
- apps/usgs/app.js
- apps/usgs/metadata.json
- apps/usgs/settings.js
Edited menu items to reflect actual functionality, instead of "my first app" names that were present.
Added button interactions, 1 press to refresh data, 2 presses to return to launcher.
> USGS v0.02

- apps/poweroff/ChangeLog
- apps/poweroff/app.js
- apps/poweroff/metadata.json
Small edit of the Poweroff app to add a prompt and prevent accidental shutdown
> Add prompt before shutdown

- apps/calendar/interface.html
- apps/sched/interface.html
> sched/calendar: Interface ical fixes

- apps/astrocalc/ChangeLog
- apps/astrocalc/astrocalc-app.js
- apps/astrocalc/metadata.json
- Fixes #2651 azimuth value: 0° is south, so add 180°
- Show all values in degrees
> astrocalc azimuth fixes

- apps/fastreset/ChangeLog
- apps/fastreset/README.md
- apps/fastreset/boot.js
- apps/fastreset/metadata.json
I've been using this change for some weeks. The snappiness is nice.
> fastreset: shorten the timeout to execution

- apps/cards/README.md
Since now GB supports the feature, I added it in the readme.
> cards: updated docs about synchronization

- apps/tetris/ChangeLog
- apps/tetris/README.md
- apps/tetris/metadata.json
- apps/tetris/tetris.app.js
Implement control by clicking, move down more by my click, and actually implement game over. Plus update metadata to display README and allow running in emulator.
> tetris: Better controls and game over

- apps/astral/ChangeLog
- apps/astral/app.js
- apps/astral/metadata.json
had a needless while loop in here, which is now replaced by a one liner that makes it update much faster.
> Astral clock update

- apps/multiclock/ChangeLog
- apps/multiclock/dk.face.js
- apps/multiclock/metadata.json
... when switching to the "dk "clock face.
Closes https://github.com/espruino/BangleApps/issues/1690
> multiclock: fix widget field flashing

- apps/recorder/ChangeLog
- apps/recorder/interface.html
- apps/recorder/metadata.json
Hi
This is my first contribution to this repository. If there is anything I missed, please let me know.
This PR adds cadence data to the GPX output file
> Add cadence data to `recorder` app

- apps/tetris/ChangeLog
- apps/tetris/metadata.json
- apps/tetris/tetris.app.js
Implement level selection, and allow user to select controls.
> tetris: implement level/mode selection

- apps/stacker/README.md
- apps/stacker/metadata.json
(I'm not increasing version number, as no code changed.)
> stacker: Add documentation, allow on emulator.

- apps/waypoint_editor/ChangeLog
- apps/waypoint_editor/app.js
- apps/waypoint_editor/metadata.json
Plus some cleanups as a bonus.
I wanted to ask: would it be okay to merge this with "waypoints" app? app.js file is small enough that keeping them separate is just complicating things and taking more resources...
> waypoint_editor: allow text waypoint names, allow marking current GPS position

- apps/setting/ChangeLog
- apps/setting/metadata.json
> setting: bump version and ChangeLog

- apps/contacts/interface.html
- apps/contacts/metadata.json
Uses https://github.com/jhermsmeier/node-vcf to parse vcard files
Notify @pavelmachek
> contacts: Add vcard import/export to interface.html

- apps/recorder/ChangeLog
- apps/recorder/metadata.json
- apps/recorder/widget.js
Resolves a small issue with #3081, see [commit comments](https://github.com/espruino/BangleApps/commit/dd96e33774bee9c0ce0aea9ffe336ce18a0d631c#r132592068) for more detail
Closes #3081
> recorder: don't prompt the user when the columns change - force new file

- apps/messages_light/ChangeLog
- apps/messages_light/messages_light.app.js
- apps/messages_light/messages_light.listener.js
- apps/messages_light/metadata.json
this change fixes a problem related to js.
until recently this code worked:
var a=[];
//add something to "a"
a.length = 0; // to remove all elements
now it doesn't work anymore.
(I replaced with splice)
> messages_light: Fix js issues

- apps/openstmap/ChangeLog
- apps/openstmap/app.js
- apps/openstmap/metadata.json
- apps/openstmap/openstmap.js
- apps/widmp/ChangeLog
- apps/widmp/metadata.json
- apps/widmp/widget.js
openstmap: Display message if no map is installed
widmp: Fix variable declaration
> openstmap & widmp fixes

- apps/lcars/ChangeLog
- apps/lcars/README.md
- apps/lcars/lcars.app.js
- apps/lcars/lcars.settings.js
- apps/lcars/metadata.json
This update of LCARS v0.30 introduces:
- Over 20 new colors
- Selection of Random Colors Functionality
- Adding in missing semicolons
> LCARS Clock v0.30 (Adds More Colors/ Random Color Selection/ Bug Fixes)

- apps/calclock/ChangeLog
- apps/calclock/calclock.js
- apps/calclock/metadata.json
> CalClock: No buzz during quiet hours

- apps/chess/ChangeLog
- apps/chess/app.js
- apps/chess/metadata.json
instead of Bangle.setLCDTimeout() to turn off the LCD while the computer is thinking.
> chess: Use Bangle.setBacklight()

- apps/tetris/ChangeLog
- apps/tetris/README.md
- apps/tetris/metadata.json
- apps/tetris/tetris.app.js
Bring back old controls as "swipe" in menu
Also now exits with short button press
> tetris: Reimplement original controls

- apps/dragboard/ChangeLog
- apps/dragboard/lib.js
- apps/dragboard/metadata.json
Hi
In the "dragboard", the touch region (upper bound) for selecting letters is not aligned with the rectangle for it - see line 38:
```
g.fillRect(0, (R.y+R.h)-26, (R.x+R.w), (R.y+R.h));
```
This fix will make it much easier to select letters.
> Fix dragboard

- apps/fwupdate/custom.html
> fwupdate: don't reset the watch after upload

- apps/tetris/ChangeLog
- apps/tetris/metadata.json
- apps/tetris/tetris.app.js
I've been enjoying this game on my Bangle.js (in fact, I usually only play tetris and chess on it), and the changes @nxdefiant were enough to finally encourage me to work on it :)
I've added scoring, levels, pausing, bugfixes and misc, inspired by NES tetris.  This can use some more testing, but it seems to be working currently.
> tetris: major overhaul

- apps/drained/ChangeLog
- apps/drained/app.js
- apps/drained/app.ts
- apps/drained/metadata.json
> drained: improve escape menu and remove clock type+tag

- apps/openstmap/ChangeLog
- apps/openstmap/app.js
- apps/openstmap/interface.html
- apps/openstmap/metadata.json
- apps/openstmap/openstmap.js
- Fixes #3167 
- interface.html: Fix show maps after delete
- interface.html: sort maps
- interface.html: Load leaflet after all maps are painted which avoids the timeout
- interface.html: Show map bounds according to uploaded size.
> openstmap: Fix rounding errors

- apps/3dclock/metadata.json
> Fix a typo

- apps/myprofile/interface.html
- apps/myprofile/metadata.json
Just a very basic interface to start with!
cc @nxdefiant
> Add ability to upload/download My Profile data

- apps/medicalinfo/ChangeLog
- apps/medicalinfo/README.md
- apps/medicalinfo/app.js
- apps/medicalinfo/lib.js
- apps/medicalinfo/medicalinfo.json
- apps/medicalinfo/metadata.json
- apps/myprofile/ChangeLog
- apps/myprofile/README.md
- apps/myprofile/metadata.json
- apps/myprofile/settings.js
- Adds weight to myprofile
- Read height + weight from myprofile in medicalinfo
Fixes #3164
> medicalinfo: Read height + weight from myprofile

- apps/widadjust/ChangeLog
- apps/widadjust/metadata.json
- apps/widadjust/settings.js
- apps/widadjust/widget.js
> widadjust: Add option to hide widget

- apps/chess/ChangeLog
- apps/chess/app.js
- apps/chess/metadata.json
Add option to buzz after computer move
> chess: buzz/cleanup

- package-lock.json
- package.json
Otherwise the `local` and `start` npm scripts do not work :)
> Add http-server dependency

- apps/swipeinv/README.md
- apps/swipeinv/metadata.json
as mentioned on https://github.com/espruino/BangleApps/pull/3217#issuecomment-1967819333
@nxdefiant @jt-nti
> swipeinv: add README

- apps/multitimer/ChangeLog
- apps/multitimer/app.js
- apps/multitimer/metadata.json
- apps/multitimer/settings.js
This also updates `multitimer.json` to hold settings as well as stopwatches.
@frigis1 is this change ok by you? No change in behaviour by default
> multitimer: add setting for initial screen

- apps/multitimer/settings.js
Fixes multitimer settings, as in #3224
> multitimer: fix settings

- apps/cscsensor/ChangeLog
- apps/cscsensor/cscsensor.app.js
- apps/cscsensor/metadata.json
Also lower connection interval for more stable connect.
> cscsensor: Automatically reconnect on error

- apps/cards/ChangeLog
- apps/cards/app.js
- apps/cards/metadata.json
- apps/cards/settings.js
Added an option to use full brightness when showing code
> Cards App added brightness option

- apps/folderlaunch/ChangeLog
- apps/folderlaunch/README.md
- apps/folderlaunch/interface.html
- apps/folderlaunch/metadata.json
Web interface still can not do everything settings on phone can, still it is very useful to sort applications between folders.
> folderlauncher: add a way to move apps between folders from web interface

- apps/calculator/README.md
The previous one was missing information
> Update calculator README

- modules/Slider.js
exFirst -> o.v.exFirst
eyFirst -> o.v.eyFirst
Suggested here: https://github.com/espruino/BangleApps/pull/3259#discussion_r1524804030
> Slider:fix lint warn var declared in global scope

- .eslintignore
- apps/lint_exemptions.js
- apps/schoolCalendar/fullcalendar/main.js
Now that you have an exemption system, I see no reason to have files listed in the eslint ignore file :)
> Move eslint ignored files to the exemption system

- apps/sleepphasealarm/ChangeLog
- apps/sleepphasealarm/app.js
- apps/sleepphasealarm/interface.html
- apps/sleepphasealarm/metadata.json
- apps/sleepphasealarm/settings.js
Fix handle dates saved as object with milliseconds
see https://forum.espruino.com/comments/17322019/
> sleepphasealarm: Fix json dates

- apps/alarm/ChangeLog
- apps/alarm/app.js
- apps/alarm/metadata.json
- apps/sched/ChangeLog
- apps/sched/lib.js
- apps/sched/metadata.json
- apps/sched/sched.js
Fix wrap around when snoozed through midnight.
> alarm, sched: Fix #3281

- apps/activityreminder/lib.js
See https://github.com/espruino/BangleApps/issues/3284
> Fix new date format

- apps/widmsggrid/ChangeLog
- apps/widmsggrid/metadata.json
- apps/widmsggrid/widget.js
... when the circle containing single digit numbers was drawn.
> widmsggrid: fix drawing outside of widget field

- apps/vpw_clock/ChangeLog
- apps/vpw_clock/app.js
- apps/vpw_clock/metadata.json
- apps/vpw_clock/settings.js
Here is the memory leak test I did:
everything seems ok.
let me know if some adjustments must be made
> Handle fast loading for Vaporwave Sunset Clock

- apps/rellotge/ChangeLog
- apps/rellotge/metadata.json
- apps/rellotge/rellotge.js
Rellotge app: Better wrapping of the text base (dynamic instead of hardcoded)
> Better wrapping of the text base (dynamic instead of hardcoded)

- apps/launch/ChangeLog
- apps/launch/app.js
- apps/launch/metadata.json
- apps/lint_exemptions.js
Commit 9cbcff08ac20efe55ceb6b5e45addc7f29397ebe removed the `drawMenu` function, but did not remove the call to `drawMenu` on line 62. This means that the `App source not found` message would never go away by itself.
This fix restores the old behavior of removing the `App source not found` message after 2 seconds.
> `launch` Fix broken reset

- apps/lint_exemptions.js
- apps/taglaunch/ChangeLog
- apps/taglaunch/app.js
- apps/taglaunch/metadata.json
Porting over the fix from #3319 to `taglaunch` which seems to have the same problem.
I have tested the changes and cannot seem to find any breakage with this fix. It seems like @nxdefiant might want to review this one before it gets merged :)
> `taglaunch` Fix broken reset

- apps/activityreminder/ChangeLog
- apps/activityreminder/metadata.json
... to notfiy users of this fix:
https://github.com/espruino/BangleApps/pull/3286
https://github.com/espruino/BangleApps/issues/3284
> activityreminder: bump version

- apps/lint_exemptions.js
- apps/sleeplog/ChangeLog
- apps/sleeplog/app.js
- apps/sleeplog/boot.js
- apps/sleeplog/lib.js
- apps/sleeplog/metadata.json
- apps/sleeplog/settings.js
The exemption for these files were broken in #3280 but the warnings were not fixed.
I have tried to test these changes as best I could, and I cannot find any issue with them. Maybe @storm64 or @ishidres would be willing to test and confirm that this works well :)
> `sleeplog` Fix lint warnings

- apps/clockcal/ChangeLog
- apps/clockcal/app.js
- apps/clockcal/metadata.json
- apps/clockcal/settings.js
no-undef
I think these changes should be fine. Will test it on my watch as well.
Edit: works on my watch.
> clockcal: fix lint warnings

- apps/counter2/ChangeLog
- apps/counter2/app.js
- apps/counter2/metadata.json
- apps/counter2/settings.js
I have not tested these changes on the watch. But they seem innocent enough to me.
Edit: Works on my watch.
> counter2: fix lint warnings

- apps/counter2/ChangeLog
- apps/counter2/app.js
- apps/counter2/metadata.json
#3330 missed one issue
I have tested this change and it all seems to work
> `counter2` Fix memory leak

- apps/teatimer/ChangeLog
- apps/teatimer/README.md
- apps/teatimer/app.js
- apps/teatimer/metadata.json
- add newline to header so time is not split
- save counter before leaving the help screen, so it does not get reset
> TeaTimer 0.6

- apps/messagesoverlay/ChangeLog
- apps/messagesoverlay/README.md
- apps/messagesoverlay/default.json
- apps/messagesoverlay/lib.js
- apps/messagesoverlay/metadata.json
- apps/messagesoverlay/settings.js
* Renders short messages in big font and centered up to as many lines as fit
* Longer messages are all rendered in smaller font on all their pages to keep them consistent
* Adds Settings
* Messages can be cleared automatically when bangle is locked
* Adds visual indicator for multiple messages in queue
> messagesoverlay - Rendering and UI improvements

- apps/rellotge/ChangeLog
- apps/rellotge/metadata.json
- apps/rellotge/rellotge.js
New version: 0.80: Add analog watch, steps and date
> Add analog watch, steps and date

- typescript/types/clock_info.d.ts
... by reusing the `Image` type
> clock_info.d.ts: improve `img` type

- apps/kbmulti/ChangeLog
- apps/kbmulti/lib.js
- apps/kbmulti/metadata.json
- apps/kbmulti/settings.js
This turns caps back on if we clear the input (to match the initial state) and adds a setting to vibrate on interaction
> kbmulti: reset caps when empty and add vibrate setting

- apps/widChargingStatus/ChangeLog
- apps/widChargingStatus/metadata.json
- apps/widChargingStatus/widget.js
- apps/widChargingStatus/widget.ts
- typescript/types/main.d.ts
This buzzes after a slight delay, to allow other "charging" handlers to run and not interrupt the buzz.
> chargingstatus: also buzz on disconnect from charging

- apps/autoreset/ChangeLog
- apps/autoreset/README.md
- apps/autoreset/boot.js
- apps/autoreset/metadata.json
- apps/autoreset/settings.js
- black-/whitelist
- timeout length
> autoreset: add settings

- apps/widdevst/ChangeLog
- apps/widdevst/metadata.json
- apps/widdevst/wid.js
See #3397 / discussion at the end
> widdevst: fix default, keep original behaviour

- apps/fuzzyw/ChangeLog
- apps/fuzzyw/README.md
- apps/fuzzyw/fuzzyw.app.js
- apps/fuzzyw/fuzzyw.settings.js
- apps/fuzzyw/metadata.json
I didn't like the animation on the text, so I made it possible to turn it off.
In addition I made settings actually work, so now widgets work as well. I also made hours work properly with pretokenisation (probably – sometimes it worked, sometimes it didn't, maybe the fix is the same and I've just been lucky), and finally added a lot of small things like proper indentation, definition of all variables and adding semicolons.
> fuzzyw: add toggle for animation + minor bug fixes

- apps/run/ChangeLog
- apps/run/metadata.json
- apps/runplus/ChangeLog
- apps/runplus/metadata.json
- modules/exstats.js
Reverts espruino/BangleApps#3384 based on https://github.com/espruino/BangleApps/pull/3384#issuecomment-2103417007
> Revert "exstats: fix steps being negative"

- apps/run/ChangeLog
- apps/run/metadata.json
- apps/runplus/ChangeLog
- apps/runplus/metadata.json
- modules/exstats.js
Based on https://github.com/espruino/BangleApps/pull/3384#issuecomment-2105149925
> Re-add "exstats: fix steps being negative"

- .eslintignore
- .eslintrc.js
- apps/.eslintrc.js
- apps/lint_exemptions.js
- bin/sync-lint-exemptions.mjs
- modules/ble_advert.ts
This follows on from https://github.com/espruino/BangleApps/pull/3390#discussion_r1590348186 and allows us to automatically ignore any typescript-generated files
> Generate js ignores automatically

- apps/runplus/ChangeLog
- apps/runplus/README.md
- apps/runplus/app.js
- apps/runplus/metadata.json
This allows users to focus on a particular stat - I found when I was running that I couldn't glance at my pace very easily, whereas with this I can leave the pace zoomed/focused as I run.
@halemmerich @thyttan I think you're the main contributors to `runplus`, what do you think?
> runplus: add ability to focus an individual stat

- apps/contacts/ChangeLog
- apps/contacts/contacts.app.js
- apps/contacts/metadata.json
- Refactored contacts app
- Added function to trigger calling a contact on the phone (Requires GadgetBridge with "Allow Intent" permission)
> Contacts 0.04: Added call function to contacts app, Refactoring

- apps/promenu/ChangeLog
- apps/promenu/bootb2.js
- apps/promenu/bootb2.ts
- apps/promenu/metadata.json
A small bug that crept in as part of #3416
> promenu: fix removal of final menu item

- modules/more_pickers.js
- modules/more_pickers.md
Following the discussion here: https://forum.espruino.com/conversations/397052
I created a module that provides a double picker and a triple picker.
If you want to test quickly you can add `|https://raw.githubusercontent.com/paul-arg/BangleApps/more_pickers/modules` to the Modules URL in the Communication section of the IDE Settings, and use the code snippet provided in the Markdown file.
> New library: add a double picker and a triple picker

- apps/promenu/ChangeLog
- apps/promenu/bootb2.js
- apps/promenu/bootb2.ts
- apps/promenu/metadata.json
- Fixed values going below minimum, if minimum was 0 (i.e. falsy)
- Only call callbacks if something's changed
> promenu: fix values going below minimum, improve callbacks

- apps/daisy/ChangeLog
- apps/daisy/app.js
- apps/daisy/metadata.json
- apps/widbattpwr/ChangeLog
- apps/widbattpwr/metadata.json
- apps/widbattpwr/widget.js
- apps/widbattpwr/widget.ts
- modules/power_usage.js
- modules/power_usage.ts
- typescript/types/main.d.ts
- typescript/types/modules.d.ts
A follow-up to #3477, this adds `require("power_usage")` support
Also updates types (based on espruino/Espruino#2533), specifically for `startsWith()`
> Add power usage module

- apps/sixths/ChangeLog
- apps/sixths/README.md
- apps/sixths/metadata.json
- apps/sixths/sixths.app.js
Major change here is ability to navigate to waypoint.
> sixths v0.05

- apps/measuretime/ChangeLog
- apps/measuretime/measuretime.app.js
- apps/measuretime/metadata.json
- calculate hour number
- make sure to not overflow the max hours/day
> fix(measuretime): hour calculation fix on day-end overlapping hours

- apps/gipy/app.js
- apps/lint_exemptions.js
It is quite hard to test this app, but I believe everything is working correctly.
I did not add a new version because that would interfere with #3528
> gipy: Fix lint issues

- apps/supaclk/ChangeLog
- apps/supaclk/app.js
- apps/supaclk/metadata.json
Adjusted main font size not to overflow on certain times of the day, minor tweaks.
> supaclock: 0.02

- apps/locale/locale.html
As mentioned in https://github.com/espruino/BangleApps/issues/3534#issuecomment-2312135999
Also fixed a bug that meant meridians were never shown. Funny enough, this force solution was perfect for that.
> Support forced meridians

- modules/more_pickers.js
this increases execution tremendously and gives the picker a much nicer feel
> more_pickers: draw sections independently for faster execution

- apps/sixths/ChangeLog
- apps/sixths/README.md
- apps/sixths/metadata.json
- apps/sixths/sixths.app.js
acknowledge commands by	vibration and message
ui tweaks -- bigger font, compressing uninteresting info
display	meters up/down
display	pressure trend
adjust GPS on/off algorithm for more reliable fix
display	warnings when GPS altitude does	not match baro
> sixths: create version 0.10

- apps/boxclk/ChangeLog
- apps/boxclk/app.js
- apps/boxclk/metadata.json
Improves performance, responsiveness, and bug fixes 
- [+] Added box size caching to reduce calculations
- [+] Improved step count with real-time updates
- [+] Improved battery level update logic to reduce unnecessary refreshes
- [+] Fixed optional seconds not displaying in time
- [+] Fixed drag handler by adding E.stopEventPropagation()
- [+] General code optimization and cleanup
> Update boxclk to V0.08

- apps/aviatorclk/ChangeLog
- apps/aviatorclk/aviatorclk.app.js
- apps/aviatorclk/metadata.json
I tweaked the aviatorclk after using it for a few months now.
It includes a couple of changes to improve battery live (don't update METAR if Bluetooth isn't connected, prevent accidental enabling of seconds display), and some functional improvements (continuously display METAR even during updates, work-around for "stuck" GPS updates).
> aviatorclk: v1.02 - various improvements

- apps/setuichange/ChangeLog
- apps/setuichange/boot.js
- apps/setuichange/metadata.json
If custom drag handler is added together with mode updown or leftright throw an exception.
See discussion at https://forum.espruino.com/comments/17445657/ for reference.
@gfwilliams
> setuichange: throw if custom drag on some modes

- lang/da_DK.json
Add danish translations for counter on banglejs2. These are app-specific because I shortened them quite a lot to make them fit on the screen, so they might not be applicable for other apps.
This needs  #3576 to work.
> counter: Add danish translations

- apps/edgeclk/ChangeLog
- apps/edgeclk/README.md
- apps/edgeclk/app.js
- apps/edgeclk/metadata.json
- apps/edgeclk/settings.js
Add option to update step number with every step event (off by default).
> edgeclk: live updates of step count

- apps/widminbt/ChangeLog
- apps/widminbt/metadata.json
- apps/widminbt/widget.js
This is minor change only to ability to be replaced by another bt widget and vice versa
> widminbt is now correct bt widget

- apps/sched/ChangeLog
- apps/sched/clkinfo.js
- apps/sched/metadata.json
> sched: add disabled-event icon

- apps/trail/ChangeLog
- apps/trail/metadata.json
- apps/trail/trail.app.js
I had demo option enabled by default, fix that.
> trail 0.11: bugifx

- apps/messages/ChangeLog
- apps/messages/metadata.json
- apps/messages/settings.js
> messages: settings only loads from storage once

- apps/alpinenav/README.md
- apps/gpsnav/README.md
- apps/rings/README.md
Small fixes to documentation I discovered while browsing applications.
> Various documentation fixes

- apps/orloj/ChangeLog
- apps/orloj/README.md
- apps/orloj/app.js
- apps/orloj/metadata.json
Change the look from (copying from andark), while still providing sunset time and sun position.
> orloj 0.10: rewrite from "andark"

- apps/setting/ChangeLog
- apps/setting/README.md
- apps/setting/metadata.json
- apps/setting/settings.js
> settings: restore previous menu's scroll position

- apps/widbtstates/ChangeLog
- apps/widbtstates/metadata.json
- apps/widbtstates/widget.js
- apps/widbtstates/widget.ts
with a slight typescript hack - avoid generating a new string when we can use a boolean
> widbtstates: generate better js indexing

- apps/assistedgps/custom.html
There was typo preventing all systems to work together.
> assistedgps: Fix combination of all systems

- apps/gpssetup/ChangeLog
- apps/gpssetup/README.md
- apps/gpssetup/app.js
- apps/gpssetup/gpssetup.js
- apps/gpssetup/metadata.json
This is an update to the gpssetup app/module to emulate the PSMOO feature in the Bangle.js1 on the Bangle.js2.
> [gpssetup] Bangle.js2 support

- apps/hasensors/ChangeLog
- apps/hasensors/README.md
- apps/hasensors/boot.js
- apps/hasensors/lib.js
- apps/hasensors/metadata.json
For #3665
- add HRM sensor
- add step count sensor
- add pressure+temperature sensor
- document Home Assistant "unique ID" workaround
> hasensors improvements

- apps/dsky_clock/ChangeLog
- apps/dsky_clock/app.js
- apps/dsky_clock/metadata.json
display seemed out of alignment last version, this should fix it.
> dsky_clock: fix display alignment

- apps/multidice/ChangeLog
- apps/multidice/app.js
- apps/multidice/metadata.json
- apps/multidice/settings.js
I'll try to not spam again ;-;
> added a settings page to multidice

- apps/waypoints/ChangeLog
- apps/waypoints/metadata.json
- apps/waypoints/waypoints.app.js
Implement better arrow pointing to a waypoint. There's more room for improvements there.
> waypoints 0.10: better navigation to a waypoint

- apps/skyspy/ChangeLog
- apps/skyspy/README.md
- apps/skyspy/metadata.json
- apps/skyspy/skyspy.app.js
Internals changed a lot to share code with space race, we now get more statistics.
> skyspy 0.10: add screens with time to fixes and estimate of time to fix

- apps/txtreader/ChangeLog
- apps/txtreader/README.md
- apps/txtreader/app.js
- apps/txtreader/metadata.json
This makes font a bit bigger, and allows user to select font size.
> txtreader: Make font size selectable

- apps/batterybooster/ChangeLog
- apps/batterybooster/metadata.json
- apps/cutelauncher/ChangeLog
- apps/cutelauncher/metadata.json
- apps/onewordclock/ChangeLog
- apps/onewordclock/metadata.json
- apps/textreader/ChangeLog
- apps/textreader/metadata.json
- apps/themes/ChangeLog
- apps/themes/metadata.json
These apps were just introduced with https://github.com/espruino/BangleApps/pull/3750
batterybooster
cutelauncher
onewordclock
textreader
themes
> reset version number to 0.01 for five apps

- apps/terminalclock/README.md
- apps/terminalclock/app.js
- apps/terminalclock/metadata.json
- apps/terminalclock/settings.js
I'm hoping to make some feature changes to the terminalclock app.
This PR makes some code style, white space, and metadata changes using prettier. That way I can maintain a consistent style and keep this separate from functional changes to help reviewers.
> terminalclock: Code style and whitespace changes

- apps/android/ChangeLog
- apps/android/lib.js
- apps/android/metadata.json
@gfwilliams
More context on companion PR to Gadgetbridge https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/4658
> android: handle android STREAM_MUSIC volume level forwarding

- apps/93dub/ChangeLog
- apps/93dub/app.js
- apps/93dub/metadata.json
This PR enables fast loading by following the example at https://www.espruino.com/Bangle.js+Fast+Load.
> Enable Fast Loading for 93Dub watchface

- apps/timecal/ChangeLog
- apps/timecal/README.md
- apps/timecal/metadata.json
- apps/timecal/timecal.app.js
- apps/timecal/timecal.settings.js
https://sebinsuresh.github.io/Add-weather-to-TimeCal/?q=timecal
**About**
This PR updates the TimeCal clock to optionally support weather widgets.
This has been only tested on a BangleJS 2 with Android GadgetBridge for BangleJS app, QuickWeather app, and using the Weather app from the app store.
**Screenshots**
App:
Settings:
> Update TimeCal watch face to support weather integration

- apps/widmp/ChangeLog
- apps/widmp/metadata.json
- apps/widmp/settings.js
- apps/widmp/widget.js
Added ability to hide the moon phase widget.
Hiding occurs whenever the moon color setting would also take effect.
Tested on Bangle 2.
> Added ability to hide moon phase widget

- apps/setting/ChangeLog
- apps/setting/metadata.json
- apps/setting/settings.js
By also saving on reset
Fixes #3814
> Fix settings altitude calibration saving

- apps/vpw_clock/ChangeLog
- apps/vpw_clock/README.md
- apps/vpw_clock/app.js
- apps/vpw_clock/metadata.json
Added AM/PM support to vaporwave watch face
> Added 12 hr view to Vaporwave Clock face

- apps/widmsggrid/ChangeLog
- apps/widmsggrid/metadata.json
- apps/widmsggrid/widget.js
as per https://github.com/espruino/BangleApps/pull/3813#issuecomment-2826952155.
> widmsggrid: reset graphics state after setClipRect

- apps/setting/ChangeLog
- apps/setting/metadata.json
- apps/setting/settings.js
> settings: handle a `undefined` scroller (BJS1)

- modules/widget_utils.js
> widget_utils: only `setLCDOverlay` if present

- apps/qrcode/ChangeLog
- apps/qrcode/custom.html
- apps/qrcode/metadata.json
... for storing multiple QR codes.
Also tidied up `custom.html`
> qrcode: permit custom app names

- apps/clock_info/ChangeLog
- apps/clock_info/lib.js
- apps/clock_info/metadata.json
this allows a user to quickly toggle whether BLE is on/off
> clock_info: add BLE icon

- apps/setting/README.md
Updated readme for better clarity, and ease of use for new users
> [Settings] Update Readme

- apps/setting/ChangeLog
I had recently added the option to set brightness to 0 in settings, but I had put incorrect defaults in the changelog, so I'm fixing that now :)
> [Settings] Update ChangeLog
